Feature/ck 35
woowacourse-teams/2023-co-kirikiri pull request #1
Opened 2023-07-12 13:24 UTC by sh981013s

## 📌 작업 이슈 번호

`35`

https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-35

## ✨ 작업 내용

### 1. directory structure 구조화

```
src
├── App.tsx
├── apis
│   ├── axios
│   ├── goalRoom
│   ├── path
│   ├── roadmap
│   └── user
├── assets
│   ├── fonts
│   ├── icons
│   └── images
├── components
│   ├── @common
│   ├── goalRommListPage
│   ├── goalRoomCreatePage
│   ├── goalRoomDetailPage
│   ├── goalRoomPage
│   ├── mainPage
│   ├── roadmapCreatePage
│   ├── roadmapDetailPage
│   ├── roadmapListPage
│   ├── signUpPage
│   └── userPage
├── constants
│   ├── common
│   ├── goalRoom
│   ├── roadmap
│   └── user
├── hooks
│   ├── common
│   ├── goalRoom
│   ├── roadmap
│   └── user
├── index.tsx
├── mocks
│   └── handlers
├── pages
│   ├── goalRoomCreatePage
│   ├── goalRoomDetailPage
│   ├── goalRoomListPage
│   ├── goalRoomPage
│   ├── loginPage
│   ├── mainPage
│   ├── roadmapCreatePage
│   ├── roadmapDetailPage
│   ├── roadmapListPostPage
│   ├── signUpPage
│   └── userPage
├── styles
│   ├── GlobalStyle.tsx
│   ├── media.ts
│   └── theme.ts
├── types
│   ├── common
│   ├── goalRoom
│   ├── roadmap
│   └── user
└── utils
    ├── common
    ├── goalRoom
    ├── roadmap
    └── user

```

### 2. 언어별 다른 폰트 적용

- 한글: Noto Sans KR
  -  https://fonts.google.com/noto/specimen/Noto+Sans+KR
- 영어: Pro SF 
  - https://developer.apple.com/fonts/ 

```js
// webpack.common.js

      {
        test: /\.(woff(2)?|ttf|eot|svg|otf)(\?v=\d+\.\d+\.\d+)?$/,
        type: 'asset/resource',
        generator: {
          filename: 'static/fonts/[hash][ext][query]',
        },
      }
```

```tsx
// GlobalStyle.tsx

  @font-face {
    font-family: 'Noto Sans KR';
    src: url(${require('../assets/fonts/NotoSansKR-Regular.otf')}) format('opentype');
  }

  @font-face {
    font-family: 'SF Pro';
    font-display: swap;
    src: url(${require('../assets/fonts/SF-Pro.ttf')}) format('truetype');
    unicode-range: U+0041-005A, U+0061-007A;
  }

  :root {
    font-size: 24px; /* for mobile devices */

    @media (min-width: ${BREAK_POINTS.TABLET}px) {
      font-size: 18px; /* for tablet devices */
    }

    @media (min-width: ${BREAK_POINTS.DESKTOP}px) {
      font-size: 16px; /* for desktop devices */
    }
  }

  body {
    font-family: 'SF Pro', 'Noto Sans KR', sans-serif;
  }
```

### 3. minreset.css v0.0.6 적용

- https://github.com/jgthms/minireset.css

### 4. 폰트 사이즈 viewport 사이즈별로 차등화

```tsx
 // GlobalStyle.tsx 

  :root {
    font-size: 24px; /* for mobile devices */

    @media (min-width: ${BREAK_POINTS.TABLET}px) {
      font-size: 18px; /* for tablet devices */
    }

    @media (min-width: ${BREAK_POINTS.DESKTOP}px) {
      font-size: 16px; /* for desktop devices */
    }
  }
```

### 5. theme palette 적용

```tsx
// theme.ts

const theme: DefaultTheme = {
  colors: {
    main_light: '#C8EE44',
    main_dark: '#76A082',
    gray100: '#F2F2F2',
    gray200: '#F5F5F5',
    gray300: '#9E9EAE',
    black: '#000',
    white: '#fff',
    red: '#ff0000',
  },
};
```

### 6. media 유틸 함수 적용

```tsx
// media.ts

import { css } from 'styled-components';
import BREAK_POINTS from '@constants/common/breakPoints';

/*
    Usage:

    import media from '@styles/media';

    const StyledComponent = styled.div`
        ${media.mobile`
            background-color: red;
        `}
        ${media.desktop`
            background-color: blue;
        `}
    `;
 */

const media = {
  mobile: (styles: TemplateStringsArray) => css`
    @media (max-width: ${BREAK_POINTS.MOBILE}) {
      ${styles}
    }
  `,

  desktop: (styles: TemplateStringsArray) => css`
    @media (max-width: ${BREAK_POINTS.DESKTOP}) {
      ${styles}
    }
  `,
};

export default media;
```

### 7. responsive content container 구현

```tsx
// ResponsiveContainer.styles.tsx

import styled from 'styled-components';
import BREAK_POINTS from '@constants/common/breakPoints';
import px2vw from '@utils/common/px2vw';

export const Container = styled.div`
  width: 100%;
  margin-right: auto;
  margin-left: auto;
  background: red;

  @media (min-width: ${BREAK_POINTS.MOBILE}px) {
    max-width: ${px2vw(BREAK_POINTS.MOBILE)};
  }

  @media (min-width: ${BREAK_POINTS.TABLET}px) {
    max-width: ${px2vw(BREAK_POINTS.TABLET)};
  }

  @media (min-width: ${BREAK_POINTS.DESKTOP}px) {
    max-width: ${px2vw(BREAK_POINTS.DESKTOP)};
  }
`;
```

```tsx
// ResponsiveContainer.tsx

import { PropsWithChildren } from 'react';
import * as S from './ResponsiveContainer.styles';

const ResponsiveContainer = ({ children }: PropsWithChildren) => {
  return <S.Container>{children}</S.Container>;
};

export default ResponsiveContainer;
```

## 💬 리뷰어에게 남길 멘트

생각보다 boilerplate 작업이 많이 추가되어 놓친부분이 있을까 걱적이네요. 
리뷰 잘 부탁드립니다! 🙇‍♂️

## 🚀 요구사항 분석

- 언어별 다른 폰트 적용
- viewport size 별 다른 default font size
- viewport size 별 다른 content max-width

2023-07-12 15:41 UTC, evencoding requested changes
너무너무 고생하셨어요
굉장히 신경쓰신 것이 느껴지네요🤩

바로 Approve해도 괜찮다고 생각하긴 하지만, 한가지만 수정 요청을 드리고 싶어요!
`px2vw` 에 대해서는 일관성을 잡고 가면 좋을 것 같다고 생각합니다
`rem`의 경우 파일 이름은 `px2rem`인데 함수의 이름은 `pxToRem`으로 되어있으니 확인 부탁드려요!

2023-07-12 15:41 UTC, evencoding commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.tsx
components 하위의 common 폴더만 `@common`인 이유에 대해서 말씀해 주실 수 있나요?

2023-07-12 15:41 UTC, evencoding commented on client/src/constants/common/breakPoints.ts
> +};
상수 Object에 불변성을 보장하기 위해 readonly 키워드를 적용한 타입을 생성하거나 Object.freeze를 사용하는 것에 대해서 어떻게 생각하시나요?

```tsx
const BREAK_POINTS = {
  MOBILE: 480,
  TABLET: 768,
  DESKTOP: 1137,
} as const;
```
혹은 위와 같이 `as const` 키워드를 적용하는 방법도 있겠네요!

2023-07-12 15:41 UTC, evencoding commented on client/src/styles/GlobalStyle.tsx
> +
폰트 asset의 규격을 ttf, otf로 다르게 하신 이유가 있을까요?
WOFF2를 사용하는 것에 대해서는 어떻게 생각하시는지도 궁금해요!

2023-07-12 15:41 UTC, evencoding commented on client/src/styles/media.ts
> +
👍👍👍👍👍👍 * 3000개

2023-07-12 15:41 UTC, evencoding commented on client/src/styles/GlobalStyle.tsx
> +    unicode-range: U+0041-005A, U+0061-007A;
이런 디테일까지 고민해주셔서 감사해요🥹

2023-07-12 15:41 UTC, evencoding commented on client/src/utils/common/getBasePixel.ts
> +  return 24;
임시로 넣어 둔 함수인가요?
이렇게만 봐서는 뷰포트에 따라 어떤 값을 반환하는 건지 알기가 어려운 것 같아요 (폰트 크기로 생각되긴 합니다)
그렇다면 어떤 기준으로 뷰포트에 따른 base 폰트 크기를 정하신 건지 여쭤봐도 괜찮을까용

2023-07-12 15:41 UTC, evencoding commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.styles.tsx
> +import px2vw from '@utils/common/px2vw';
`px2vw`, `px2rem` 이 유틸 함수들의 파일명과 함수명을 이와 같이 정의하신 데에는 어떤 이유가 있을까요?

어떤 함수는 stringToNumber, 어떤 함수는 number2Boolean과 같은 형태라면 일관성이 깨질 수도 있겠다는 생각이 들어요

2023-07-12 17:41 UTC, NaveOWO reviewed
고생 많았으요~!👍 세심하게 반응형을 고려해서 세팅한 것 같아요!!

2023-07-12 17:41 UTC, NaveOWO commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.styles.tsx
> +import px2vw from '@utils/common/px2vw';
우디의견에 동의요! 개인적으로는 `2`보다는 `to`라는 네이밍이 더 직관적인 것 같아요!

2023-07-12 17:41 UTC, NaveOWO commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.tsx
`@`를 앞에 붙여서 저 폴더를 components 폴더 맨 위로 끌어올리려고 했던게 맞나요?
근데 우리 src 경로 자체를 @를 사용하고있어서 헷갈릴 수 있는 것 같아요!
`@`대신 `_`은 어뗘?

2023-07-12 17:41 UTC, NaveOWO commented on client/src/styles/theme.ts
> +}
저는 이렇게 모듈의 타입을 선언하는 부분은 `style.d.ts`파일로 분리하는게 좋지 않나싶어요! 
안그래도 무리는 없지만, 타입선언과 `theme`를 적용하는 부분을 확실히 분리하는 차원에서요!

2023-07-12 17:41 UTC, NaveOWO commented on client/src/styles/theme.ts
> +
요부분에... font도 들어가면 좋은데, 아침에 후딱 폰트스타일 통일해서 추가해보는건 어떨까요!? (폰트스타일 통일은 제가 할께요!)

2023-07-12 17:41 UTC, NaveOWO commented on client/src/utils/common/px2vw.ts
> +const px2vw = (size: number, width = BREAK_POINTS.DESKTOP) => `${(size / width) * 100}vw`;
이 함수는 어디서 무슨역할을 하는지 궁금해요!

2023-07-12 17:41 UTC, NaveOWO commented on client/src/styles/GlobalStyle.tsx
> +const GlobalStyle = createGlobalStyle`
이 파일만 카멜케이스가 아니네요!😭 수정필요할 것 같아요!

2023-07-13 02:02 UTC, sh981013s commented on client/.eslintrc.cjs
확실히 config 파일에도 컨벤션이 어느정도 적용되면 장점이 많겠네요! 😀
짚어주신 부분 아래와 같이 수정해봤어요!


```js
// .eslintrc.cjs

    'react/jsx-filename-extension': [
      1,
      {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        rules: {
          'space-before-blocks': ['error', 'always'],
        },
      },
    ], 

    'import/no-extraneous-dependencies': [
      'warn',
      {
        devDependencies: false,
        optionalDependencies: false,
        peerDependencies: false,
        rules: {
          'space-before-blocks': ['error', 'always'],
        },
      },
    ],
```

2023-07-13 02:09 UTC, sh981013s commented on client/src/App.tsx
> +import ResponsiveContainer from '@components/@common/responsiveContainer/ResponsiveContainer';
넵넵 정확해요! 저희가 한 디렉토리 내부에 `컴포넌트`,  `스타일` 을 위치시키기로 해서 

폴더 네이밍을 확실히 하기 위해 카멜 케이스를 사용했어요!

2023-07-13 02:12 UTC, sh981013s commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.tsx
> @를 앞에 붙여서 저 폴더를 components 폴더 맨 위로 끌어올리려고 했던게 맞나요?

위 이유가 맞아요! 그런데 path alias 에 `@` 를 사용해 문제가 될 수 있네요!
`_` 를 사용하는 방향으로 수정 진행했어요!

2023-07-13 02:16 UTC, sh981013s commented on client/src/constants/common/breakPoints.ts
> +};
오랜만에 개발하다보니 별걸 다 까먹네요 😅

`as const` 사용하여 불변화 진행했어요!

```ts
// breakPoints.ts

const BREAK_POINTS = {
  MOBILE: 480,
  TABLET: 768,
  DESKTOP: 1137,
} as const;

export default BREAK_POINTS;
```

2023-07-13 02:38 UTC, sh981013s commented on client/src/styles/GlobalStyle.tsx
> +
아아 그부분 고려를 못했네요! 

woff2 형식은 비교적 최근인 2018년 버전의 safari 에서도 문제가 있는 것으로 알고 있어서
woff 형식으로 폰트들 통일했습니다!

2023-07-13 02:41 UTC, sh981013s commented on client/src/utils/common/getBasePixel.ts
> +  return 24;
우선은 테스트용으로 작업하던 유틸 함수였는데 필요가 없어졌네요! 😅

해당 파일 제거했습니다!

2023-07-13 02:47 UTC, sh981013s commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.styles.tsx
> +import px2vw from '@utils/common/px2vw';
확실히 불분명하겠네요..!

`pxToVw` 와 같은 형식으로 모두 변경했어요!

2023-07-13 02:47 UTC, sh981013s commented on client/src/components/@common/responsiveContainer/ResponsiveContainer.styles.tsx
> +import px2vw from '@utils/common/px2vw';
https://github.com/woowacourse-teams/2023-co-kirikiri/pull/1#discussion_r1261916264

동의해요! `to` 로 수정했어요!

2023-07-13 02:50 UTC, sh981013s commented on client/src/styles/theme.ts
> +}
오오 좋아요! `style.d.ts` 로 분리 진행했어요~~

2023-07-13 02:51 UTC, sh981013s commented on client/src/utils/common/px2vw.ts
> +const px2vw = (size: number, width = BREAK_POINTS.DESKTOP) => `${(size / width) * 100}vw`;
일반적으로 피그마 시안을 보고 스타일링을 하게 되는데, 해당 지점에서 피그마에서는 px 가 많이 쓰이기에, 저희가 사용할 vw 로 쉽게 변환하도록 만든 유틸 함수에요!

2023-07-13 03:43 UTC, evencoding approved these changes

2023-07-13 04:43 UTC, evencoding approved these changes
빠르게 반영해주셔서 감사해요😆

대박 굳귯 쫗아용

2023-07-13 05:18 UTC, evencoding approved these changes
변경 사항도 모두 확인했습니다!
고생하셨어요 👍

2023-07-13 06:04 UTC, NaveOWO approved these changes
감사해요~!~!!~! approve할께요! 개발하자 드디어😭

2023-07-13 06:04 UTC, merged