[feat/CK-20] 로드맵 단일 조회 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #10
Opened 2023-07-15 17:34 UTC by younghoondoodoom

## 📌 작업 이슈 번호
[CK-20](https://co-kirikiri.atlassian.net/browse/CK-20)

## ✨ 작업 내용
- 로그인 기능 : 회원이 로그인을 했을 때 사용자 인증를 하고, refreshToken과 accessToken을 발급하도록 했습니다.
- 인가 기능 : 인증된 사용자만(로그인 된 사용자)만 사용할 수 있는 api에 `@Authenticated`이 있으면 Authorization 헤더에 있는 토큰 값을 검증하여 인가 하도록 했습니다.
- 토큰에서 사용자 아이디 찾기 기능 : 사용자 아이디를 알고싶을 때 필드에 `@MemberIdentifier`를 달면 토큰에서 회원 아이디를 찾아오도록 했습니다.
- 테스트 : 테스트 짜는데 시간을 거의 다 쏟은거 같습니다... 혹시라도 부족한 테스트 있으면 꼭 말씀해주세요

## 💬 리뷰어에게 남길 멘트
- 이번에는 로그인도 로그인이지만 저희가 사용할 Interceptor나 ArgumentResolver를 만들었으니 사용하기 불편하실 것 같으면 말씀해주세요.
### @Authenticated 
- 인증된 사용자(로그인 된 사용자)만 사용할 수 있는 api임을 뜻합니다. Controller method에 달아주면 됩니다.
```java
@GetMapping("/test")
    @Authenticated
    public void test() {
        // logic ...
    }
```
### @MemberIdentifier
- 사용자 아이디가 필요할 때 사용할 수 있습니다. Controller에 String인 파라미터 에다가 달아주면 헤더에 있는 Authorization 토큰에서 회원 아이디를 가져옵니다. 여기서 아이디는 identifier입니다.
```java
@GetMapping("/test")
    @Authenticated
    public void test(@MemberIdentifier String identifier) {
        // logic ...
    }
```
- 마지막으로 부족한 테스트 있으면 말씀해주세요!

## 🚀 요구사항 분석
### 로그인 기능

- [x] 아이디와 비밀번호를 입력 받음
- [x] 아이디를 통해 회원을 찾음
    - [x] 회원이 존재하지 않으면 예외를 던짐
- [x] 비밀번호를 암호화하여 대조한다
    - [x] 일치하지 않으면 예외를 던짐
- [x] JWT Token 발급
    - [x] secret key를 HMAC-SHA 알고리즘으로 암호화
    - [x] 토큰에는 만료시간, 회원 identifier이 감
    - [x] access token과 refresh token에 만료 시간이 다르게 들어감

### 인가

- [x] 요청이 들어왔을 때, Authentication header에 있는 토큰 값이 유효한지 확인

### 토큰 재발급

- [x] refresh token을 입력 받음
- [x] refresh token이 유효한지 확인
    - [x] db에 있는 refresh token이랑 일치하는지 확인
    - [x] 일치하면 해당 db에서 refresh token 삭제
- [x] 유효하다면 refresh, access token 새로 생성해서 발급
    - [x] 새로 생성된 refresh token은 다시 db에 들어감
- [x] 유효하지 않다면 예외를 던짐
    - [x] 만료가 됐으면 Expired Token
    - [x] 이상한 문자열이면 Invalid Token

### 토큰으로부터 회원 identifier 찾기

- [x] 토큰에서 subject 빼서 identifier를 찾음.

2023-07-16 19:01 UTC, miseongk requested changes
짧은 기간동안 많은 양의 코드를 구현하셨네요 테스트 수도 엄청 많고요!
정말 고생하셨어요 두둠👍

2023-07-17 01:41 UTC, Cl8D requested changes
고생 많으셨어요 두둠~! 테스트가 진짜 어마어마하게 많네요 ㅋㅋㅋ
테스트 케이스에서 부족한 점은 없는 것 같아요!
간단하게 리뷰 드렸는데 참고 부탁드립니다 🙇‍♀️
+ 추가로 작업하시면서 Intellij에서 `Reformat Code > Clean up Code` 한 번 부탁드릴게요! 코드 스타일이 안 맞는 파일들이 조금 있는 것 같아서요!!

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/JwtTokenProvider.java
> +                            @Value("#{T(Long).parseLong('${jwt.refresh-token-validity-in-seconds}')}") final Long refreshTokenValidityInSeconds) {
`@Value` 어노테이션을 사용하는 것보다, 별도의 프로퍼티 파일로 만들어서 관리하는 건 어떨까요?

```java
@ConstructorBinding
@ConfigurationProperties(prefix = "jwt")
public class JwtProperties() {
	private final int accessTokenValidityInSeconds;
	...
}
```

```java
@ConfigurationPropertiesScan // 별도의 Config 파일로 설정해도 좋아요!
@SpringBootApplication
public class KirikiriApplication {

    public static void main(String[] args) {
        SpringApplication.run(KirikiriApplication.class, args);
    }
}
```

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +class AuthControllerTest extends RestDocsHelper {
테스트양이 어마어마하네요... 👍
정말 고생하셨어요 ㅠㅠ

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +        final ErrorResponse errorResponse = new ErrorResponse("Invalid Token");
예외 메시지는 전부 한글로 가는 게 좀 더 통일성 있지 않을까요? 😶

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/helper/RestDocsHelper.java
> +        return objectMapper.readValue(mvcResult.getResponse().getContentAsString(), typeReference);
👍
공통 메서드 정의 너무 좋아요!
다음 스프린트 때 develop으로 올라가면 기존 코드 이걸로 적용해두겠습니다 ㅋㅋㅋ

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/IntegrationTest.java
> +    protected ObjectMapper objectMapper = new ObjectMapper();
여기는` @SpringBootTest` 어노테이션으로 인해 ObjectMapper를 생성하지 않고 @Autowired를 통한 자동 주입이 가능할 거예요!
아니면 전에 만들어둔 Java Time Module이 지정된 ObjectMapper를 import 해와도 좋을 것 같아요!

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/auth/RefreshTokenRepositoryTest.java
> +    void 정상적으로_토큰으로_취소되지_않은_리프레시_토큰을_찾아온다() {
메서드명이 조금 어색해서, '토큰으로'라는 말은 빼도 괜찮을 것 같아요~

2023-07-17 01:41 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/JwtTokenProviderTest.java
> +    void 정상적으로_subject와_claims를_포함한_REFREST_TOKEN을_생성한다() {
`REFRESH_TOKEN`😶

2023-07-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/test/resources/application.yml
> +jwt:
테스트에서 쓰이는 정보여서 괜찮을 것 같아요! 프로덕션에서는 다른 값들로 진행할 테니까요 😊

2023-07-17 01:47 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/common/interceptor/AuthInterceptor.java
> +                return false;
Interceptor와 ArgumentResolver에 대한 테스트도 있으면 좋을 것 같아요! (테스트 커버리지 때문에 🥹)

2023-07-17 06:47 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/AuthService.java
> +            throw new AuthenticationException("Invalid Token");
부엉이랑 그렇게 합의 했었는데 "토큰이 유효하지 않습니다."로 수정하겠습니다!

2023-07-17 07:03 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/common/interceptor/AuthInterceptor.java
> +        }
정적인 리소스를 내려줄 때는 따로 검사하지 않아도 될 것 같아서 넣었습니다!

2023-07-17 07:54 UTC, Ohjintaek requested changes
늦어서 죄송합니다 두둠
늦게 보내서 다른 분들이 코멘트를 많이 해 주셔서 조금만 했습니다😅

2023-07-17 07:54 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +class AuthControllerTest extends RestDocsHelper {
여기서도 Auth 통합 테스트와 마찬가지로 "identifier1"와 "password1!"을 상수화해서 사용하는 건 어떨까요?

그나저나 인증/인가도 분기가 많아서 통합 테스트도 컨트롤러 테스트도 할 게 많았군요. 수고하셨습니다!!!

2023-07-17 07:54 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/auth/RefreshTokenRepositoryTest.java
> +        assertThat(result).isNotEmpty();
여러 개의 assertThat()을 실행할 때 위의 assertThat이 실패하면 아래가 실행되지 않으니 assertAll 같은 거로 묶는 건 어떨까요?
추가적으로 아래 assertThat()은 디미터 법칙이 지켜지지 않은 거 같아요

2023-07-17 08:27 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/AuthService.java
> +    }
저는 private method로 인해 맨 아래로 내려가기 불편하다고 생각해서 사용 순서대로 하긴합니다!

2023-07-17 13:18 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/auth/RefreshToken.java
> +    @ManyToOne(fetch = FetchType.LAZY)
여러 토큰을 저장하면 2개이상의 디바이스에서 로그인이 가능해집니다! one2one이면 최대 하나만 생성이 가능할테니까요
그리고 만료된 토큰들은 db에서 삭제하고 있습니다!

2023-07-17 13:20 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/auth/RefreshTokenQueryRepository.java
> +    Optional<RefreshToken> findByTokenAndIsRevokedFalse(final EncryptedToken token);
동일한 `token_id`를 가지는 토큰은 존재하지 않습니다! 이 메소드는 암호화된 토큰과 같고, rovoke 되지 않은 RefreshToken을 가져오는 메소드 입니다!

2023-07-17 13:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/auth/vo/EncryptedToken.java
> +    }
음.. 저는 `EncrypedToken`이랑 `EncrypedPassword`가 다른 객체에 의존하면 캡슐화가 깨질 것 같다는 생각이 드네요! 그렇게 되면 각 객체가 사용하는 알고리즘을 각각 관리하기도 힘들 것 같은데 어떻게 생각하시나요?

2023-07-17 14:32 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +                .andDo(print())
저번에도 말씀하셨던것 같은데 까먹었네요😅 
성공한 케이스에 대해서만 넣어놨습니다!

2023-07-17 16:52 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/auth/RefreshTokenRepositoryTest.java
> +        assertThat(result).isNotEmpty();
음, 그렇네요. 그럼 위의 assertThat이 필요없는 게 아닌가요?

2023-07-18 01:19 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/auth/RefreshTokenRepositoryTest.java
> +        assertThat(result).isNotEmpty();
Optional이라 Empty 체크를 안하면 노란불이 떠서..ㅎㅎ

2023-07-18 05:32 UTC, miseongk approved these changes
리뷰 반영하느라 고생하셨습니다😃

2023-07-18 05:32 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/common/interceptor/AuthInterceptorTest.java
> +        final boolean result = authInterceptor.preHandle(request, response, handlerMethod);
오 이렇게 직접적으로 테스트를 할 수 있군요 👍

2023-07-18 05:32 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +import static org.apache.http.HttpHeaders.RANGE;
이게 아닐거에요! 현재는 test/resource/org/springframework/restdocs/templates에 커스텀 스니펫이 없어서 adoc 파일에서 안보이는데, develop에는 있어서(request-fields.snippet 등등) 합쳐지면 저 값이 제대로 안나올거에요..! 제가 해보니까 RANGE -> "range"로 수정하면 될 거 에요! 이거는 나중에 머지할 때 하면 될거같아요~

2023-07-18 07:41 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +import static org.apache.http.HttpHeaders.RANGE;
아까 발견해서 수정 했습니다! ㅋㅋㅋ

2023-07-18 07:41 UTC, Cl8D approved these changes
고생하셨어요 두둠!! 💪
merge 파이팅!!

2023-07-18 09:39 UTC, merged