[feat/CK-149] 골룸 인증피드 내부 전체 인증피드 도출 로직을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #102
Opened 2023-08-08 08:19 UTC by sh981013s

## 📌 작업 이슈 번호

[CK-149](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-149)

## ✨ 작업 내용

![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/81363031/88d710e2-874e-47ed-a4c3-1d294dfaedf5)

- 인증피드 도출 로직 구현
- 골룸 인증피드 컴포넌트에 인증피드 전체 렌더링

## 💬 리뷰어에게 남길 멘트

잘부탁드립니다.

## 🚀 요구사항 분석

- 골룸 인증피드 내부 전체 인증피드 도출 로직 구현

2023-08-08 15:17 UTC, evencoding reviewed
부엉이 너무 잘 작성해주셔서 크게 수정사항이 없습니다🤩
너무너무 고생하셨어요!!

몇가지 코맨트만 확인 부탁드려요!

2023-08-08 15:17 UTC, evencoding commented on client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
> +                style={{ display: 'none' }}
으으 이거 진짜진짜 어떤 느낌인지 아는데ㅠㅠ
그래도 스타일은 styled component에서 주는걸로 통일시키는 것은 어떨까요?

2023-08-08 15:17 UTC, evencoding commented on client/src/myTypes/goalRoom/remote.ts
> +export type GoalRoomCertificationFeedsResponse = Array<CertificationFeedType>;
`Array<CertificationFeedType>`
`CertificationFeedType[]`
둘 중 어떻게 작성할지 팀 컨벤션으로 이야기해봐도 좋을 것 같아요!

현재는 `CertificationFeedType[]`와 같이 작성된 타입이 많은데, 이걸로 통일시키는 것은 어떨까요?

2023-08-09 01:57 UTC, NaveOWO requested changes
리뷰할만한 부분은 우디가 다 짚어준 것 같아요!!  수고햇어요~! Array<> 만 변경해주세요~!

2023-08-09 06:16 UTC, sh981013s commented
> Array<>

변경 적용했습니다~~!

2023-08-09 06:36 UTC, NaveOWO approved these changes
굿!

2023-08-09 06:40 UTC, evencoding approved these changes
부엉이 너무 고생하셨습니다!!

2023-08-15 05:14 UTC, merged