[feat/CK-66] 로드맵을 삭제하는 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #108
Opened 2023-08-11 18:22 UTC by miseongk

## 📌 작업 이슈 번호
[CK-66](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-66)

## ✨ 작업 내용
- 로드맵을 삭제하는 API를 개발했습니다.
- 매일 오전 4시에 로드맵을 삭제하는 스케줄러를 구현했습니다.
- 같이 이야기했던것 처럼 로드맵 삭제 시 해당 로드맵과 골룸에 대한 데이터를 모두 지우도록 했습니다.
- 추가적으로 골룸 인증피드 조회 시 `createAt`을 `LocalDate`로 반환하도록 수정했습니다. (화면에 그대로 뿌려준다고 하셔서 수정했습니다)

## 💬 리뷰어에게 남길 멘트
- 우선 매일 자정에 로드맵을 시작하는 스케줄러가 돌기 때문에 비교적 중요하지 않은 작업인 삭제 스케줄러를 오전 4시에 실행하도록 설정했습니다. (매일 처리하는 것도 굳이 필요없다고 생각이 된다면 간격을 조정해보면 좋을 것 같습니다!)
- `Roadmap`이 가지고 있는 필드인`RoadmapContents`와  `RoadmapNodes` 엔티티에 `CascadeType.Remove` 지정해주었습니다. 로드맵을 삭제할 때 함께 삭제하기 위해 설정했는데, 로드맵은 골룸이 모두 종료된 후에 삭제하기 때문에 Remove를 걸어도 괜찮다고 생각합니다!
- `RoadmapSchedulerTest` 에서 골룸이 완료되고 3개월이 지난 상태를 만들어줄 수 없어서(period 제약조건 때문에) 테스트하지 못했습니다. 하지만 통합테스트에서 이 상황에 대한 테스트를 해서 괜찮을것 같아요 ㅎㅎ
- `RoadmapSchedulerIntegrationTest`에서 골룸의 종료 날짜를 변경해주어야 테스트가 가능하기 때문에 직접 update 쿼리를 작성해서 테스트하기 위해 `IntegrationTestHelper`라는 클래스를 만들었습니다. 피드백 부탁드립니다!

## 🚀 요구사항 분석
- [x]  로드맵을 삭제한다.
    - [x]  로드맵을 생성한 사람만 삭제할 수 있다.
- [x]  골룸이 생성된 적이 없으면 바로 삭제한다.
    - [x]  그에 따른 로드맵 본문, 로드맵 노드, 로드맵 태그도 함께 삭제한다.
- [x]  골룸이 생성된 적이 있으면 3개월 뒤에 삭제한다.
    - [x]  로드맵의 상태를 `DELETED`로 변경한다.
    - [x]  가장 마지막 골룸이 종료되면(골룸의 상태가 `COMPLETED`) 그 이후로 3개월 뒤 삭제된다.
    - [x] 로드맵 삭제 시 관련 골룸에 대한 데이터도 모두 삭제한다.
- [x]  스케줄러로 로드맵을 3개월 뒤에 삭제한다.
    - [x]  매일 오전 4시에 처리한다.

2023-08-14 08:34 UTC, Cl8D requested changes
고생하셨어요 밀리~ 👍
테스트 쪽 트랜잭션 분리 아주 좋아요!!
몇 가지 리뷰 달아봤는데 확인 부탁드려요! 🙇‍♀️

2023-08-14 08:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapSchedulerTest.java
> +        final Roadmap roadmap2 = new Roadmap("로드맵2", "로드맵 설명2", 30, RoadmapDifficulty.DIFFICULT, member1, category);
혹시 `roadmapContent2_1`라는 변수가 있는데, 본문의 수정본을 별도로 두신 이유가 있을까요??
`roadmap2`에 대해 여러 개의 `roadmapContent`를 두는 것을 표현하기 위해서 표현하신 걸가요?_?
그런 의미라면` roadmapContent2_1`,` roadmapContent2_2`가 조금 더 이해하기 쉬울 것 같아요!

2023-08-14 08:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTestHelper.java
> +    }
👍
프로덕션에 불필요한 메서드도 만들 필요 없고 좋네요! 
저는 이상태 너무 좋은 것 같아요!!!
다만, 완료 상태로 변경할 때도 setParameter를 통해 enum 값을 넘겨주면 더 좋을 것 같아요!

2023-08-14 08:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapSchedulerIntegrationTest.java
> +    void 삭제된_상태의_로드맵을_삭제한다() {
핵심이 되는 when절의 경우 로드맵을 삭제하는 것은 맞지만, 내부적으로 골룸이 종료된 지 3개월 이후에 삭제가 가능한 것이니까 이러한 것이 좀 더 메서드명으로 드러나면 좋을 것 같아요!

2023-08-14 08:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapSchedulerIntegrationTest.java
> +        testHelper.골룸을_완료상태로_변경하고_종료날짜를_변경한다(골룸_아이디3, LocalDate.now().minusMonths(4));
`LocalDate.now().minusMonths(4)`의 경우 상당히 핵심적인 변수값이죠!
현재 날보다 4달 전의 값을 구하는 것이기 때문에 별도로 변수로 추출하는 게 더 좋을 것 같습니다 ㅎㅎ

2023-08-14 08:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapSchedulerIntegrationTest.java
> +        assertThat(roadmapRepository.findAll()).hasSize(1);
여기서 size뿐만 아니라 값을 가져와서 해당 골룸의 아이디가 `골룸_아이디2` (지금은 두 번째 골룸 생성 후 리턴을 하지 않아서 없는 값이지만요!) 인지 확인하면 보는 사람 입장에서 테스트를 이해하기 쉬울 것 같아요! 
여담이지만 저는 처음에 첫 번째 메서드랑 뭐가 다르지?... 하고 살짝 헷갈렸어서 ㅎㅎ 넣어주면 더 좋을 것 같습니다!

2023-08-14 08:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapSchedulerIntegrationTest.java
> +        assertThat(roadmapRepository.findAll()).hasSize(1);
요기도 마찬가지로 함께 적용해주면 좋을 것 같아요!

2023-08-15 15:18 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/CheckFeed.java
> +        this.createdAt = createdAt;
아! 이 부분이 저도 추가하면서 고민했는데, 
> 추가적으로 골룸 인증피드 조회 시 createAt을 LocalDate로 반환하도록 수정했습니다. (화면에 그대로 뿌려준다고 하셔서 수정했습니다)

위에 언급했듯이 골룸 인증피드 조회시 날짜만 전달하도록 수정을 해야 했어요. 그래서 LocalDateTime으로 받아온 createdAt을 mapper에서 `createdAt.toLocalDate()`로 변환해서 반환하도록 했어요! 그랬더니 테스트 코드에서 실제로 값이 디비에 저장되지 않을 때 값이 채워지지 않아서 NPE가 뜨더라구요..! 
그래서 mapper에서 toLocalDate()를 하지 않고 @JsonFormat으로 날짜형식으로 반환하려고 시도했더니 또 통합테스트에서 응답값 검증을 할 때 json으로 파싱이 안되는 문제가 있었어요. 
그래서 가장 간단하게 생성자를 만들어서 테스트 했는데, 이것도 좀 찝찝하긴 해요..
통합테스트에서 응답값을 검증하지 않고 상태코드만 비교하도록 할 수도 있을 것 같은데 그게 좋을까요??

2023-08-15 15:22 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +    }
이미 `creatorCond`가 있어서 `creatorIdentifierCond`로 변경했어요!

2023-08-15 15:47 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapCreateService.java
> +        validateRoadmapCreator(roadmapId, identifier);
뭔가 로드맵이 없는 경우와 삭제하려는 사용자가 만든 로드맵이 아닌 경우를 나눠서 예외처리를 해줘야 할 것 같아서 했어요! 
그래서 404와 403으로 구분해서 예외가 내려가요! 
이 부분은 사실 프론트쪽에서 어떻게 처리를 하느냐에 따라 달라질 것 같아요. 만약 프론트쪽에서 예외에 따라 다르게 처리하지 않는다면 굳이 나눠서 쿼리를 두 번 날릴 필요가 없을것 같네요..!

2023-08-15 15:49 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapCreateService.java
> +        }
오..! 왜 이 생각을 못했을까요😭

2023-08-15 16:31 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapScheduler.java
> +                .allMatch(goalRoom -> goalRoom.isCompleted() && goalRoom.isCompletedAfterMonths(3));
네 맞아요! 골룸 생성 구현하신 두둠한테 말씀드리긴 했는데 바쁘시니까 제가 여기서 추가할게요!

2023-08-15 17:25 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapSchedulerTest.java
> +        final Roadmap roadmap2 = new Roadmap("로드맵2", "로드맵 설명2", 30, RoadmapDifficulty.DIFFICULT, member1, category);
> roadmap2에 대해 여러 개의 roadmapContent를 두는 것을 표현하기 위해서 표현하신 걸가요?_?

넵 맞아요! 조금 더 이해하기 쉽게 수정했습니다!

2023-08-15 19:04 UTC, miseongk commented
리뷰 반영 완료했고, 골룸 생성 시 삭제된 로드맵인 경우에 대해 예외 처리 추가했습니다!

2023-08-16 07:25 UTC, Cl8D approved these changes
고생했어요 밀리~ approve 할게요! 👏

2023-08-16 07:27 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +    }
앗 별건 아니지만 value로 빼지 않고 그냥 `new Identifier()` 값을 만들어줘서 비교할 수도 있을 것 같아요~!

2023-08-17 05:31 UTC, merged