feat: 골룸 종료 기능 구현
woowacourse-teams/2023-co-kirikiri pull request #109
Opened 2023-08-12 06:47 UTC by Ohjintaek

## 📌 작업 이슈 번호
[CK-73](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-73

## ✨ 작업 내용
- 골룸 종료 기능을 구현한다
  - 골룸 종료일 다음날 새벽 4시에 자동으로 상태가 COMPLETED가 되도록 Scheduler를 사용해 구현
  - 골룸 종료 시 인증 피드 조회가 필요한 API에서 모든 인증 피드를 조회할 수 있도록 수정

## 💬 리뷰어에게 남길 멘트
- Scheduler를 사용하는 기능 자체는 별 게 없는데 테스트를 못하겠네요. 종료날짜가 어제인 골룸을 만들수가 없어서 테스트 동안 잠깐 서버 시간을 바꾸는 건 어떨까 해서 이것저것 시도해보는데 실패했어요...😥 일단 개발 서버에 직접 데이터를 만들어서 실험해보면 어떨까 싶습니다
- Scheduler를 사용하는 메서드들을 GoalRoomScheduler 클래스에 따로 분리했습니다.
- 원래 인증 피드 조회와 관련해서 진행 중인 노드 동안 올라온 인증 피드만 볼 수 있도록 했었습니다. 하지만 골룸 종료 후에는 골룸 기간 동안 등록된 모든 인증 피드를 조회할 수 있도록 해주었습니다. 사용자 입장에서 골룸 종료 후 자신과 다른 골룸 멤버들이 얼마나 열심히 인증했는지 보고 싶어할 것 같아서 부엉이랑 그렇게 협의했었는데 어떻게 생각하시나요?
 

## 🚀 요구사항 분석
- [x] 골룸을 종료하는 기능을 만든다
    - [x] 골룸 종료 시 골룸 상태가 COMPLETED로 변경되어야 한다
    - [x] 골룸 종료 시 사용자 골룸 단일 조회에서 모든 인증 피드에 대해 조회할 수 있도록 수정한다
    - [x] 골룸 종료 시 인증 피드 전체 조회에서 모든 인즈 피드에 대해 조회할 수 있도록 수정한다
    - [x] 골룸 시작 스케줄러와 부하를 줄이기 위해 명일 새벽 4시에 진행한다

2023-08-13 07:51 UTC, Cl8D requested changes
고생하셨어요 썬샷~!
간단하게 커멘트 몇 개 남겨보았어요!

> 종료날짜가 어제인 골룸을 만들수가 없어서 테스트 동안 잠깐 서버 시간을 바꾸는 건 어떨까 해서 이것저것 시도해보는데 실패했어요...😥 일단 개발 서버에 직접 데이터를 만들어서 실험해보면 어떨까 싶습니다

음... 별도의 클래스로 분리한 다음에 `@Transactional`을 선언해준 다음, 골룸 생성 시 endDate가 어제인 날짜로 (현재 시간의 -1) GoalRoom을 만들어서 save를 해줄 것 같아요! 요런 방법으로는 해결될 것 같은데 한 번 시도해보시면 좋을 것 같습니다!!

2023-08-13 07:51 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
> +                .isEqualTo(List.of(expected1, expected1, expected1, expected2, expected2, expected2));
이 메서드랑 상위의 `골룸이_진행중일_때_특정_노드_동안_등록된_인증_피드들을_조회한다()` 메서드 모두 `인증_피드를_저장한다()` 메서드에서 반환받은 CheckFeed 객체를 expected로 사용한다면 좀 더 명확한 테스트 코드가 될 수 있을 것 같습니다!! (현재는 given 절에 어떤 인증 피드를 저장하는지에 대한 정보가 드러나지 않고, isEqualTo 구문에서 expected1이 여러 번 나오고 이러다 보니까 처음 봤을 때 잘못된 코드인 줄 알고 헷갈렸습니다!)

2023-08-13 08:26 UTC, Cl8D commented
아, 추가적으로 PR 이름이랑 작업 이슈 번호 수정만 부탁드려요!! 🙇‍♀️

2023-08-14 07:48 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
> +                .isEqualTo(List.of(expected1, expected1, expected1, expected2, expected2, expected2));
좋아요!! 그렇게 하면 ignoringFields도 필요없겠네요🤗

2023-08-14 07:57 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
> +                                        partWithName("text").description("인증 피드 본문")
이렇게 하면 HTTP response 보여줄 때 나오긴 하는데 request-parts에서 파라미터를 받진 못하더라구요. 그냥 안 깨진다 정도 수준이에요...

2023-08-14 08:02 UTC, Ohjintaek commented on backend/kirikiri/src/docs/asciidoc/goalroom.adoc
> +operation::goal-room-create-api-test/인증_피드_등록_요청을_보낸다[snippets='http-request,http-response,request-headers,path-parameters,response-headers']
그러면 http-response가 response-fields나 response-header와 같이 요청에 필요한 값들을 모두 보여준 뒤에 오는 게 좋다는 얘기죠? 다른 adoc 파일들이 다 이 형식은 아니었던 것 같아서 맞다면 저 merge할 때 다 수정해놓을게요😆

2023-08-14 09:08 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepositoryImpl.java
> +    }
지금 규칙이 골룸이 진행중일 때는(RUNNING) 현재 진행 중인 노드 기간에 등록된 인증 피드만을 보여주고 있어요.
모집 중일 때는 로직 상으로는 전체 기간에 대해서 조회할 수 있는 상태이지만 인증 피드 등록 자체가 안 돼서 빈 리스트가 반환될 거구요.
완료됐을 때는 골룸에서 전체 등록된 인증 피드를 찾아서 반환합니다.
모집 완료 상태는 삭제해서 고려할 필요는 없습니다.
그래서 골룸의 상태가 RUNNING일 때만 eq조건을 반환하면 돼서 저렇게 구현했는데 잘못된 부분이 있을까요? 피드백 내용을 이해를 못 해서 질문드립니다!!!

그와 별개로 RUNNING 상태일 때 node가 null인 경우라면 예외가 발생을 하는 걸 발견해서 service에서 검증하도록 수정해주었습니다. 또 DB까지 내려가는 상황을 줄이고자 service에서 검증하도록 했지만 혹시나 db에 null 값이 전달되어 error가 나는 상황이 있을까 싶어 repository에도 null 검증을 추가해주었습니다. null 사용으로 인한 위험 포인트를 자주 만나서 고민이 생기네요... 😢

2023-08-15 08:28 UTC, Ohjintaek commented
코드 리뷰 적용하고 밀리 코드를 참고해서 테스트에서만 골룸 날짜를 바꿔서 테스트를 추가해주었습니다

2023-08-15 11:56 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
> +                                        partWithName("text").description("인증 피드 본문")
그래도 안 깨지니까... 해결된 거라고 생각해요 ㅎㅎ... ㅠ_ㅠ

2023-08-15 13:24 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +    }
골룸이 진행 중이면서 골룸의 현재 노드가 비어있는 경우가 한 노드의 종료일과 다른 노드의 시작일 사이에 간격이 있을 경우에 존재하는 것이죠?! (이런 경우가 아니라면 비어있는 다른 경우가 있을까요?? -> 인증 피드가 비어있는 상태여서 제가 잘못 이해한 건가 싶어서요!)
그리고 골룸이 모집 중이거나 종료되었을 경우 현재 노드 값은 항상 비어있게 되겠죠?! (혹시 제가 잘못 이해한 건지 궁금합니다!)

2023-08-15 13:25 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepositoryImpl.java
> +        }
-1인 경우는 혹시 어떤 경우일까요?!
checkFeed의 id 값은 PK인지라 사실상 -1이 들어갈 수 없는 값이지 않나 싶어서요!

2023-08-15 13:28 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +                new GoalRoomRoadmapNodeRequest(로드맵_두번째_노드_아이디, 오늘부터_십일까지_인증_횟수, 이십일_후.plusDays(1), 삼십일_후));
인증 횟수가 모두 동일한 값이 쓰여서 조금 헷갈리네요! 
중요한 필드가 아니라면 `이십일부터_삼십일까지_인증_횟수` 값을 써도 될 것 같아요! (+ 이전 필드는 `십일부터_이십일까지_인증_횟수` 같은 필드를 둬도 될 것 같네요!)

2023-08-15 13:31 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTestHelper.java
> +                .setParameter("goalRoomId", 골룸_아이디)
status값도 setParameter로 설정해주면 더 좋을 것 같아요!

2023-08-15 13:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepository.java
> +            final Optional<GoalRoomRoadmapNode> currentGoalRoomRoadmapNode, final GoalRoomStatus status);
사실 파라미터로 Optional을 넘겨주는 게 좋은 형태는 아닌 것 같아서 조금 고민이네요 ㅠㅠ
(Intellij에서도 warning 형태로 뜨고 있는 부분이기도 하구요!)
저라면 아예 메서드 분리 쪽을 조금 더 고민해볼 것 같아요! (currentRoadmapNode 자체를 사용하는 메서드랑, 사용하지 않는 메서드로요!)

2023-08-15 13:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
> +                null, goalRoom.getStatus());
Optional을 인자로 넘기고 있기 때문에 파라미터로 null 대신에 Optional.empty() 같은 값이 들어가야 할 것 같아요!

2023-08-15 13:38 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepository.java
> +            final Optional<GoalRoomRoadmapNode> currentGoalRoomRoadmapNode, final GoalRoomStatus status);
추가적으로, 문득 느낀 건데 지금 두 메서드에서는 memberImage까지 fetch join으로 가져오는지에 대한 여부잖아요?!
근데 골룸에서 인증 피드 정보 내려줄 때 단순히 사진 정보만 내려주는 게 아니라 해당 사용자 정보는 필요가 아예 없나요?
물론 현 기획상 이미지 정보만 내려주기 때문에 필요없을 것 같기는 한데, 호버링 같은 걸로 어떤 사용자가 올린 인증 피드인지 정도는 나중에 추가될 수도 있지 않나 싶어서 여쭤봅니다!

2023-08-15 18:09 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +    }
말씀하신 것들이 다 맞아요~!!

2023-08-15 18:13 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepositoryImpl.java
> +        }
일단 그 위의 if문 조건이 `status != RUNNING`이니까 아래 코드들은 골룸이 진행 중일 때만 진입을 하게 됩니다
골룸이 진행중인데 전달된 **현재 진행중인 노드**가 비어 있다면(=null) 빈 리스트를 반환하고 싶어요. 그래서 where에서 어떤 조건도 통과할 수 없는 조건을 넣어준 거에요. 져니가 말씀하신대로 id 값에는 -1이 들어갈 수 없으니까요

2023-08-15 18:19 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepository.java
> +            final Optional<GoalRoomRoadmapNode> currentGoalRoomRoadmapNode, final GoalRoomStatus status);
이 부분은 프론트분들이랑 얘기를 한 뒤에 수정해야겠지만 확실히 그렇네요?
프로필 이미지까지는 아니더라도 닉네임이나 아이디 같은 정보는 있으면 좋을 거 같은데 왜 안 넣었는지 모르겠네요 🥴
프론트분들이랑 얘기한 뒤에 동일한 메서드를 쓰도록 바꾸는 게 나을 거 같아요!!

2023-08-16 05:45 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepository.java
> +            final Optional<GoalRoomRoadmapNode> currentGoalRoomRoadmapNode, final GoalRoomStatus status);
일단 변경하게 되면 프론트도 그에 맞춰 코드를 수정해야 하는데 현재 일정상 어렵다고 판단돼서 LEVEL 4때 바꿔야 할 거 같네요

2023-08-16 08:36 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedQueryRepository.java
> +            final Optional<GoalRoomRoadmapNode> currentGoalRoomRoadmapNode, final GoalRoomStatus status);
메서드 분리 다 했습니다~!
Optional이 반환형으로 쓰이는 것을 목적으로 설계되어 파라미터로 전달하는 건 권장하지 않네요

2023-08-17 01:42 UTC, Cl8D approved these changes
고생하셨어요 썬샷~!
정말 마지막으로 리뷰 조금 달았는데 확인 부탁드려요! 🙇‍♀️

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTestHelper.java
> +    @PersistenceContext
이거 develop 쪽에는 `TestTransactionService` 클래스가 있는데 해당 클래스에 넣어주시면 좋을 것 같아요!

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
> +                .ignoringFields("goalRoomTodos")
`goalRoomTodos` 쪽은 왜 ignoringFields 인가요 ?.?

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomSchedulerIntegrationTest.java
> +        assertThat(요청_응답값.status()).isEqualTo("COMPLETED");
enum 값의 name()을 활용해주면 더 좋을 것 같아요!

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/BaseCreatedTimeEntity.java
> +    static final String TIME_FORMAT = "yyyy-MM-dd HH:mm:ss.SSSSSS";
다른 곳에서도 쓰이는 변수일까요? 접근제어자 처리가 필요할 것 같아요!

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
> +    List<CheckFeed> findByGoalRoom(final GoalRoom goalRoom);
엇 `@Param` 어노테이션이 없어도 잘 동작하나요 ?_?

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +        }
이게 더 많은 경우에 적용되는 케이스니까 최하단 return문으로 걸고, `checkFeedRepository.findByRunningGoalRoomRoadmapNode()`에 대해서 running일 때 진행해줌을 명시하면 좋을 것 같아요!

2023-08-17 01:42 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +            throw new BadRequestException("골룸에 참여하지 않은 회원입니다.");
요거는 `Forbidden`으로 거는 게 조금 더 적합할 것 같아요!

2023-08-17 01:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
> +    List<CheckFeed> findByGoalRoom(final GoalRoom goalRoom);
심장이 덜컹했는데 테스트 코드에서 더 엄밀하게 검증해보니 되네요
이전에는 @Param 없이 만들었을 때 되긴 했는데 만약 변수명이 다르면 명시적으로 선언해줘도 좋을 거 같아요

2023-08-17 02:17 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
> +                .ignoringFields("goalRoomTodos")
위에서 expected에 goalRoomTodoReponse에 null이 들어가는 상황이 말이 안 돼서 Collections.emptyList()로 바꿔주고 ignoringFields도 제거해주었어요

2023-08-17 02:45 UTC, merged