Feature/ck 156
woowacourse-teams/2023-co-kirikiri pull request #110
Opened 2023-08-13 09:18 UTC by NaveOWO

## 📌 작업 이슈 번호

## ✨ 작업 내용

## 💬 리뷰어에게 남길 멘트

## 🚀 요구사항 분석

2023-08-13 12:48 UTC, sh981013s approved these changes
야무진 필터링 컴포넌트를 구현해주셨군요..! 우선 어푸르브 드릴게요! 질문사항만 대답 부탁 드려요~~~

2023-08-13 12:48 UTC, sh981013s commented on client/src/myTypes/_common/global.d.ts
> +export {};
궁금해서 그런데 의도를 알 수 있을까요?? 😮

2023-08-13 12:48 UTC, sh981013s commented on client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
> +export default GoalRoomFilter;
너무 좋아요!!! 저도 써야겠네요! 다만 render props 패턴을 사용하는 부분에서 DRY 원칙을 지키기 위함도 있지 않나요? 허나 해당 컴포넌트는 재사용성이 살짝 떨어지는 느낌이 드네요..! 어떤 방식을 취할 수 있을까요?? 😃

2023-08-13 15:18 UTC, evencoding requested changes
네이브 너무 고생하셨어요!
Render Props패턴이 재미있어 보여서 저도 활용해보고 싶네요!

몇가지 코맨트만 확인 부탁드릴게요!!!!

2023-08-13 15:18 UTC, evencoding commented on client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
> +        <GoalRoomFilter>
`Render Props`패턴은 재미있네요!
다양한 디자인 패턴을 잘 알고 계신 것 같아서 멋있어요👍

다만 GoalRoomFilter에 `setSortedOption`을 넘기는 것으로도 구현이 가능했을 것 같은데,
`Render Props`패턴을 도입하신 이유가 궁금해요!
어떤 이점이 있었는지 설명해주시면 감사하겠습니다🤩

2023-08-14 09:43 UTC, NaveOWO commented on client/src/myTypes/_common/global.d.ts
> +export {};
이게..!! 타입을 선언하는 파일에서 이 선언부가 모듈로서 동작하지 않고, 그냥 타입정보만을 제공하기 위해 사용되는 코드에요!!

2023-08-14 09:47 UTC, NaveOWO commented on client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
> +export default GoalRoomFilter;
앗 어떤부분에서 재사용성이 떨어진다는 판단이 들었는지 궁금해요..!! state를 외부에서 받지 않고 골룸만을 위한 상태를 내부에 선언한 것 때문일까요!?

2023-08-14 10:13 UTC, NaveOWO commented on client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
> +    selectedOption: (typeof goalRoomFilter)[keyof typeof goalRoomFilter]
헉 좋은 생각이에요!! type폴더에 객체의 value타입들을 뽑을 수 있는 유틸타입을 만들어둘게요!!

2023-08-14 10:14 UTC, NaveOWO commented on client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
> +    useState<(typeof goalRoomFilter)[keyof typeof goalRoomFilter]>('마감 임박 순');
아하... 진짜 좋은지적 ㅜㅜㅜ 감사해요!!

2023-08-15 05:17 UTC, evencoding approved these changes
너무 고생하셨습니다~!!!

2023-08-15 05:22 UTC, merged