[feat/CK-158] 골룸 시작 API를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #113
Opened 2023-08-14 06:22 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-158](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-158)

## ✨ 작업 내용
- 골룸 시작 API를 구현하였습니다. 이미 있는 기능에 API만 추가한 거여서 오래 걸리지 않았어요 ㅎㅎ

## 💬 리뷰어에게 남길 멘트
- 이전의 PR과 마찬가지로 E2E 테스트의 경우 리팩터링 끝나면 진행하는 게 좋을 것 같아서 지금 진행하지 않았습니다!!

## 🚀 요구사항 분석
- 골룸을 수동으로 시작하는 API를 구현한다.
    - 골룸을 생성한 사용자만 시작할 수 있다.
    - 골룸의 시작 날짜가 오늘이어야 시작이 가능하다.

2023-08-14 09:24 UTC, miseongk requested changes
져니 고생하셨어요!!
빠르게 잘 구현해주셨네요👍
큰 리뷰는 없고 제 생각 하나 남겼으니 확인 부탁드립니다~!

2023-08-14 09:24 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +        goalRoomPendingMemberRepository.deleteAll(goalRoom);
이전에 골룸 시작하는 기능을 제가 구현하긴 했는데, 또 갑자기 드는 생각이 repository로 직접 쿼리를 날리지 않고 객체에 add와 remove를 해주는게 조금 더 객체지향적일 것 같다는 생각이 드네요..!
그런데 이렇게 할 때의 단점이라고 한다면 goalroom을 조회해올 때 GoalRoomPendingMember와 GoalRoomMember를 페치조인해와야 한다는 점인 것 같아요. (프록시 상태에서 add를 못하는게 맞다면요..!)
져니는 어떻게 생각하시나요??

2023-08-14 09:24 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +    private void saveGoalRoomMemberFromPendingMembers(final List<GoalRoomPendingMember> goalRoom) {
`goalRoom`이라는 변수명보다 `goalRoomPendingMembers`가 좋겠네용!

2023-08-15 16:54 UTC, Cl8D commented
요기까지 리뷰 반영 완료했습니다~!

2023-08-16 02:28 UTC, miseongk approved these changes
리뷰 반영하신거 확인했습니다~! 고생하셨어요!!

2023-08-16 02:28 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        // TODO 사용자 골룸 조회 시 리더인지 팔로워인지 정보가 필요하지 않을까?
오 그러네요 필요할 것 같네요!

2023-08-16 02:34 UTC, merged