[feat/CK-147] 골룸 생성 페이지 고도화 및 유효성 검사를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #114
Opened 2023-08-14 07:15 UTC by evencoding

## 📌 작업 이슈 번호
CK-147

## ✨ 작업 내용
- [x] useFormInput 고도화
- [x] 골룸 생성 validation
- [x] 골룸 생성 노드 데이터 맵핑
- [x] InputField 컴포넌트 생성
- [x] 인원수 Input 항목 추가

## 💬 리뷰어에게 남길 멘트

혹여나 잘 이해가 가지 않는 부분이 있다면 언제든 말씀해주세요
화면공유하고 따로 설명드리겠습니다😭

잘 부탁드립니다!

https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/1439aa45-7c5f-498c-96d2-d707e15882d4

2023-08-14 07:55 UTC, sh981013s requested changes
커밋 기록을 다 보며 확인했는데 계속 훅이 진화하는게 인상적이었어요! ㅋㅋㅋㅋㅋ

너무 고생하셨고, 리뷰 내용만 확인 부탁드려요! vㅔ리 굳입니다!!

2023-08-14 07:55 UTC, sh981013s commented on client/src/tests/utilTests/isCurrentOrFutureDate.test.ts
> +});
순수하게 궁금한게 이 하나의 테스트로 테스트 커버리지가 80% 이상이 나왔었나용?? 😮

2023-08-14 07:55 UTC, sh981013s commented on client/src/hooks/_common/useFormInput.ts
> +  const [error, setError] = useState<FormErrorType>();
초기 값을 넣어주지 않아 `undefined` 가 나올경우가 있을 것 같네요..! `null` 값이나 `{}` 빈 객체를 초기 값으로 할당하는 것은 어떨까요? 🫡

2023-08-14 07:55 UTC, sh981013s commented on client/src/hooks/_common/useFormInput.ts
>            };
로대쉬가 그리워지는 로직이군요..! 😀

2023-08-14 07:55 UTC, sh981013s commented on client/src/hooks/_common/useFormInput.ts
> +        const isValid = validate(String(fieldValue));
`validateInputValue` 와 `handleSubmit`  함수에서 유효성 검사 로직이 중복되는 것처럼 보이는데 의도된 상황일까여?? 🙂

2023-08-14 07:55 UTC, sh981013s commented on client/src/hooks/_common/useFormInput.ts
배열 핸들링이 코드에 들어가 살짝 복잡해지는 감이 있는데,  아래와 같이 분리해보는건 어떨까여?? 😁

```ts
const handleArrayUpdate = (baseName: string, arrayIndex: string, arrayPropName: string) => {
  // 배열 업데이트 로직
};
```

2023-08-14 07:55 UTC, sh981013s commented on client/src/utils/_common/transformDateStringsIn.ts
> +};
`transformDateStringsIn` 이라는 네이밍이 조금 애매한 것 같아요! 네이밍만 봐서는 어떤 함수인지 알기 힘들 것 같네요 🥲

그리고 유틸 함수인만큼 설명과 간단한 사용예시정도를 주석으로 달면 어떨까여??  🙂

2023-08-14 07:55 UTC, sh981013s commented on client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
> +};
해당 부분을 실 사용처에서 만드는 것이 좋을까요? 아니면 분리해서 따로 모아놓는 것이 좋을까요? 저는 헷갈리네요 우디의 의견이 궁금합니다!

2023-08-14 07:55 UTC, sh981013s commented on client/src/components/goalRoomCreatePage/createGoalRoomForm/createGoalRoomValidations.ts
> +      return { ok: true };
제가 놓친부분이 있는 것 같은데 `ok` property는 어디에 쓰이나요?

2023-08-14 07:55 UTC, sh981013s commented on client/src/hooks/_common/useFormInput.ts
> +  const [error, setError] = useState<FormErrorType>({});
엇 아까 리뷰 남겼던 부분이 여기서 이미 해결이 되었군요..!!! 👍👍👍👍

2023-08-14 07:55 UTC, sh981013s commented on client/src/hooks/_common/useFormInput.ts
> +    if (isFormValid()) callback();
`callback` 보다는 `callbackFn` 혹은 `callbackFunction` 같이 조금 더 명시적이면 인자로 받은 콜백 함수겠구나~ 하고 판단하기 조금 더 편하지 않을까 생각이 드네요! 어떻게 생각하시나용

2023-08-14 07:55 UTC, sh981013s commented on client/src/utils/_common/isEmptyString.ts
> +export const isEmptyString = (value: string) => value.length === 0;
음 개인적으로 유틸 함수의 경우에는 팀원 모두가 자주 쓰게 될 것 같아서 모두 간단한 설명과 사용예시를 담은 주석을 추가하는건 어떨까용?? 😀

2023-08-14 07:55 UTC, sh981013s commented on client/src/utils/_common/isNumeric.ts
> +export const isNumeric = (value: string) => /^[1-9]+\d*$/.test(value);
주석 부탁려용~~

2023-08-14 07:55 UTC, sh981013s commented on client/src/utils/_common/isValidMaxLength.ts
> +  return value.length <= max;
주우썩 부탁드려용~~

2023-08-14 14:09 UTC, NaveOWO commented on client/src/components/_common/InputField/InputField.tsx
> +const InputField = ({ ...props }: InputFieldProps) => {
여러 props를 받아서 Input을 사용할 수 있게 한거 너무 좋은 것 같아요!! 우디 고민한 티가 많이나고 너무 수고많았어요ㅠㅠ  조금 더 다듬어서 서비스 내 모든 input에 적용해켜봅시당!!
지금 당장은 아니고 리팩토링할 때 했으면 하는 부분들 여기에 정리해놨습니다!
https://www.notion.so/d0b3ea6e9cf44703ab9c3a10bb6e1b96

2023-08-14 14:12 UTC, NaveOWO commented on client/src/hooks/_common/useFormInput.ts
> +export type FormErrorType = {
타입 선언부 모두 myTypes 폴더로 분리 하는게 좋을 것 같아요~!

2023-08-14 14:29 UTC, NaveOWO commented on client/src/hooks/_common/useFormInput.ts
> +    if (typeof validations?.[name] !== 'function') return true;
타입 선언부를 보면 validations는 함수를 string인 key와 function인 value를 갖는 객체인 것 같은데, value의 타입이 'function'이 아닌 경우는 왜 구분해준건지 궁금해요!

2023-08-14 15:57 UTC, NaveOWO commented on client/src/hooks/_common/useFormInput.ts
> +      const result = validations[key](String(getNestedValue(formState, key)));
객체의 정확한 타입 추론을 위해서 util 폴더의 invarientType에 있는 유틸함수르 이용해서 object.keys()를 사용해주세요!

2023-08-14 15:57 UTC, NaveOWO reviewed
우디 너무너무 수고햐셨어요~~!~!!!! 코멘트 확인해주세요~!

2023-08-15 05:20 UTC, NaveOWO approved these changes

2023-08-15 05:21 UTC, sh981013s approved these changes
vㅔ리 굳이에용~~

2023-08-15 05:21 UTC, merged