[feat/CK-55] 모바일과 웹 환경에 따른 Header와 NavBar의 기본 뼈대를 구현하다
woowacourse-teams/2023-co-kirikiri pull request #12
Opened 2023-07-16 09:15 UTC by evencoding

## 📌 작업 이슈 번호
https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-55

## ✨ 작업 내용
- 모바일 환경에서의 Header 구현
- NavBar 구현
- 모바일 환경일 때 Header와 NavBar의 상호작용 구현

## 💬 리뷰어에게 남길 멘트
UI작업을 위해서 Header, NavBar의 뼈대와 기본적인 상호작용을 구현했습니다.

보통의 경우 Header에서 NavBar가 확장되는 형태로 구현되지만, 이번의 경우는 조금 달랐습니다.
웹 환경에서는 Header는 없지만 NavBar가 존재하고. 모바일 환경에서는 Header가 존재하고 NavBar가 선택적으로 존재해야했어요.
즉, Header와 NavBar가 완전히 별개로 존재해야 했습니다.

때문에 모바일 환경에서 조금 복잡하게 보일 수 있는데 아래의 그림과 같습니다.
<img width="594" alt="image" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/334c33bc-bf63-4aa7-ae80-a5d0845967c8">

또, Web 환경에서 메인 컨텐츠가 들어갈 공간을 NavBar의 공간과 구분짓기 위해서 PageLayout의 children을 ChildrenLayout으로 감싸줬습니다.

실제 브라우저로 확인하면 아래와 같습니다.
빨간 화면은 실제 컨텐츠가 들어가는 공간입니다.

### Web View
 
![스크린샷 2023-07-16 오후 5 50 51](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/5c1ecc73-a939-4dd0-be9b-e1486ea99616)

### Mobile View
#### isNavBarOpen === false
![스크린샷 2023-07-16 오후 5 51 11](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/6bfbacd8-9574-4d5a-8803-a496637bbfeb)

#### isNavBarOpen === true
![스크린샷 2023-07-16 오후 5 51 26](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/e75c25ca-14df-4490-a709-64d8f77e3cdb)

2023-07-16 12:57 UTC, sh981013s commented
레전드 레전드 레전드.... 너무 좋네요!!!

어서 레이아웃 위에서 개발하고 싶어요! 고생하셨어요 🫡

2023-07-16 13:04 UTC, sh981013s requested changes
너무 고생하셨어요! 👍👍👍

몇가지만 확인해주세여~

2023-07-16 13:04 UTC, sh981013s commented on client/src/components/_common/header/Header.tsx
> +      {isNavBarOpen && <S.CloseNavBackground onClick={toggleNavBarState} />}
제가 헷갈려서 그런데 lint 가 적용되어 있는게 맞을까여? 😅

2023-07-16 13:04 UTC, sh981013s commented on client/src/components/_common/header/Header.styles.ts
> +  z-index: 100;
z index 도 옵션이 정해져 있는것 같은데 상수화를 해보면 어떨까용?

2023-07-16 15:19 UTC, NaveOWO requested changes
우디 덕분에 레이아웃 잡고 편하게 개발할 것 같아요!!! 굿굿!!!👍

2023-07-16 15:19 UTC, NaveOWO commented on client/src/components/_common/header/Header.styles.ts
> +  z-index: 200;
저는 `z-index` 사용을 지양하는 편인데요..!! 화면에 컴포넌트들이 쌓이다보면 컴포넌트가 마음대로 화면에 보이지 않을 때 원인이 z-index를 통해 임의로 정해놓은 컴포넌트 순서때문일 때가 많더라구요!!
우디가 z-index를 사용했다면 이유가 있을 것 같은데 왜인지 궁금해요!

2023-07-16 15:19 UTC, NaveOWO commented on client/src/components/_common/header/Header.tsx
> +const Header = () => {
그리고 `Header`  랑 `Nav바`는 스크롤 해도 위치가 고정되게 `position sticky`를 주는건 어때요!?

2023-07-16 15:19 UTC, NaveOWO commented on client/src/components/_common/header/Header.tsx
> +  };
이렇게 열었닫 닫았다 하는 로직은 조금 더 추상화 시켜서 훅으로 빼면 코드 전반에서 공통적으로 사용할 수 있을 것 같아요!

2023-07-16 15:19 UTC, NaveOWO commented on client/src/components/_common/navBar/NavBar.tsx
> +const NavBar = ({ isNavBarOpen }: NavBarProps) => {
컨벤션에 추가되어야할 부분인 것 같은데, 저는 `props`의 갯수가 늘어날 수도 있는 확장성을 고려해서 컴포넌트의 파라미터 부분에는 `props : Type` 형태로 써주고
`const { 인자들 } = props;`
형태로 구조분해할당을 해주는데, 이부분을 통일하면 좋을 것 같아요!!
우디랑 부엉이는 어떤게 편하세요!?

2023-07-16 15:19 UTC, NaveOWO commented on client/src/components/_common/pageLayout/PageLayout.styles.ts
> +  padding: 0 18px;
코드 전반적으로 px이 보여요!! rem으로 변경하는게 좋을 것 같아요!

2023-07-16 15:46 UTC, sh981013s commented on client/src/components/_common/navBar/NavBar.styles.ts
> +`;
사소한 부분이지만 이런 속성이 별로 없고 많이 쓰일 것 같은 컴포넌트는 따로 분리 후 재사용 할 수 있게 하는건 어떨까요??

2023-07-17 04:40 UTC, closed without merging

2023-07-17 14:34 UTC, evencoding commented on client/src/components/_common/header/Header.tsx
> +      {isNavBarOpen && <S.CloseNavBackground onClick={toggleNavBarState} />}
적용이 되어있습니다🤩

2023-07-18 03:13 UTC, evencoding commented on client/src/components/_common/navBar/NavBar.styles.ts
> +`;
테스트를 위해서 만들어둔 현재 사용되지 않는 스타일 컴포넌트인데, 제가 깜빡하고 지우지 않았네요😭
제거해뒀습니다!!