[feat/CK-166] 골룸 리스트 페이지 버그 수정 및 무한 스크롤을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #120
Opened 2023-08-16 07:16 UTC by evencoding

## 📌 작업 이슈 번호
CK-166

## ✨ 작업 내용
- [x]  골룸 무한스크롤
- [x]  골룸 들어가기
- [x]  골룸 리스트 height 늘어짐
- [x]  골룸 디테일 모달 content 영역 눌러도 꺼짐
- [x]  골룸 생성하고 list refetching (invalidation)
- [x]  골룸 목록 페이지에서 버튼으로 골룸 생성 페이지 이동할 때 터짐 (Suspense)

## 💬 리뷰어에게 남길 멘트
잘 부탁드리겠습니다~!!!

2023-08-16 07:28 UTC, sh981013s requested changes
마치 저와 생각을 공유한듯한 느낌은 뭐죠? 😆 
너무 재밌게 리뷰했습니다!!

다만, 기존에 없던 기능이니 제대로 돌아가는 모습을 보여주는 사진, 혹은 짧은 영상정도는 첨부해주시면 좋읗 듯 싶어요! 아무래도 머지가 될 친구니까요!

그리고 전반적으로, 안전성과 캐싱 효율성을 위해 `get` 하는 쿼리문에서 쿼리키에 두번째 요소로 들어가는 
 dependent 엘리먼트가 존재한다면 써주는게 어떨까요?? 

추후에 invalidation 처리를 할때도 확실하기도 하고요! 😁😁

2023-08-16 07:28 UTC, sh981013s commented on client/src/hooks/queries/goalRoom.ts
> +        await queryClient.invalidateQueries([['myGoalRoomList']]);
roadmapContentId 를 query key 배열 두밴째로 넣어줘야 안전할 것 같아요! 그리고 Querykey 는 상수화 부탁드려용~

2023-08-16 07:28 UTC, sh981013s commented on client/src/components/_common/wavyLoading/WavyLoading.tsx
> +export default WavyLoading;
기존에 있던 wavy lodaing component 와는 다른건가용??

2023-08-16 07:28 UTC, sh981013s commented on client/src/hooks/queries/goalRoom.ts
> +        await queryClient.refetchQueries([['myGoalRoomList']]);
여기에도 배열 두번째 인자와 QueryKeys 상수화 부탁드릴게여!

2023-08-16 07:39 UTC, evencoding commented on client/src/hooks/queries/goalRoom.ts
> +        await queryClient.invalidateQueries([['myGoalRoomList']]);
오 빼먹었었네요!
매의 눈 감사합니다!

하는김에 goalRoom.ts 파일 내부 모든 QueryKey에 대하여 상수화 진행했습니다!!

2023-08-16 08:21 UTC, sh981013s approved these changes
vㅔ리 좋습니당~~~~~~~ 고생하셨어요!!!!!!!!!! 굳굳

2023-08-17 02:58 UTC, NaveOWO approved these changes
우디 너무 수고많았어요~! 무한스크롤 므찌게 했네요!

2023-08-17 02:58 UTC, NaveOWO commented on client/src/hooks/queries/goalRoom.ts
> +  const { data: goalRoomRes } = useSuspendedQuery(
사소한 부분인데, goalRoomResponse 로 네이밍 컨벤션을 지켜도 좋을 것 같아요~!

2023-08-17 04:48 UTC, evencoding commented on client/src/hooks/queries/goalRoom.ts
> +  const { data: goalRoomRes } = useSuspendedQuery(
이게 뭐지..ㄷ.ㄷ..
바로 수정하겠습니다!!

매의 눈 👍

2023-08-17 04:52 UTC, merged