[feat/CK-185] 툴팁(Tool Tip)을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #140
Opened 2023-09-03 13:21 UTC by evencoding

## 📌 작업 이슈 번호
CK-185

## ✨ 작업 내용
- [x] Tool Tip 컴포넌트 구현

## 💬 리뷰어에게 남길 멘트
잘 부탁드립니다!!

## 🚀 요구사항 분석
- 사용자에게 부가적인 설명을 전하기 위한 Tool Tip 컴포넌트 구현

### 사용법
```jsx
<ToolTip>
  이와 같이 설명 글을 넣어줍니다. <strong>강조</strong>하고 싶은
  글에는 이와 같이 <strong>strong 태그</strong>로 감싸줍니다.
</ToolTip>
```

### onHover
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/c8a7615f-675d-43fe-a9c4-6c97b9b9e08e

### onActive
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/2cb88a35-6cdd-446a-95b7-dc86f25bb0a3

2023-09-13 08:38 UTC, NaveOWO approved these changes
너무 잘햇네요 우디!!! 수고하셨어요~!

2023-09-13 15:44 UTC, sh981013s requested changes
우디 넘나 고생쓰 하셨습니다! 살짝 억까를 해보자면 툴팁인만큼 `!` 느낌표 아이콘 보다는 `?` 물음표 아이콘이 어떨까 생각하네용

그리고 추후에 컴파운드로 개편해도 좋을듯? 싶다는 생각도 들었슴다 ㅎㅎ

리뷰 한번 확인 부탁드려요~

2023-09-13 15:44 UTC, sh981013s commented on client/src/components/_common/toolTip/ToolTip.styles.ts
> +export const ToolTipContent = styled.span<{ isShow: boolean }>`
넘나 고생하셨어요! 허나 `ToolTipContent` 에 span 태그를 할당한 이유가 있을까여??

저도 `p` vs `span` 을 곰곰히 생각하며 자료를 찾다가 다음과 같은 자료를 발견했어요! 우디의 의견이 궁금쓰 하네요

> Span is completely non-semantic. It has no meaning, and serves merely as an element for cosmetic effects.

> Paragraphs have semantic meaning - they tell a machine (like a browser or a screen reader) that the content > they encapsulate is a block of text, and has the same meaning as a paragraph of text in a book.

[출처](https://stackoverflow.com/questions/1908234/when-to-use-span-instead-p)

2023-09-14 04:16 UTC, evencoding commented on client/src/components/_common/toolTip/ToolTip.styles.ts
> +export const ToolTipContent = styled.span<{ isShow: boolean }>`
좋은 지적 감사해요 부엉이🤩

툴팁에는 의미있는 문단이 들어가니 p태그를 사용하는 것이 좋다고 생각되네요!
수정했습니다!!

2023-09-14 12:56 UTC, sh981013s approved these changes
고생하셨으요~~

2023-09-14 12:56 UTC, merged