[feat/CK-183] 사용자 역할(어드민, 일반 사용자)을 추가한다
woowacourse-teams/2023-co-kirikiri pull request #143
Opened 2023-09-08 05:00 UTC by miseongk

## 📌 작업 이슈 번호
[CK-183](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-183)

## ✨ 작업 내용
- 사용자를 어드민과 일반 사용자로 나누기 위해 `Member` 엔티티에 `role` 필드를 추가했습니다.
- 사용자 역할을 구분하기 위해 JWT에 role 정보를 추가했습니다. 
- 어드민 권한이 필요한 API를 구분하기 위해 `@AdminPermission` 어노테이션을 만들었습니다. 어드민 권한이 필요한 API 메서드 위에 붙여서 사용하시면 됩니다.
- 로드맵 생성 api를 어드민 권한으로 변경했습니다. 
- 어드민 계정으로 회원가입하기 위한 API를 따로 만들었습니다. (`/member/join/admin`)
- 로그인 시 기존에는 토큰 정보만 반환하는데, 어드민 계정인지 확인할 수 있는 `isAdmin` 필드를 추가했습니다.

## 💬 리뷰어에게 남길 멘트
- 두둠이 만드신 카테고리 생성 API는 머지할 때 어드민 권한으로 변경하겠습니다!
- API에 어노테이션 판별할 때, `AuthInterceptor`에서 모두 처리하는데, `@AdminPermission`이 붙은 메서드는 따로 `@Authenticated`을 붙이지 않도록 하기 위해서 로직이 중복되는데 딱히 처리할 방법이 없더라구요.. 메서드로 분리해서 재사용하면 되긴 한데 오히려 가독성이 안좋은 것 같아서 그냥 놔뒀습니다. 확인 부탁드려요! 
- 테이블에 role 컬럼을 추가하면서 flyway에 sql을 작성했는데요. flyway가 이미 존재하는 데이터에 값을 추가해주지는 않기 때문에, 일단 not null 제약조건을 붙이지 않았어요! 그래서 `Member` 엔티티에도 `nullable`하도록 했습니다. 기존 데이터에 role을 넣어준 뒤에 not null로 바꾸면 될 것 같은데 어떠신가요?!

## 🚀 요구사항 분석
- [x]  어드민 계정으로 회원가입하는 API 구현
    - [x]  Member 엔티티에 role 필드 추가
- [x]  JWT 토큰에 역할 정보 추가
- [x]  어드민 API용 어노테이션 만들기
    - [x]  로드맵 생성
    - [ ]  카테고리 생성 (머지하면서 하기)
- [x]  로그인 시 어드민 계정인지 boolean값 반환하기
- [x]  flyway 적용하기

2023-09-10 12:24 UTC, Ohjintaek approved these changes
깔끔한데요!! 회원가입 관련 부분이라 테스트에 추가할 부분이 많았겠네요ㅎㅎ
저는 바로 Approve하겠습니다~

2023-09-11 06:24 UTC, younghoondoodoom requested changes

2023-09-11 06:24 UTC, younghoondoodoom commented on backend/kirikiri/src/main/resources/db/migration/V3_alter_role_column.sql
> +    ADD role varchar(10) default 'USER';
production 서버에도 적용해야겠네요!

2023-09-11 06:24 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/common/interceptor/AuthInterceptorTest.java
> +        // when
디테일 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저는 붙혀쓰는데..

2023-09-11 06:24 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthCreateApiTest.java
> +                false);
어드민 계정이 로그인 성공했을때에 api test도 만들어주시면 좋을 것 같아요!

2023-09-11 06:24 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        final Long 기본_로드맵_아이디 = 로드맵_생성(기본_로드맵_생성_요청, 어드민_로그인_토큰);
이 파일의 로그인 토큰을 모두 어드민 토큰으로 바꾸신 이유가 있나요?

2023-09-11 06:24 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +        final Long 기본_로드맵_아이디 = 로드맵_생성(기본_로드맵_생성_요청, 어드민_로그인_토큰);
이 파일도 왜 다 토큰을 바꾸신건지.. 다른 파일들도요!

2023-12-10 10:57 UTC, closed without merging