[feat/CK-184] 회원가입 API 수정을 반영하고 유효성 검사를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #146
Opened 2023-09-12 14:31 UTC by evencoding

## 📌 작업 이슈 번호
CK-184

## ✨ 작업 내용
- 회원가입 Form에서 전화번호, 생년월일 필드 제거
- useInputForm의 Validation 적용
- Email 필드 추가

## 💬 리뷰어에게 남길 
https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/9a288885-2269-4150-971d-0c57b08e82af
현재 에러 메시지가 onChange시에 발상하는데, 보다 나은 사용성을 위해서는 onBlur 시에 에러 메시지를 표시함과 동시에 해당 필드를 focus하는 편이 좋겠다고 생각합니다
현제 PR이 merge되는데로 useFormInput 훅에서 대응 가능하도록 하겠습니다!

## 🚀 요구사항 분석
- 회원가입 API 변경 반영
- 회원가입 유효성 검사

2023-09-13 06:55 UTC, NaveOWO approved these changes
수정사항 없습니다~!!! useForm을 잘 만들어놓으니깐 사용도 편리한 것 같아요!! 우디 수고많았어요!!!!

2023-09-13 06:55 UTC, NaveOWO commented on client/src/components/signUpPage/signUpValidations.ts
> +};
우디 그런데 이 validations파일이 왜 components 폴더 하위에 있는걸까요?!?

2023-09-13 07:10 UTC, sh981013s requested changes
넘나리 고생쓰 하셨어요~~ 사소한거 몇부분 있는데 확인만 부탁드릴게여!

2023-09-13 07:10 UTC, sh981013s commented on client/src/components/signUpPage/signUpValidations.ts
> +};
저도 동감쓰요..!

2023-09-13 07:10 UTC, sh981013s commented on client/src/components/signUpPage/signUpValidations.ts
> +        ok: false,
사소한부분이지만 조금 더 명시적으로 불린을 반환하고 검사를 통과했냐는 뜻을 가지게끔 `isOk` 같은 느낌은 어떨까여??

2023-09-14 04:45 UTC, evencoding commented on client/src/components/signUpPage/signUpValidations.ts
> +        ok: false,
그것도 좋을 것 같아요!

`fetch`의 `response`에서 `ok`라는 속성으로 성공 실패를 boolean으로 나타내서 일관적으로 `ok`속성을 사용하고 싶었어요!
바꾸는 게 좋을까요?😭

2023-09-14 05:15 UTC, evencoding commented on client/src/components/signUpPage/signUpValidations.ts
> +};
validation이 ~~Form에 매우 족송적, 심지어 동적으로 생성되기도 하기 때문에(createGoalRoomForm에서) Form 파일이 있는 곳에 함께 두면 어떨까? 생각했습니다
현재는 signUpPage 하위에 있었기 때문에 Form 폴더를 생성해서 구조를 변경해주었습니다!

다른 의견 있으시면 제안 부탁드려요🤩

2023-09-14 12:57 UTC, sh981013s approved these changes
고생하셨으요~~

2023-09-14 12:58 UTC, merged