Feature/ck 187
woowacourse-teams/2023-co-kirikiri pull request #148
Opened 2023-09-12 18:20 UTC by NaveOWO

## 📌 작업 이슈 번호

## ✨ 작업 내용

## 💬 리뷰어에게 남길 멘트

## 🚀 요구사항 분석

2023-09-13 07:46 UTC, sh981013s requested changes
크으으.. 진짜 난이도 빡셌겠네요!! 넘 고생하셨고 몇가지 부분만 확인 부탁드려요!

pr 메세지에 남긴 적용해야 할 개선사항들은 다음 스프린트에 해봅시다!

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/errorBoundary/AsyncBoundary.tsx
> +            <Suspense fallback={<Spinner />}>{children}</Suspense>
이렇게 되면, Suspense 가 전체 라우터를 감싸는 것 같은디 어느 하나 로딩 상태가 걸리면 전체 화면에 항상 스피너가 돌지는 않았나여? 😀

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/error/ErrorComponents.tsx
> +    window.location.reload();
😅 ㅋㅋㅋㅋㅋㅋㅋㅋ

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/error/ErrorComponents.tsx
> +  };
중복되는 것 같은디 훅으로 빼봐도 좋을 듯 싶네요!

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/error/ErrorComponents.tsx
> +      <S.RuntimeText>
마크업 계층구조도 반복되는 느낌이 드는데, HOC 와 같은 방식을 추후에 적용해보든건 어떨까여??

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/errorBoundary/ErrorBoundary.tsx
> +  // eslint-disable-next-line react/no-unused-class-component-methods
eslint config 파일에서 처리하는건 어떨까요??

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/errorBoundary/ErrorBoundary.tsx
> +    // eslint-disable-next-line react/destructuring-assignment
eslint config 파일에서 처리하는건 어떨까요??

2023-09-13 07:46 UTC, sh981013s commented on client/src/components/_common/errorBoundary/ServerErrorBoundary.tsx
> +    const status = /5\d{2}/;
regex 모아둔곳으로 빼는건 어떨까요??

2023-09-13 07:46 UTC, sh981013s commented on client/src/index.tsx
> +            alert(error.response.data.message);
alert 말고 다른 방식은 없을까요??!

2023-09-13 10:06 UTC, evencoding approved these changes
네이브 어려운 부분이었는데 정말 고생하셨어요!

부엉이가 이미 잘 달아주셔서 제 리뷰는 코맨트만 확인해주시면 될 것 같아요🤩

2023-09-13 10:06 UTC, evencoding commented on client/src/components/_common/errorBoundary/CriticalErrorBoundary.tsx
> +  componentDidCatch(_error: any, _errorInfo: ErrorInfo): void {}
매개변수명이 `_error`인 이유가 있을까요?

2023-09-13 10:06 UTC, evencoding commented on client/src/components/_common/errorBoundary/RuntimeErrorBoundary.tsx
> +  componentDidCatch(_error: any, _errorInfo: ErrorInfo): void {}
없어도 무방한 라인이라는 생각이 들어요🤩

2023-09-14 05:07 UTC, NaveOWO commented on client/src/components/_common/errorBoundary/AsyncBoundary.tsx
> +            <Suspense fallback={<Spinner />}>{children}</Suspense>
맞아요오..!!! 이 AsyncBoundary를 필요한 곳에 부분적으로 감싸줘야하는데 아직 완성이 되지 않아서 일단 app 전체를 감싸줬어요!

2023-09-14 05:07 UTC, NaveOWO commented on client/src/components/_common/error/ErrorComponents.tsx
> +    window.location.reload();
..ㅎㅎ 수정하겠습니다아

2023-09-14 05:07 UTC, NaveOWO commented on client/src/components/_common/error/ErrorComponents.tsx
> +  };
앗 어차피 저 reload부분이 리셋로직으로 대체될꺼라서 임시방편으로 그냥 뒀는데요..!! 훅이 필요할까요!?

2023-09-14 05:08 UTC, NaveOWO commented on client/src/components/_common/error/ErrorComponents.tsx
> +      <S.RuntimeText>
호호~ 좋은 생각이에요 고려해보겠습니다!!

2023-09-14 05:08 UTC, NaveOWO commented on client/src/components/_common/errorBoundary/ErrorBoundary.tsx
> +  // eslint-disable-next-line react/no-unused-class-component-methods
네엡 없앨께욧!

2023-09-14 05:09 UTC, NaveOWO commented on client/src/components/_common/errorBoundary/ErrorBoundary.tsx
> +    // eslint-disable-next-line react/destructuring-assignment
넵!!

2023-09-14 05:12 UTC, NaveOWO commented on client/src/components/_common/errorBoundary/ServerErrorBoundary.tsx
> +    const status = /5\d{2}/;
아핫 넵!!

2023-09-14 06:28 UTC, NaveOWO commented on client/src/index.tsx
> +            alert(error.response.data.message);
토스트로 바꿔볼께요~!!

2023-09-14 07:43 UTC, NaveOWO commented on client/src/index.tsx
> +            alert(error.response.data.message);
엉 이거 토스트로 변경하려구 했는데, 애초에 우리가 만들어둔 토스트 자체가 ToastProvider 안에서만 쓸 수 있는데 이 queryClient는 그 밖에서 선언되고있어서 이 계층에서 토스트 사용은 불가능하더라구요..!! 일단 alert로 두고 토스트를 사용할 방법을 고민해볼께요

2023-09-14 07:44 UTC, NaveOWO commented on client/src/components/_common/errorBoundary/CriticalErrorBoundary.tsx
> +  componentDidCatch(_error: any, _errorInfo: ErrorInfo): void {}
사용하지 않는 매개변수때문에 린트가 징징대서 _를 넣어줬어요..!! 추후에 에러 처리 로직이 들어가야하는 부분이라서요!!

2023-09-14 12:59 UTC, sh981013s commented on client/src/components/_common/error/ErrorComponents.tsx
> +  };
앗 그걸 몰랐네요! 일단 다음에 바로 수정하죠!

2023-09-14 13:00 UTC, sh981013s approved these changes
고생하셨으요~~

2023-09-14 13:01 UTC, merged