Feature/ck 199
woowacourse-teams/2023-co-kirikiri pull request #163
Opened 2023-09-21 06:54 UTC by NaveOWO

## 📌 작업 이슈 번호

CK-199

## ✨ 작업 내용
최적화 진행했습니당. 진행내용이랑 결과물은 노션에 있어서 링크로 첨부할께용
[최적화 진행](https://www.notion.so/co-kirikiri/e6003f2b5d884e3ea2d747fe57bc6211)

## 💬 리뷰어에게 남길 멘트

## 🚀 요구사항 분석

2023-09-21 11:08 UTC, sh981013s requested changes
넘나리 고생하셨어요...!! 리뷰 몇가지만 확인 부탁드려요~

2023-09-21 11:08 UTC, sh981013s commented on client/src/hooks/_common/useIntersectionObserver.ts
`useIntersection` 이라는 훅이 이미 있지 않나여..?

2023-09-21 11:08 UTC, sh981013s commented on client/src/components/roadmapDetailPage/roadmapNodeList/RoadmapNodeList.tsx
> +// import LazyImage from '@/components/_common/lazyImage/lazyImage';
필요한 주석인가여??

2023-09-21 11:08 UTC, sh981013s commented on client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
> +            <S.PodiumImage src={podiumImg} alt='Podium' loading='lazy' />
여기서는 만들어놓은 `lazy image` 컴포넌트를 사용하지 않은 이유가 뭐에요?

2023-09-21 11:08 UTC, sh981013s commented on client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
> +                    loading='lazy'
여기서는 만들어놓은 `lazy image` 컴포넌트를 사용하지 않은 이유가 뭐에요?

2023-09-22 04:15 UTC, evencoding approved these changes
네이브 고생하셨어요!

성능 최적화 뿐만 아니라, 웹 접근성까지 챙겨주셔서 너무 좋네요🤩

코맨트만 확인 부탁드릴게요!

2023-09-22 04:15 UTC, evencoding commented on client/src/styles/GlobalStyle.tsx
> +    font-display: optional;
굳굳굳!

2023-09-22 04:15 UTC, evencoding commented on client/src/styles/GlobalStyle.tsx
> +    scrollbar-width: none;
스크롤 바를 `display: none`으로 설정했는데, 어떤 부분에 문제가 있어서 width을 none으로 설정해주신 건가요?

2023-09-25 05:10 UTC, sh981013s approved these changes
vㅔ리 좋습니다~~!

2023-09-25 05:30 UTC, merged