[feat/CK-202] 태그 및 크리에이터로 로드맵을 검색할 떄 규칙을 수정한다
woowacourse-teams/2023-co-kirikiri pull request #167
Opened 2023-09-26 11:34 UTC by Ohjintaek

## 📌 작업 이슈 번호
[CK-202](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-202)

## ✨ 작업 내용
- 크리에이터명으로 로드맵 검색 시 기존에는 검색어가 완전히 일치하는 로드맵만 반환했지만, 크리에이터명이 검색어로 시작하는 모든 로드맵을 반환하도록 수정했습니다.
- 태그로 로드맵 검색 시 기존에는 검색어와 완전히 일치하는 태그를 가지는 로드맵만 반환했지만, 검색어로 시작하는 태그를 가진 모든 로드맵을 반환하도록 수정했습니다.

## 💬 리뷰어에게 남길 멘트
- 기존에 있던 테스트 외에 규칙변경으로 인해 추가된 케이스들에 대한 테스트를 작성해주었습니다.
- 통합 테스트에서 h2 database에 한글이 제대로 저장되지 않는 것 같아서 해결해보려고 했는데 (`?`로만 담기기 때문에 한글깨짐 현상과는 다른 것으로 예상) 실패해서 영어 케이스만 검증했습니다. 기존에도 발생했던 문제라서 실제 개발 서버에 merge됐을 때는 큰 오류가 없을 것으로 생각합니다.

## 🚀 요구사항 분석
- [x] 크리에이터명으로 로드맵 검색 시 검색어로 시작하는 크리에이터가 만든 모든 로드맵을 반환한다.
- [x] 태그로 로드맵 검색 시 검색어로 시작하는 태그를 가진 모든 로드맵을 반환한다.

2023-12-06 03:22 UTC, younghoondoodoom requested changes
안녕하세요 썬샷! 이걸 이제야 리뷰하네요.. 죄송합니다🥲
무한 스크롤 방식 때문에 로드맵 검색할때 모든 로드맵을 조회해야하네요ㅠㅠ 성능도 성능이고 로드맵이 많아진다면 npe가 발생할 수 있겠네요. 아무래도 다른 방식을 고민해봐야할 것 같습니다! 

이 정도로 복잡한 검색 요구사항이라면 `ElasticSearch`를 활용하는 것도 방법이 될 것 같습니다. 찾아보니 `ElasticSearch`의 `from`, `size`를 이용하면 무한스크롤을 쉽게 구현할 수 있을 것 같아요! 한번 회의 해봐도 좋을 것 같네요!

고생하셨습니다 썬샷🙇‍♂️

2023-12-06 03:22 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
>                          titleCond(searchRequest.getTitle()),
> 검색어와 완전히 일치하는 로드맵을 먼저 반환하도록 했습니다. 일치도가 같다면 최근에 만들어진 것을 먼저 반환합니다. 일치도는 임시로 로드맵의 크리에이터명/제목/태그의 길이로 판단하지만 너무 단순한 방법이라 나중에 개선이 필요할 것을 생각합니다.

검색어와 완전히 일치하는 로드맵만을 반환하고 있는 것 같습니다. 검색어가 포함되는 경우는 반환하지 않는건가요?

2023-12-06 03:22 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
> +    }
이 부분이 길이로 일치도를 판단하는거군요! 제 생각엔 이 부분이 `Repository` 레이어에 들어가는게 맞다고 생각합니다!

2023-12-06 03:22 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
> +                            .findAny().get().getName().getValue().length());
메소드 분리와 디미터 법칙을 통해 가독성을 높일 수 있을 것 같아요!

2023-12-06 03:22 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
> +                    .findAny().get().getName().getValue().length() -
`optional`에서 바로 get했을 때 npe가 발생할 여지가 있는것 같습니다!

2023-12-06 03:22 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
> +            final Roadmap lastRoadmap = findRoadmapById(scrollRequest.lastId());
마지막 로드맵은 파라미터로 받은 `roadmaps`에서 찾는게 더 나을 것 같아요!

2023-12-06 03:22 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
> +        }
이 부분 전체가 repository의 책임일 수도 있을 것 같아요!

2023-12-06 08:03 UTC, miseongk requested changes
안녕하세요 썬샷! 
리뷰가 넘 늦어서 죄송합니다..🙇‍♀️🙇‍♀️🙇‍♀️

복잡한 요구사항 구현하시느라 고생하셨어요!
검색 + 무한스크롤을 구현하려니 생각보다 복잡하네요. 
지금보다 좋은 방법이 없다면 
아직 ElasticSearch에 대해 잘 모르지만 두둠이 말씀하신 것 처럼 도입하는 것도 좋을 것 같네요!!

고생하셨어요 👍

2023-12-06 08:03 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +                .orderBy(sortCond(RoadmapOrderType.LATEST))
무한스크롤을 쿼리로 구현하지 못하는 이유가 일치도 순으로 정렬을 못하기 때문이죠?
만약 제목을 검색한다고 할 때, `orderBy` 절에서 제목의 길이 순서대로 정렬하는 것이 불가능한가요??
MySQL에 `Length`라는 함수가 있더라구요!

2023-12-07 00:55 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
>                          titleCond(searchRequest.getTitle()),
```
private BooleanExpression titleCond(final RoadmapSearchTitle title) {
        if (title == null) {
            return null;
        }
        return removeBlank(roadmap.title).containsIgnoreCase(title.value());
    }
```
`titleCond()` 메서드가 querydsl의 `containsIgnoreCase()`를 사용해서 포함하면 true를 반환합니다

2023-12-10 11:33 UTC, closed without merging