[feat/CK-222] Redis를 도입하고 Refresh Token을 Redis에 저장하도록 변경한다
woowacourse-teams/2023-co-kirikiri pull request #190
Opened 2023-11-01 01:19 UTC by miseongk

## 📌 작업 이슈 번호
[CK-222](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-222)

## ✨ 작업 내용
- 기존 데이터베이스에 저장하던 Refresh Token을 레디스에 저장하도록 변경했습니다.
- 기존 `RefreshToken`에서 `isRevoked` 필드를 제거했습니다.

## 💬 리뷰어에게 남길 멘트
- 리프레시 토큰 저장 시 암호화 하던 부분(`EncryptedToken`)을 제거하고 `RefreshToken` 내부에서 암호화하도록 변경했습니다. 암호화하는 클래스를 따로 만들기에는 서비스(`AuthService`, `MemberService`)에 의존성이 추가되고 테스트하기가 까다로워서 하지 않았습니다. 
    - `EncryptedToken`을 레디스의 Key 값으로 설정 못하는 이유는 레디스 Key 값 타입이 String 또는 Long이여야 하기 때문입니다.
- 레디스 테스트를 위해 **테스트컨테이너**를 사용했습니다. → 로컬에서 테스트 실행 시 ⭐️도커를 먼저 실행시킨 후 테스트를 실행⭐️해야 합니다!

## 🚀 요구사항 분석
- [x] Redis 도입
- [x] 리프레시 토큰을 Redis에 저장하도록 변경
- [ ] 만료기간이 지나면 자동으로 삭제해주도록 TTL 설정

2023-11-01 13:27 UTC, miseongk commented
RefreshToken의 Key 값을 MemberIdentifier로 하자는 의견을 내주셨는데, Key값은 중복되면 안되는 것 같습니다!
기존 방식대로 놔둘게요.

2023-11-02 04:44 UTC, Ohjintaek approved these changes
레디스 공부하고 적용까지 수고하셨습니다 밀리!!
저는 사소한 제안사항만 있어서 바로 Approve합니다. 그나저나 test container까지 사용해서 테스트를 돌리려니 텀퓨터가 힘들어하네요 😥

2023-11-02 04:44 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/helper/RedisRepositoryTest.java
> +public @interface RedisRepositoryTest {
커스텀 어노테이션까지 사용하셨네요 😮

2023-11-02 04:44 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/AuthServiceTest.java
>          //then
이 테스트는 삭제하는 게 낫지 않을까요? 위의 토큰이 존재하지 않을 때와 테스트 메서드와 body와 같을뿐더러 redis에서 만료되었는지 여부를 저장하지 않으니까요

2023-11-02 06:08 UTC, younghoondoodoom requested changes
고생 하셨습니다 밀리! 밀디스를 드디어 보네요.. redis로 잘 이전되었고, 테스트 코드 잘 동작하는 것도 확인했습니다. 
다만, CD 과정에서 테스트가 터질 것 같아서 걱정이네요.. 이 부분은 확인하고 머지를 해야할 것 같습니다! 
추가로, 저번에 `RedisTemplate`을 사용하는 방식으로 변경하신다고 인지했던 것 같은데 기존 방식을 그대로 유지한 이유가 무엇인지 궁금합니다!

2023-11-02 11:51 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/AuthService.java
> +                .orElseThrow(() -> new AuthenticationException("토큰이 만료 되었습니다."));
발급된 적 없는 토큰은 위에 `checkTokenValid`에서 검증돼서 토큰이 유효하지 않은 경우만 해당 로직을 타요!

2023-11-02 13:11 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/auth/RefreshToken.java
> +    private String memberIdentifier;
JPA와 연관있는 객체를 레디스 객체가 가지고 있는게 걸려서 사용하지 않았었어요.

2023-11-06 04:52 UTC, younghoondoodoom approved these changes
고생하셨습니다~! 처음 적용하는 레디스인데 깔끔하네요. 다음에는 같이 캐쉬도 해보시죠👍

2023-11-06 04:52 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/auth/RefreshTokenRepository.java
> +                .set(refreshToken, memberIdentifier, refreshTokenValidityInSeconds / 1000, TimeUnit.SECONDS);
옆에서 TimeUnit을 설정했는데 1000으로 나누는 이유가 뭔가요??

2023-11-06 04:52 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/auth/AuthService.java
> +                .orElseThrow(() -> new AuthenticationException("토큰이 만료 되었습니다."));
토큰이 이미 만료 되었을때 reissue 요청을 할거 같은데, 토큰이 만료가 되어서 이 부분에서 무조건 당연히 터지지 않나요?

2023-11-06 04:52 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/service/AuthServiceTest.java
>          final String rawAccessToken = "accessToken";
`rawRefreshToken` -> `refreshToken`으로 바꾼 김에 이것도 바꾸는 건 어떨까요?

2023-11-07 01:39 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/auth/RefreshTokenRepository.java
> +                .set(refreshToken, memberIdentifier, refreshTokenValidityInSeconds / 1000, TimeUnit.SECONDS);
환경변수에 설정된 값은 밀리초이고, TTL은 초단위여서 1000으로 나눴어요!

2023-11-07 01:43 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/auth/RefreshTokenRepository.java
> +                .set(refreshToken, memberIdentifier, refreshTokenValidityInSeconds / 1000, TimeUnit.SECONDS);
헷갈릴 여지가 있을거같아 변수로 빼겠습니다!

2023-11-07 01:48 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/auth/AuthService.java
> +                .orElseThrow(() -> new AuthenticationException("토큰이 만료 되었습니다."));
액세스 토큰이 만료되었을 때 리프레시 토큰으로 재발급 받는 것이기 때문에 리프레시 토큰도 만료되었다면 저기서 터지는게 맞을 것 같아요!

2023-11-07 02:58 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/auth/AuthService.java
> +                .orElseThrow(() -> new AuthenticationException("토큰이 만료 되었습니다."));
아 맞네요.. 잠깐 헷갈렸네요😅

2023-11-07 05:43 UTC, merged