[feat/CK-234] 폼 라이브러리를 부분 적용한다
woowacourse-teams/2023-co-kirikiri pull request #196
Opened 2023-11-06 13:06 UTC by jw-r

## 📌 작업 이슈 번호
CK-234

## ✨ 작업 내용
로그인 페이지, 회원가입 페이지에 폼 라이브러리 적용

## 💬 리뷰어에게 남길 멘트
[react-lightweight-form npm](https://www.npmjs.com/package/react-lightweight-form)
잘 부탁드립니다

2023-11-11 08:42 UTC, NaveOWO requested changes
리액트 훅 폼 적용한 것 같이 흠잡을데가 없네요...ㄷ ㄷ 대단하고 배아파요....
차차 다른 부분도 적용했으면 좋겟어요!! 이거가지고 하고싶은게 많거든요ㅋ ㅋ
우디 멋진 폼 만드느라 수고많았어요!!!

2023-11-11 08:42 UTC, NaveOWO commented on client/src/components/signUpPage/signUpForm/SignUpForm.tsx
> +              placeholder='아이디'
이런 부분들 상수처리하는거 어떤가요~?

2023-12-09 08:40 UTC, NaveOWO approved these changes

2023-12-19 09:13 UTC, sh981013s approved these changes
고생하셨어요!! 👍👍

2023-12-19 09:14 UTC, merged