[feat] 회원가입 API를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #2
Opened 2023-07-13 06:36 UTC by younghoondoodoom

## 📌 작업 이슈 번호
[CK-19](https://co-kirikiri.atlassian.net/browse/CK-19)

## ✨ 작업 내용
- 회원 정보에 각 사항의 조건에 따라 검증
- 비밀번호 인코딩
- API 문서화

## 💬 리뷰어에게 남길 멘트
- EncryptedPassword라는 도메인에서 비밀번호 인코딩을 진행한 이유는 비밀번호 인코딩은 비즈니스 로직이라고 생각했습니다. 그리고 인코딩 부분은 변경사항이 많이 없는 부분 같아서 domain에 있어도 어색하지 않다고 생각했는데 여러분의 생각이 궁금합니다.
- service에서 회원가입 정보를 받을 때, controller와 관계를 끊기위해 dto를 사용했는데(JoinMemberDto), 조금 마음에 안드네요. 이 부분도 확인해주세요!

## 🚀 요구사항 분석

### 회원가입 기능

- [x] 회원 정보를 입력 받는다.
    - [x] 아이디 설정
        - [x] 필수 설정
        - [x] 영어 소문자, 숫자 가능
        - [x] 최소 4, 최대 20
        - [x] 중복 불가능
    - [x] 비밀번호 설정
        - [x] 필수 설정
        - [x] 영어 소문자, 숫자, 특수문자 사용 가능
        - [x] 사용 가능한 특수문자 : `!,@,#,$,%,^,&,*,(,),~`
        - [x] 영어 소문자, 숫자는 필수
        - [x] 최소 8, 최대 15
    - [x] 닉네임 설정
        - [x] 필수 설정
        - [x] 최소 2, 최대 8
        - [x] 중복 불가능
    - [x] 성별 설정
        - [x] 필수 설정
        - [x] 남/여
    - [x] 생년월일 설정
        - [x] 필수 설정
        - [x] yyMMdd 형식
    - [x] 휴대폰 번호 설정
        - [x] 필수 설정
        - [x] xxx-xxxx-xxx 형식으로 받음

- [x] 비밀번호를 인코딩한다.
    - [x] 암호화 알고리즘은 SHA-256 암호화 + 무작위 문자열(salt)를 사용한다

2023-07-13 10:33 UTC, Cl8D requested changes
코드 작업량이 어마어마하시네요 👍
달다 보니 리뷰가 엄청 많아졌는데, 천천히 보시고 반영할 부분 반영해 주시면 감사드리겠습니다!
고생하셨어요 😊

2023-07-13 10:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
> +    private static MemberProfile memberProfile;
private로 선언된 상수가 아닌 변수가 static이어야 할 이유가 있을까요? 🤔

2023-07-13 10:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
> +        assertThat(OptionalMemberProfile).isNotEmpty();
findBy~로 찾은 메서드의 결과라면 테스트에서 해당 결과값이 원하는 객체로 나왔는지도 테스트를 하는 게 좋을 것 같아요! 🥲
(MemberRepositoryTest도 마찬가지입니다!... 단순히 비어있는지보다 원하는 값이 나왔는지 검증하는 게 중요하니까요!)

2023-07-13 10:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/JoinMemberDto.java
> +public record JoinMemberDto(
> service에서 회원가입 정보를 받을 때, controller와 관계를 끊기위해 dto를 사용했는데(JoinMemberDto), 조금 마음에 안드네요. 이 부분도 확인해주세요!

저는 완전 찬성입니다! 이런 식으로 연관관계를 끊어줘야 한다고 생각해요.

2023-07-13 10:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/member/MemberServiceTest.java
> +        //then
then절에 코드가 없어요...! 😶

2023-07-13 10:47 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
> +        final String message = Objects.requireNonNull(exception.getFieldError()).getDefaultMessage();
저희가 정한 `ErrorResponse`에 필드가 하나만 처리하긴 했는데, List<ErrorResponse>로 보내는게 나을까요?

2023-07-13 10:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/request/JoinMemberRequest.java
> +public record JoinMemberRequest(
member 패키지 하위에 있어서 Join이 먼저 나오는게 가독성이 좋다고 생각했어요! 만약 member -> dto 패키지를 들어갔을때 앞에 있는 글자만 보고 빠르게 찾기 좋지않을까 했는데 어떻게 생각하시나요?

2023-07-13 10:58 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/member/JoinMemberMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
네?

2023-07-13 11:24 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/EncryptedPassword.java
> +    }
저도 java 라이브러리를 활용해서 domain에 있는게 괜찮겠다고 생각했어요. vo가 로직을 가지는게 불편하긴 하지만, 저는 `er, or`이 붙는 객체가 만들어지는게 객체지향적이지 않은 설계가 되어있다는 포인트라고 느껴져서 분리하는걸 선호하지는 않는거 같아요! 
저도 다른분들 의견이 궁금하네요!

2023-07-13 11:44 UTC, miseongk reviewed
두둠 너무 고생하셨어요! 
이미 져니가 많은 부분 리뷰 남겨주셔서 저는 간단하게 남겨봤습니다!

2023-07-13 11:44 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/member/MemberService.java
> +    public void join(final JoinMemberRequest joinMemberRequest) {
혹시 인자로 request를 받을 때 변수명을 request로 하는 것은 어떻게 생각하시나요? 
혹시라도 JoinMemberRequest가 변경될 경우에 클래스만 변경하는 것이 아니라 변수명까지 모두 변경해야 해서 request로 통일하는 것이 더 좋다고 생각해요!

2023-07-13 11:44 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(BadRequestException.class)
@ExceptionHandler에 클래스를 넣지 않아도 돼요!
그러면 복붙하기에도 더 쉬워서(인자 타입만 변경하면 되니까 실수할 일도 줄어들어요), 저는 안넣는 것을 선호하는데 어떻게 생각하시나요?

2023-07-13 11:44 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/Identifier.java
> +            throw new AuthenticationException("제약 조건에 맞지 않는 아이디입니다.");
저도 두 케이스 분리하는 것이 더 명확할 것 같아요!

2023-07-13 11:44 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/IdentifierTest.java
> +        //then
저는 given과 when 절이 없는 경우 expect라고 하는데 이건 크게 중요하지 않을것 같네용

2023-07-13 11:44 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/service/member/MemberServiceTest.java
> +        //then
🫢

2023-07-13 11:44 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/MemberIntegrationTest.java
> +class MemberIntegrationTest extends IntegrationTest {
저희 통합 테스트는 변수명, 메서드명 모두 한글로 작성하는 것이 컨벤션 아니였나요?!

2023-07-13 16:18 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/EncryptedPassword.java
> +    }
저는 암호화같은 정책은 도메인에서 분리하는 것이 좋겠다는 생각이 들어요!
저희 서비스는 그럴 확률이 거의 없겠지만, 일반적으로 본다면 정책은 언제든지 바뀔수 있다보니 분리하는 것이 낫지 않을까 생각이 드네요!

2023-07-13 16:57 UTC, Ohjintaek reviewed
정말 수고하셨어요 두둠!!👍👍
리뷰를 다는 것도 처음이고 경험도 적어서 리뷰하면서도 내가 잘못 생각한 건 아닐까? 하는 생각들이 들 때가 있네요
그래도 한 팀이니 끝까지 같이 화이팅해요 ㅎㅎㅎ

2023-07-13 16:57 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/MemberControllerTest.java
> +        mockMvc.perform(post("/api/member/join")
첫 테스트만 `API_PREFIX + "/member"`` 형식이라 나머지 테스트랑이랑 달라요

2023-07-13 16:57 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/Identifier.java
> +            throw new AuthenticationException("제약 조건에 맞지 않는 아이디입니다.");
저도 두 케이스에서 서로 다른 메시지를 전달해주면 더 좋을 거 같네요. 추가적으로 테스트를 보다 보니 제약 조건과 관련된 exception은 저도 bad request를 반환하는 것이 더 나을 것 같다는 생각이 들어요

2023-07-13 16:57 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/EncryptedPasswordTest.java
> +    }
이 부분에 대해 올려주신 블로그 글을 봤을 때 레인보우 테이블로 인해 해킹을 방지하기 위해 salting을 한다고 했는데 그렇다면 서로 다른 사용자가 같은 패스워드를 입력해도 다르게 암호화되어 저장된다고 이해했는데 맞을까요?

2023-07-13 16:57 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/PasswordTest.java
> +}
비밀번호가 숫자나 영어 소문자만 있는 경우도 테스트하면 좀 더 정규식이 제대로 구현됐는지 알 수 있을 거 같아요!!

2023-07-13 16:57 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
> +    @BeforeAll
@BeforeAll로 테스트가 실행되기 전에 한 번만 수행되도록 하는 것이 아니라 createMember와 같은 메서드로 분리하는 건 어떨까요?
MemberProfileRepositoryTest에서 등록이나 조회뿐만 아니라 추후에 수정이나 삭제같은 기능까지 테스트하면 다른 테스트 메서드들이 영향을 받을 수도 있을 거란 생각이 들었어요.

2023-07-14 01:44 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/EncryptedPasswordTest.java
> +    }
@Ohjintaek 네 맞습니다! 같은 패스워드를 입력해도 임의로 생성하는 Salt가 다르기 때문에 아마 다르게 저장될겁니다

2023-07-14 02:10 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
> +    private static MemberProfile memberProfile;
@BeforeAll이 붙은 메소드는 static 메소드여서..🥲

2023-07-14 02:14 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/service/member/MemberServiceTest.java
> +        //then
아무일도 일어나지 않는게 성공이라는걸 표현한거긴한데 assertDoesNotThrow로 명시적으로 할게요..

2023-07-14 02:28 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
> +        assertThat(OptionalMemberProfile).isNotEmpty();
까먹었네요..🥲

2023-07-14 03:09 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
> +    @BeforeAll
beforeall로 하는건 변동이 없는 객체입니다! final 필드로 쓰는것보다 메소드 내에서 생성하는것 같아서 그렇게 했는데 어떻게 생각하시나요??

2023-07-14 04:24 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/EncryptedPasswordTest.java
> +    }
@Cl8D 인터페이스로 해도 구현체 자체를 테스트해야하는건데 어렵지 않나요..?

2023-07-14 04:33 UTC, Cl8D approved these changes
고생하셨어요! 😊

2023-07-14 04:40 UTC, miseongk approved these changes
고생하셨어요~! 저는  approve 할게요!

2023-07-14 04:45 UTC, Ohjintaek approved these changes
수고하셨습니다~~~!!

2023-07-14 04:49 UTC, merged