[feat/CK-241] 회원, 인증/인가, 공통 부분 의존성 리펙토링을 한다
woowacourse-teams/2023-co-kirikiri pull request #205
Opened 2023-12-14 09:46 UTC by younghoondoodoom

## 📌 작업 이슈 번호
[CK-241](https://co-kirikiri.atlassian.net/browse/CK-241?atlOrigin=eyJpIjoiOTkxMDc1Nzc5YTI1NDZlOGFhMThhMjc3MGQzNDMzOTUiLCJwIjoiaiJ9)

## ✨ 작업 내용
회원(member), 인증/인가(auth), 공통(commcon) 부분의 의존성 리펙토링을 진행 했습니다. 다른 분께서 담당하는 부분은 최대한 건드리지 않고 진행했습니다. 
주요 작업 내용으로는 의존관계를 끊기 위해서 새로운 dto를 만들기, oauth 회원가입 로직 분리가 있습니다. 
새로운 dto는 member.service.dto.response 패키지 하위에 위치한 클래스들입니다. 그리고 oauth 회원가입 같은 경우에는 기존에 `memberService`에서 토큰까지 만들어서 반환해주고 있었습니다. 그렇게 되면 `member`와 `auth`가 양방향 의존관계가 생기는 문제가 발생합니다. 이를 해결하기 위해서 `memberService`에서는 회원 저장만 진행하도록 하고 토큰 생성은 `authService`가 하도록 로직을 수정했습니다.

## 💬 리뷰어에게 남길 멘트
다음과 같이 의존성이 흐르게 했습니다. `common -> auth`, `common -> member`, `auth -> member`
그리고 나머지 패키지들도 기본적으로는 `common` 패키지에 의존하게됩니다. 

그리고 지금 현재 `common`은 다른 패키지에 의존하는 클래스가 몇개 있습니다. 해당 도메인 담당해주시는 분이 변경 해주실 것 같아서 그냥 뒀습니다!

## 🚀 요구사항 분석
[x] `member`, 'auth' 관련된 로직을 패키지로 분리한다.
[x] `member` 패키지는 `common`에 의존한다.
[x] `auth` 패키지는 `common`, `auth`에 의존한다.
[x] `common` 패키지는 어디에도 의존하지 않는다.

2023-12-22 04:58 UTC, Ohjintaek requested changes
수고하셨습니다!! 역시 두둠, 깔끔한데요?
Member에서 관리하는 DTO 중 몇 가지만 GoalRoom으로 넘기는 게 어떤지에 대한 코멘트와 추가적으로 테스트코드에서 MemberControllerTest들도 `Member` 패키지로 넘기는 것에 대해서 의견을 제시해봅니다.

2023-12-22 04:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/member/service/MemberService.java
> +    public Member oauthJoin(final OauthMemberJoinDto oauthMemberJoinDto) {
Token을 관리하는 역할을 auth로 넘겨서 member에서 auth에 대한 의존성이 사라졌네요 👍👍

2023-12-22 04:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/member/service/MemberService.java
> +    private MemberInformationDto makeMemberInformationDto(final Member member) {
꼼꼼하시네요

2023-12-22 04:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/member/service/dto/response/MemberGoalRoomResponse.java
> +public record MemberGoalRoomResponse(
`MemberGoalRoomResponse`나 `MemberGoalRoomForListResponse` 등이 네이밍에 **Member**가 들어가 있긴 하지만 **GoalRoom**과 관련되어 있는 Dto이고 반환도 `GoalRoomController`에서 하고 있기 때문에 `Member` 패키지에서 관리하는 것보다 `GoalRoom` 패키지에서 관리하는 편이 낫다고 생각합니다. 그에 따라 의존성 때문에 추가로 생성된 Dto들도 없어지는 편이 좋을 거 같구요(`MemberCheckFeedResponse` 같은 객체들)

2023-12-26 10:55 UTC, miseongk requested changes
의존성 분리하시느라 고생많으셨어요 두둠!
크게 변경될 부분이 보이지 않네요. 👍👍
몇가지 코멘트 남겼으니 확인해주세요!
그리고 현재 이전 커밋부터 올라와있는데 이 부분 확인부탁드려요~!
그럼 좋은 연말 보내세요 🎄

2023-12-26 10:55 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/auth/service/dto/OauthRedirectResponse.java
> +package co.kirikiri.auth.service.dto;
이 DTO는 `auth.service.dto.response` 패키지로 들어가야겠네요!

2023-12-26 10:55 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/common/exception/DomainException.java
도메인 예외와 서비스 예외를 exception 패키지 내에서도 패키지로 구분하면 어떨까요?
현재는 무슨 예외가 도메인 예외인지 서비스 예외인지 알지만, 나중에 헷갈려서 혼동하여 사용할 위험을 줄일 수 있을 것 같아요!

2023-12-26 10:55 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/member/service/MemberService.java
> +    public Member oauthJoin(final OauthMemberJoinDto oauthMemberJoinDto) {
토큰 생성 역할을 auth로 옮기니 역할 분리도 잘돼서 깔끔하고 좋네요 👍

2023-12-26 10:55 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/member/service/dto/response/MemberGoalRoomResponse.java
> +public record MemberGoalRoomResponse(
저도 동의합니다! 골룸 패키지에서 사용하는 DTO 들이라 골룸 패키지에 놔두는게 좋을 것 같아요.
실제로 제가 작업하면서 골룸 패키지로 옮기기도 했구요..!

2023-12-26 10:55 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/controller/helper/ControllerTestHelper.java
> +    private MemberIdentifierArgumentResolverImpl memberIdentifierArgumentResolver;
직접 구현체를 선언하지 않고 인터페이스로 해도 동작하는데 인터페이스로 놔두는게 어떨까요??

2023-12-27 23:02 UTC, closed without merging

2024-01-06 12:52 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/member/service/dto/response/MemberGoalRoomResponse.java
> +public record MemberGoalRoomResponse(
동의합니다! 지금보니까 왜 굳이 바꿨는지 모르겠네요.. 밀리꺼랑 일치하도록 수정할게요!