[feat/CK-240] 골룸 관련 부분 의존성 리팩토링을 한다
woowacourse-teams/2023-co-kirikiri pull request #207
Opened 2023-12-21 14:57 UTC by miseongk

## 📌 작업 이슈 번호
[CK-240](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-240)

## ✨ 작업 내용
- 골룸 관련된 부분 의존성 리팩토링을 진행했습니다. 
- 패키지를 생명주기에 따라 goalroom, todo, checkfeed로 나눴습니다. 
    - 패키지 내의 객체는 객체를 직접참조 했고, 패키지 외의 객체는 id로 간접참조 했습니다.
    - `goalroom` -> `roadmap`, `member`, `common`
    - `todo` -> `goalroom`, `member`, `common`
    - `checkfeed` -> `goalroom`, `member`, `common`
<img width="1170" alt="스크린샷 2023-12-21 오후 11 47 07" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/39994337/52b3ac35-1039-4125-be91-def4331bd360">

- 패키지를 분리하면서 컨트롤러와 서비스도 각각 분리했습니다.

## 💬 리뷰어에게 남길 멘트
- 너무 많은 수정이 있어서 혹시나 놓친 부분이 있을 수 있습니다..! 😭
- 현재 로드맵 관련된 테스트 몇개가 실패합니다. 로드맵과 골룸이 의존하고 있는 부분이 있는데, 이 부분을 로드맵 의존성 분리해주실 때 분명 변경될 것 같아서 처리하기가 힘들더라구요. 그래서 일단 실패하는대로 놔뒀습니다! 추후에 머지할 때 수정하겠습니다.
    - 로드맵 정렬 할 때 골룸 개수와 참여자 수로 정렬하는 조건이 있는데 기존에는 쿼리에서 직접 골룸에 접근해서 문제 없었는데, 골룸과 로드맵 의존을 끊어서 직접 접근할 수 없게 되었습니다. 일단 로드맵 부분을 건드리기 어려워서 주석처리 해두었습니다. 
    - 로드맵 쪽에 수정된 코드는 임시로 해둔거라 무시하셔도 좋아요..!

## 🚀 요구사항 분석

2023-12-25 13:28 UTC, Ohjintaek requested changes
수고하셨어요 밀리~!!
요즘 코드를 잘 안 보다보니 집중력이 떨어져서 띄엄띄엄 보느라 너무 오래 걸렸습니다...
그냥 보는 것만 해도 이렇게 오래 걸렸는데 의존성 분리하고 테스트 코드까지 많이 건드리신 것 같아서 엄청 고생하셨을 것 같네요 😵
`GoalRoom`만을 분리하는 게 아니라 내부적으로 패키지를 더 나눈 점이 인상적이었습니다. 코멘트를 단 시간대가 자유분방해서 작성한 코멘트 중에서 맥락이 이상한 점이 있지 않을까 우려되는데 제 의견이 궁금하신 부분은 편하게 다시 질문주세요!!

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomReadService.java
> +                goalRoom, currentGoalRoomRoadmapNode);
여기서 `currentGoalRoomRoadmapNode`가 있는 경우에만 `DashBoardCheckFeedService`의 메서드를 호출하는 건 어떤가요? Optional을 파라미터로 넘기는 것은 그다지 추천하지 않기도 하고, 골룸의 상태나 현재 노드가 진행 중인지 여부에 따른 `CheckFeed`의 호출 방식 여부는 `CheckFeed`보다 상위에서 결정되는 게 덜 어색한 거 같아서요.

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/GoalRoomCheckFeedService.java
> +    public String createCheckFeed(final String identifier, final Long goalRoomId,
`GoalRoom`이라는 큰 도메인 내부에서도 GoalRoom, CheckFeed, GoalRoomTodo로 패키지를 나누어 의존성이 한 방향으로 흐르게 한 점이 인상적이에요 👍

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/GoalRoomCheckFeedService.java
> +    private List<CheckFeed> findCheckFeedsByGoalRoomRoadmapNode(final GoalRoom goalRoom,
패키지를 나누니 필연적으로 중복된 코드도 늘어날 수 밖에 없겠네요

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/common/service/dto/FileInformation.java
> +    public static FileInformation from(final MultipartFile multipartFile) {
GoalRoomMapper보다 여기에 있는 게 훨씬 잘 어울리는데요 👍

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
> -    private void checkTotalSize(final int totalSize) {
도메인 예외가 아니어서 Service 레이어로 빼신 건가요? 꼼꼼하시네요 😮

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/persistence/GoalRoomMemberQueryRepositoryImpl.java
>                  .fetchJoin()
fetchJoin()이 중복됐어요

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomCreateService.java
> +    private void validateGoalRoomRoadmapNodeSize(final GoalRoom goalRoom, final GoalRoomRoadmapNodes goalRoomRoadmapNodes,
위의 public 메서드에서 등장한 순서대로 위치하도록 해 주면 좋을 거 같아요. `join` 메서드 바로 위로요!

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/mapper/GoalRoomMapper.java
> +    public static GoalRoomRoadmapNodes convertToGoalRoomRoadmapNodes(
요 메서드는 사용하는 서비스 계층에 두는 건 어떤가요? Mapper의 다른 메서드들은 `DTO`를 조립하는 역할인데 얘는 도메인을 만들어내서 서비스에 있는 게 좀 더 적절하다는 생각이 들어서요

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomReadService.java
> +    public GoalRoomCertifiedResponse findGoalRoom(final String identifier, final Long goalRoomId) {
GoalRoom에서 객체 참조로 가지고 있던 것을 끊어주면서 이렇게 DB 접근이 늘어나게 된 거 같습니다. 기존 방식과 현재 방식을 비교했을 때 왜 지금 방식을 선택했는지 의견이 궁금해요. 전 아직 뭐가 더 좋을지 기준을 잘 못 세워서...

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/todo/domain/exception/GoalRoomToDoException.java
> +public class GoalRoomToDoException extends DomainException {
👍

2023-12-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/todo/persistence/GoalRoomToDoCheckRepository.java
> +    Optional<GoalRoomToDoCheck> findByGoalRoomTodoAndGoalRoomMemberId(
요부분 `Todo`를 `ToDo`로 하면 JPA가 매칭시켜주던데 따로 JPQL로 한 이유가 있을까요? 추가적으로 아래에 Delete 쿼리도 `ToDoId` 대신에 `GoalRoomToDoId`로 바꿔도 되더라구요

2024-01-01 07:17 UTC, younghoondoodoom requested changes
안녕하세요 밀리! 작년까지 리뷰를 끝냈어야했는데 새해 들어서야 끝내네요.. 죄송합니다.
골룸 관련된 의존성 분리 정말 쉽지 않았겠네요.. 로드맵이랑도 엮인 부분이 많아서 더 힘드셨을거 같아요. 고생하셨습니다! 

저는 의존성 분리의 목적이 조회를 편하게 위한 것이 아니라, 유지보수하기 좋은 형태로 바꾸는 것 같습니다. 어떤 클래스가 요구사항에 의해 변경 되었을때, 최대한 다른 클래스들에 최소한의 영향을 주는것이 좋다고 생각해요! 그래서 도메인 모델이 꼭 필요한 의존성만 가지고 있고, 불필요한 의존성은 제거하는게 맞다고 생각합니다.
양방향 의존성을 가지게 되면 두 클래스가 서로의 변경에 크게 영향을 받게 되어서 유지보수성이 떨어지게 됩니다. 조회 시에 불편하더라도 이러한 의존성은 꼭 끊는게 좋을 것 같아요!

추가적으로 제 생각 남겼으니까 참고 부탁드립니다. 나중에 의존성 관련해서 얘기 해봐도 좋을 것 같네요! 취업 준비 파이팅입니다🙌

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
>      private final GoalRoomMembers goalRoomMembers = new GoalRoomMembers();
`goalRoom`과 `goalRoomMember`가 양방향 연관관계를 가지고있네요. `goalRoom`과 `goalRoomMember`의 생명주기가 같다고 하기에는 애매한 것 같아요. `goalRoomMember`의 어떤 로직이 변경 되었을때 `goalRoom`도 변경될 가능성이 있게되면 유지보수성이 떨어질 것 같습니다! 
그리고 제 생각에는 `goalRoomMember`가 `goalRoom`을 직접적으로 알 필요도 없다고 생각합니다. 단순히 멤버가 추가 되는 로직 밖에 없어서요! `goalRoom`이 `goalRoomMember`를 모르게 하고, `goalRoomMember`가 `goalRoom`를 가지게 하면 어떨까요? 

`goalRoomPendingMembers`도 같은 의견입니다!

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
>      private final GoalRoomRoadmapNodes goalRoomRoadmapNodes = new GoalRoomRoadmapNodes();
`goalRoomMember`과 반대로 `goalRoomRoadmapNodes`는 직접 참조하는게 맞다고 생각이 드네요. 비즈니스 로직 상`goalRoom`이 생성되는 시점에 `goalRoomRoadmapNode`가 현재 `roadmapNode`를 참조하는 역할이니까요! 이 둘은 완전히 생명주기가 일치한다고 할 수 있네요👍

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomCreateService.java
> +        goalRoom.addAllGoalRoomRoadmapNodes(goalRoomRoadmapNodes);
지금 보니까 굉장히 어색한데 `goalRoomRoadmapNodes`를 왜 따로 추가 해주고있죠..? `goalRoom`이랑 `goalRoomRoadmapNodes`의 생명주기가 같아서 생성자에 넣어서 같이 만들어주면 될 것 같아요.

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomCreateService.java
> +        }
이 부분도 지금 보니까 굉장히 어색하네요. `goalRoom`의 `goalRoomRoadmapNode`가 비어있는 상태인데 굳이 `goalRoomRoadmapNodes`의 사이즈랑 합쳐서 비교하고 있네요.

그냥 `goalRoom` 생성할때 `goalRoomRoadmapNodes`를 넣어서 생성될 `goalRoom`의 `goalRoomRoadmapNodes` 사이즈랑 `roadmapContent`의 nodeSize랑 같은지 확인하면 될 것 같아요.

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/GoalRoomCheckFeedService.java
> +        updateAccomplishmentRate(goalRoom, goalRoomMember, currentMemberCheckCount);
인증피드 등록하는 로직에서는 등록에 대한 관심사만 존재하고, 달성률 계산하는 로직은 개념적으로 분리하는건 어떨까요? 달성률 계산하는 로직을 확인하고 싶을때 인증피드 등록에 들어와서 확인해야한다는게 직관적이지 않은 것 같아요.

인증피드 등록 이벤트를 발행하고, 다른 곳에서 이벤트 리스너를 통해서 달성률을 계산하는건 어떨까요?

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
>      }
리더가 업데이트 되는 로직은 골룸 생성이랑 무관할 수도 있을 것 같아요. 골룸이 생성될때 이벤트를 발행해서 리더인 `GoalRoomPendingMember`를 생성하는건 어떨까요? 이렇게 하면 `goalRoom`이랑 `GoalRoomPendingMember`의 관심사를 분리해서 유지보수성을 높힐 수 있을 것 같습니다!

2024-01-01 07:17 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomCreateService.java
> +        }
이 부분도 이벤트를 통해서 분리할 수 있을 것 같아요. leave에서는 회원이 방에서 나가는 것에 대한 책임만 가지고, 빈 골룸일 경우 골룸을 삭제하는건 다른 관심사일 수도 있겠다는 생각이 들어요!

2024-01-05 16:53 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
> -    private void checkTotalSize(final int totalSize) {
이 부분은 기존에는 `RoadmapContent`를 직접 참조하고 있어서 예외 처리를 도메인 내에서 할 수 있었는데, `RoamapContent`를 간접 참조로 바꾸면서 repository를 접근해야해서 서비스로 뺐어요!

2024-01-05 16:56 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/persistence/GoalRoomMemberQueryRepositoryImpl.java
>                  .fetchJoin()
헉 감사합니다 😅

2024-01-05 17:21 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/todo/persistence/GoalRoomToDoCheckRepository.java
> +    Optional<GoalRoomToDoCheck> findByGoalRoomTodoAndGoalRoomMemberId(
오 그렇군요!! 몰랐어요..ㅎㅎ 수정했습니다!

2024-01-10 07:28 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomCreateService.java
> +        }
그러게요..!
'`goalRoomRoadmapNodes` 사이즈랑 `roadmapContent`의 `nodeSize`랑 같은지 확인'하는 부분은 `GoalRoom`이 `RoadmapContent`를 간접참조하고 있어서 `GoalRoom` 내부에서 검증할 수 없어 서비스 레이어에서 검증해주도록 했어요!

2024-01-14 12:16 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
>      }
좋아요 👍 
`goalRoom`에서 `goalRoomPendingMember` 의존성을 제거해주니 자연스럽게 `updateLeader` 로직을 수행할 수 없게되었어요! 애초에 서로 관심사가 다르다는 걸 나타내는 것 같네요.
리더 업데이트 로직은 이벤트를 발행해서 해결하겠습니다!

2024-01-14 13:37 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomCreateService.java
> +        }
좋아요. 반영하겠습니다!

2024-01-14 14:34 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/GoalRoomCheckFeedService.java
> +        updateAccomplishmentRate(goalRoom, goalRoomMember, currentMemberCheckCount);
확실히 그런 것 같네요! 달성률 계산 로직을 따로 분리하면 나중에 확인하기도 훨씬 좋겠네요! 👍
반영하겠습니다!

2024-01-14 15:03 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomReadService.java
> +    public GoalRoomCertifiedResponse findGoalRoom(final String identifier, final Long goalRoomId) {
저도 아직 확 와닿지는 않는 것 같아요.
리팩터링하면서 레포지토리 접근하는 코드가 확 늘어나서 더욱 헷갈리더라구요. 
그래서 저는 아래 두둠이 말씀하신 것처럼 유지보수성 측면에서 객체 참조를 끊어주는 것이 좋다는 것으로 일단은 생각하고 있어요! 객체를 직접 가지고 있으면 객체를 활용해서 코드를 작성하게 될 텐데 그렇다면 변경에 대해 같이 변경 지점이 발생할 수 있어서 끊어주는게 훨씬 유지보수하기 좋다고 생각했어요. 
더 나아가서 뭐가 더 좋은지는 조금 더 고민하고 공부해봐야 할 것 같아요.

2024-01-14 15:19 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/domain/GoalRoom.java
>      private final GoalRoomMembers goalRoomMembers = new GoalRoomMembers();
`goalRoom`과 `goalRoomMember`의 생명주기가 확실히 다른 것 같네요! 멤버는 골룸을 들어갔다가 나갈 수 있기 때문에 골룸의 생성, 삭제 시점과 멤버들의 생성, 삭제 시점이 다르네요! 
하지만 골룸과 멤버들은 밀접하게 연관되어 있어서 양방향 연관관계를 놔두었었어요! 골룸에 참여하는 로직을 생각해보면 제약사항이 골룸과 연관된 것이 많아요. (골룸이 진행중이면 안된다거나 골룸에 참여 인원이 꽉 찼다거나) 또 조회할 때도 골룸의 멤버들의 수를 구하거나, 리더를 찾는 작업을 거의 모두 해야하더라구요!

그런데 두둠이 말씀하신 것처럼 의존성 분리를 하는 목적은 조회보다는 유지보수성을 높이기 위함이라고 생각해서 양방향 연관관계를 제거해주었어요! 그렇게 하니 검증하는 부분이 서비스 계층으로 모두 옮겨진 것과, 도메인이 비교적 간단해진 점이 조금 아쉽네요..! 
하지만 기존에 골룸 멤버의 로직이 변경되었을 때 골룸에 영향을 주는 코드들이 많았는데, 이를 제거한 것이 가장 큰 장점인 것 같네요! 그만큼 관심사 분리도 잘 된 것 같아요.

2024-01-14 15:37 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomReadService.java
> +                goalRoom, currentGoalRoomRoadmapNode);
`currentGoalRoomRoadmapNode`가 없는 경우에도 골룸의 상태에 따라 인증피드를 조회할 수 있어서, `currentGoalRoomRoadmapNode`가 있는 경우에만 메서드를 호출할 수가 없더라구요! 
`GoalRoomReadService`에서 분기문으로 처리하는 것보다 `DashBoardCheckFeedService`의 메서드에서 해당하는 인증피드를 상태에 따라 조회하는 것도 괜찮지 않나요?!

Optional을 파라미터로 넘기는게 좀 걸려서, 
```
final Optional<GoalRoomRoadmapNode> currentGoalRoomRoadmapNode = findCurrentGoalRoomNode(goalRoom);
``` 
이 부분을 차라리 `DashBoardCheckFeedService`의 메서드로 옮기는 것도 좋을 것 같은데 어떻게 생각하시나요?

2024-01-20 07:28 UTC, younghoondoodoom requested changes
안녕하세요 밀리! 롱타임노씨네요.. 골룸 의존성 분리하느라 고생하셨습니다!
이벤트를 발행할때 어떤 것을 이벤트로 발행해야하는지에 대해서 의견 남겼으니 참고 부탁드립니다.

고생하셨습니다👍

2024-01-20 07:28 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/AccomplishmentRateUpdateEventListener.java
이벤트랑 이벤트 리스너 자체에 무엇을 할지 들어나있는거 같아요! 이벤트는 단순히 인증피드 등록을 한다는 것을 발행하고  그것을 Listen 하는 쪽에서 구체적인 행위를 하면 좋을 것 같네요.

https://techblog.woowahan.com/7835/

위 링크의 `무엇을 이벤트로 발행할 것인가?` 부분 읽어보시면 좋을 것 같아요!

2024-01-20 07:28 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/event/AccomplishmentRateUpdateEvent.java
> +        int pastCheckCount
`pastCheckCount`을 이벤트로 직접 넘겨주면 좋지만, 저는 이벤트에 너무 구체적인 정보가 들어가는것 같아요! 이 이벤트를 다른 쪽에서도 Listen 할 수 있으니까 특정 행위(달성률 계산)에 대한 구체적인 정보는 최대한 없애는게 좋다고 생각합니다.

`eventListener`애서 `checkFeedRepository`를 통해서 이 정보를 가져오는건 어떨까요?

2024-01-20 07:28 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomLeaderUpdateEventListener.java
이 클래스도 이름에 행위의 목적이 들어있는거 같아요! 골룸 생성에 대한 이벤트를 발행하고, 그걸 들어서 처리하는 쪽에서 구체적인 행위를 하면 더 좋을 것 같습니다! 이벤트명도 마찬가지 입니다!

2024-01-20 07:28 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/EmptyGoalRoomDeleteEventListener.java
이 클래스랑 이벤트 네이밍도 위 의견들이랑 같습니다~!

2024-01-20 14:37 UTC, Ohjintaek approved these changes
일단 요즘 리뷰가 너무 늦어져 죄송합니다 😥 두 번째도 많은 수정을 하셨겠군요...
제가 코멘트한 부분에 대해서는 추가적인 제의사항이 없어 approve합니다.

그와 별개로 두둠이 전에 코멘트하신 부분과 관련해서 `GoalRoom`과 `GoalRoomMember`, `GoalRoomPendingMember` 간의 양방향 의존성을 없애기 위해서 현재 GoalRoom에서 참가한 멤버들에 대한 의존성을 다 끊은 것에 대해서 의견드릴 부분이 있습니다.

`GoalRoom`의 생명주기가 멤버들과 달라서 의존성을 끊어버렸는데, 멤버들 개개인은 다르지만 `GoalRoom`과 `GoalRoomMembers` 혹은 `GoalRoomPendingMembers`, 즉 멤버들과는 같다는 생각이 듭니다. 골룸에 참가할 때 반드시 멤버들에 대한 정보를 필요로 하고, 골룸에서 나갈 때도 모든 멤버들이 나갔을 때 골룸을 삭제하거나 리더가 나갔다면 새롭게 리더를 선정하기 위해 멤버들에 대한 정보를 필요로 합니다.
비즈니스 규칙상 엄청 연관되어 있는 객체다 보니 분리하고 보니 서비스 레이어에 코드가 다 넘어가서 제 개인적으로는 코드가 더 읽기 어려워진다는 단점도 있는 것 같구요.
해당 부분에 대해서는 `무조건 했으면 좋겠다`가 아닌 의견 제시일 뿐이니 밀리가 맞다고 생각하신 대로 진행하시면 좋을 거 같습니다.
수고하셨어요👍👍

2024-01-20 14:37 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/goalroom/service/GoalRoomReadService.java
> +                goalRoom, currentGoalRoomRoadmapNode);
다시 생각하니 코드 흐름 상으로는 `checkfeed`가 `goalroom`을 알고 있으니까 밀리 말이 맞네요 😀
Optional을 파라미터로 넘기는 것에 대한 부분은 동일하니까 해당 부분만 옮기면 충분할것 같습니다!!

2024-02-10 10:03 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/AccomplishmentRateUpdateEventListener.java
오 그렇군요! 
이벤트 자체에 의도를 담으면 개념적인 결합도는 아직 높은 상태인 것이군요! 
덕분에 아주 중요한 것을 깨달았어요 👍👍 
이벤트에 의도가 드러나지 않게 모두 수정하겠습니다!

2024-02-10 10:07 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/checkfeed/service/event/AccomplishmentRateUpdateEvent.java
> +        int pastCheckCount
저도 그렇게 생각해요! 
이벤트에는 최소한의 필요한 정보만 전달하는게 좋겠네요!

2024-02-17 10:09 UTC, miseongk commented
@Ohjintaek 썬샷의 코멘트를 보고 엄청 많이 고민을 해봤어요!
저도 `GoalRoom`에서 `GoalRoomMembers` 의존성을 끊으면서 서비스 레이어에 모든 로직이 넘어가는게 고민이 많았어요!

그래서 다시 한번 곰곰히 생각을 해봤는데, 
`GoalRoomMembers`가 변경되면 `GoalRoom`에도 영향을 줄 수 있기 때문에 의존성을 끊었는데, 사실 `GoalRoomMembers`가 하는 일이 거의 없더라구요. 거의 대부분의 메서드가 검증하는데 쓰이고, 이 말은 `GoalRoom`과 `GoalRoomMember`가 **도메인 제약조건을 강하게 공유**한다는 뜻인 것 같아요. 이런 경우에는 굳이 의존성을 끊을 필요가 없다고 생각해요!
또한 이후에도 `GoalRoomMember`를 갖고 로직을 수행할 여지도 별로 없는 것 같아요. (혹시 떠오르는 상황이 있다면 알려주세요.. 저는 정말 모르겠어요 🥲)

하지만 양방향 연관관계는 없는게 좋은 것 같아요. 전에는 생각을 못했는데 `GoalRoomMember`가 `GoalRoom`을 참조하는 것을 없애서 양방향을 끊어주는 쪽이 더 나을 것 같아요! `GoalRoomMember`에서 `GoalRoom`을 사용해서 로직을 처리하는 메서드도 전혀 없더라구요. 😅
이 부분은 어떻게 생각하시나요?!

혹시 제가 생각하지 못한 부분이나, 다른 관점으로 봐야 한다거나 그런 것들이 있으면 알려주시면 감사하겠습니다. 🙇‍♀️🙇‍♀️🙇‍♀️
@younghoondoodoom

2024-02-17 12:14 UTC, Ohjintaek commented
저도 `GoalRoom`과 `GoalRoomMember`간의 양방향 연관관계를 없애는 게 낫다고 생각합니다. GoalRoomMember를 가지고 GoalRoom을 찾을일도 없을 거 같구요

> GoalRoomMembers가 변경되면 GoalRoom에도 영향을 줄 수 있기 때문에 의존성을 끊었는데, 사실 GoalRoomMembers가 하는 일이 거의 없더라구요. 거의 대부분의 메서드가 검증하는데 쓰이고, 이 말은 GoalRoom과 GoalRoomMember가 도메인 제약조건을 강하게 공유한다는 뜻인 것 같아요. 이런 경우에는 굳이 의존성을 끊을 필요가 없다고 생각해요!
또한 이후에도 GoalRoomMember를 갖고 로직을 수행할 여지도 별로 없는 것 같아요. (혹시 떠오르는 상황이 있다면 알려주세요.. 저는 정말 모르겠어요 🥲)

그런데 이 부분에 대해서는 제가 잘 이해를 못 했는데 혹시 한 번 더 설명해주실 수 있나요? `GoalRoomMembers`가 하는 일이 거의 없어서 의존성을 끊을 필요가 없다는 부분이 어떤 의미인지 잘 모르겠어서요 😅

2024-02-18 06:57 UTC, miseongk commented
@Ohjintaek 

기존 `GoalRoom`이 `GoalRoomMembers`를 의존하는 구조에서는 `GoalRoom 내부에서 GoalRoomMembers를 통해 validate 하는 로직을 수행`했었는데, `GoalRoom`에서 `GoalRoomMembers`를 제거하니 `서비스 레이어에 검증` 부분이 모두 넘어갔죠! 
그런 문제가 있음에도 의존성을 끊었던 이유는, `GoalRoomMembers`가 변경되었을 때 서로 양방향 의존을 하고 있어서 양쪽에 변경지점이 발생할 여지가 있어 유지보수성이 떨어지기 때문이었어요! 

하지만 `GoalRoomMembers`가 **검증 로직 이외에 별다른 역할이 없기 때문에 변경될 가능성이 적다**고 판단했고, 양방향 의존 문제는 **`GoalRoomMember`의 `GoalRoom`을 제거**하면서 해결할 수 있으니까 
굳이 `도메인 제약조건이 강하게 결합되어 있는 GoalRoom과 GoalRoomMember의 의존성을 끊을 필요가 없다`고 생각했어요!

2024-05-18 17:43 UTC, merged