Feature/ck 43
woowacourse-teams/2023-co-kirikiri pull request #22
Opened 2023-07-19 07:52 UTC by NaveOWO

## 📌 작업 이슈 번호

## ✨ 작업 내용

## 💬 리뷰어에게 남길 멘트

## 🚀 요구사항 분석

2023-07-20 01:49 UTC, sh981013s requested changes
코드 너무 잘봤습니다! 👍👍

여러번 읽었지만 저는 딱히 크게 바꿀 부분을 못찾겠네요..! 👍 👍

확실히 범용성있게 커스텀 훅을 짜더라도 컴파운드 패턴 형식으로 짜면 사용처(사용 컴포넌트)에서 상태를 따로 관리를 하지 않아도 됬겠네요!

이부분은 차차 시간 나면 마이그레이션 하는 방향을 얘기해 봅시다!

고생하셨어요~~~~

2023-07-20 01:49 UTC, sh981013s commented on client/src/styles/GlobalStyle.tsx
> +
의도된 개행일까요???!

2023-07-20 01:49 UTC, sh981013s commented on client/src/hooks/_common/useValidateInput.ts
> +    const { rule, message } = pattern;
구조분해 할당이 훅의 최상단 스코프에서 이루어진다면 코드의 중복을 막을수도 있을 것 같아요!

2023-07-20 01:49 UTC, sh981013s commented on client/src/components/roadmapCreatePage/input/inputLabel/inputLabel.styles.ts
> +    color: red;
theme 에 선언되어있는 색상변수를 사용해도 될 것 같아요!

2023-07-20 01:49 UTC, sh981013s commented on client/src/components/roadmapCreatePage/mainText/mainText.tsx
> +const MAIN_TEXT_MAX_LENGTH = { rule: /^.{0,2000}$/, message: '' };
regex 와 에러 메세지를 같은 형식으로 가진 객체의 위치가 사용처에서 반복되는 것 같은데 상수화를 시켜 모아두는것도 어떨까 싶네요!

2023-07-20 02:20 UTC, evencoding requested changes
네이브 너무 멋진 훅을 만들어 주신 것 같아요!
빨리 써보고 싶네요🤩

너무 고생하셨습니다!!!
몇 가지 코맨트 확인 부탁드릴게요🥹

2023-07-20 02:20 UTC, evencoding commented on client/src/components/roadmapCreatePage/title/title.tsx
> +    useValidateInput(TITLE_MAX_LENGTH);
pattern에 에러 메시지가 함께 들어가는데, pattern이라는 네이밍이 변하거나 pattern과 error 메시지를 따로 보내주면 어떨까 하는 생각이 들었어요!

이건 네이브의 의견이 궁금해요🥹

2023-07-20 02:20 UTC, evencoding commented on client/src/hooks/_common/useValidateInput.ts
> +export const useValidateInput = (pattern: any) => {
제네릭이 아닌 any가 들어간 이유가 있을까요?

2023-07-20 02:20 UTC, evencoding commented on client/src/hooks/_common/useValidateInput.ts
너무 사용하기 편한 훅을 만들어 주신 것 같아요🤩
빨리 써보고 싶네요!

2023-07-20 02:20 UTC, evencoding commented on client/src/hooks/_common/useValidateInput.ts
> +  };
`e.target.value`가 반복되고 있네요

아래와 같이 구조분해 할당을 사용하는 방법에 대해 네이브의 의견이 궁금해요🤩
```ts
const controlInputChange = ({ target: { value }}: ChangeEvent<HTMLTextAreaElement>)
```

상위 스코프에 value라는 네임의 변수가 이미 존재하기 때문일까요?

2023-07-20 02:20 UTC, evencoding commented on client/src/hooks/_common/useValidateInput.ts
> +      e.target.value = e.target.value.slice(0, -1);
이 코드는 사용자가 입력한 값을 잘라내어 마치 사용자가 입력하지 않은 것처럼 보이는데, 이는 React의 "단방향 데이터 흐름" 원칙에 위배되는 걸로 보여요🤩

pattern에 맞지 않으면 상태를 업데이트하지 않고 `return` 해주는데, 따로 입력받은 문자열을 잘라내는 이유가 궁금해요!

2023-07-20 02:20 UTC, evencoding commented on client/src/hooks/_common/useValidateInput.ts
> +  const validateInput = () => {
Input의 유효성 검사를 수행하는 함수를 연상시키는 네이밍이라는 생각이 들었어요!

`isInputValid`와 같이 boolean 을 반환한다는 것을 명확히 하는 건 어떨까요?

2023-07-20 04:37 UTC, NaveOWO commented on client/src/styles/GlobalStyle.tsx
> +
린트 적용이 안되네요;; 수정했어요 :)

2023-07-20 04:53 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/input/inputLabel/inputLebel.tsx
> +      {text} <p>*</p>
이런 태그가 있는줄 몰랐네요! 좋은 생각이에요!!!수정했습니다~!

2023-07-20 04:54 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/input/textCount/textCount.styles.ts
> +  ${({ theme }) => theme.fonts.button1}
맞아요.. font적용을 하면 스타일린트 적용이 안되더라구요.. 우디 아이디어가 좋은 것 같아요!! 수정해놓을께요!!! 공유부탁🙏

2023-07-20 05:15 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/input/textCount/textCount.tsx
> +  const { maxCount, currentCount } = props;
저는 컴포넌트에는 다양한 상황에 따라 props가 얼마든지 늘어날 수 있다고 생각해서 애초에 컴포넌트를 생성할 때부터 인자를 1개만 받고 함수 안에서 그 props를 비구조화할당했어요!!
지금처럼 1-2개의 인자는 그냥 비구조화할당해도 괜찮지만, props가 더 늘어난다면
```js
const TextCount = ({ maxCount, currentCount,props2, props3 ,props4 }: TextCountProps) => {
  // 생략...
```
이런식으로 가독성이 떨어진다고 생각했기 때문이에요!
우디는 어떻게 생각하세요?

2023-07-20 05:24 UTC, NaveOWO commented on client/src/hooks/_common/useValidateInput.ts
> +export const useValidateInput = (pattern: any) => {
ㅁㅊ네요.. 감삼다👍

2023-07-20 05:44 UTC, NaveOWO commented on client/src/hooks/_common/useValidateInput.ts
> +  };
오! 좋아요!! 생각 못해봤던 부분인데 감사해용~ 수정했습니당

2023-07-20 16:36 UTC, NaveOWO commented on client/src/hooks/_common/useValidateInput.ts
> +      e.target.value = e.target.value.slice(0, -1);
진짜 날카로운 리뷰 감사감사👍 해당 e.taret.value를 변경해줘야 입력이 막히는거라고 판단했는데, 그냥 저 value를 input의 속성으로 달아서 해결했습니다!

2023-07-20 16:40 UTC, NaveOWO commented on client/src/hooks/_common/useValidateInput.ts
> +  const validateInput = () => {
저는 validate 자체가 유효성을 검사한다는 뜻이고, 유효한지 안한지에 대한 boolean값을 반환하는게 일반적이지 않나..? 생각했어요!
함수의 네이밍은 동사+명사 의 형태로 짓는게 컨벤션이기도 했구요! 우디는 어떠세요!?

2023-07-20 17:09 UTC, sh981013s approved these changes
변경사항들 다 너무 잘 반영된 것 같아요! 고생하셨어요~~ 밤 늦게까지 고생하셨습니다! 👍👍👍👍

2023-07-23 02:50 UTC, evencoding commented on client/src/hooks/_common/useValidateInput.ts
> +  const validateInput = () => {
저도 유효성을 검사한다는 의미로 받아들였어요!

네이브의 의견에 동의합니다🤩
단순히 boolean을 반환하는 것이 아니라 에러가 발생했을 때, 에러 메세지를 set해주고 있으니 네이브가 지은 네이밍이 의미가 있는 것 같아요!

2023-07-23 03:01 UTC, evencoding commented on client/src/components/roadmapCreatePage/input/textCount/textCount.tsx
> +  const { maxCount, currentCount } = props;
확실히 props가 많아진다면 가독성이 떨어질 수 있겠네요! 동의해요🤩

혹시 코드 컨벤션처럼 1~3개의 props에 대해서는 전자와같이, 4개 이상의 props에 대해서는 후자와 같이 작성하도록 규칙을 만드는 것은 어떨까요?
대부분의 컴포넌트들은 3개 이하의 props를 받을 것 같아서요!

크게 중요한 부분은 아니라고 생각하지만 네이브의 의견을 들어보고 싶어요!

2023-07-23 03:13 UTC, evencoding commented on client/src/components/roadmapCreatePage/title/title.tsx
> +    useValidateInput(TITLE_MAX_LENGTH);
두개를 세트로 묶어서 보내주는 것은 너무 좋은 것 같아요!
단지 `PATTERN`이라는 이름은 실제 패턴(정규 표현식)을 연상시키는데, 에러 메시지도 함께 포함하고 있다는 점을 고려하면, 이를 모두 반영하는 더 포괄적인 이름을 좋을 수 있겠다고 생각했어요

`VALIDATION_RULES`과 같은 네이밍이라면 유효성 검사 규칙을 포함하고 있음을 명확히 하고 있으니 내부에 pattern과 에러 메시지가 들어있어도 어색하지 않게 느껴지지 않을까? 했습니다!

이건 네이브의 의견을 따라가고 싶어요🤩

2023-07-23 03:13 UTC, evencoding approved these changes

2023-07-23 06:51 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/input/textCount/textCount.tsx
> +  const { maxCount, currentCount } = props;
좋은 생각이에요!! 월요일에 다같이 확정지읍시다~!

2023-07-23 06:52 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/title/title.tsx
> +    useValidateInput(TITLE_MAX_LENGTH);
아하! 네이밍의 문제였군요ㅠㅠ 네이밍을 좀 더 포괄적으로 수정해볼께요!!

2023-07-23 11:05 UTC, merged