[feat/CK-25] 골룸 단일 조회 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #23
Opened 2023-07-19 14:00 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-25](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-25)

## ✨ 작업 내용
- 골룸에 대한 단일 조회 기능을 구현하였습니다.
- 비로그인, 로그인에 대해 단일 조회 기능에 대한 API를 나누었습니다.

## 💬 리뷰어에게 남길 멘트
- 로그인한 사용자와 로그인하지 않은 사용자에 대해 골룸 단일 조회 API를 다르게 생성하였습니다.
- 로그인한 사용자에 대한 endpoint를 `/goal-rooms/certified/{goalRoomId}`로 만들기는 했는데, path의 경우 계층형 데이터에 잘 어울리는 URI이다 보니 어울린다는 생각이 잘 안 들어서, 혹시 좋은 의견이 있으면 제시 부탁드립니다! 🥹 로그인한 경우는 해당 골룸에 참여하고 있는지에 대한 여부를 추가로 반환해줍니다.

- 해당 골룸에 참여하고 있는지에 대한 여부를 추가 쿼리를 날려서 우선 간단하게 구현하였는데, 골룸 조회 시 한 번에 조회하는 게 나을지, 아니면 이대로 가면 좋을지도 의견 부탁드립니다!
	- 만약 한 번에 조회한다면 쿼리 반환 값으로 `GoalRoom` 자체가 아닌 Dto를 통해서 받아와야 해서 아마 꽤 복잡해질 것 같아요. (지연 로딩이 아마 안 될 것 같기도 하구요… )
	- 참고로 이 테이블에 대해서 다양한 쿼리가 발생할 것 같지 않아서 queryDSL 대신에 JPQL을 사용했습니다. 
	- existBy를 사용하지 않은 이유는 inner join을 사용하기 위해 + count(*) 하는 과정이 부하가 클 것이라고 생각했어요!

- 골룸의 노드 정보를 가져올 때 `@BatchSize`를 통해서 1:N 관계의 엔티티를 가져오는 쿼리를 최적화했습니다! (노드는 아무리 많아도 10개를 넘어갈 것 같다는 생각이 안 들어서 우선 10으로 했는데, 노드 개수가 더 많아진다면 20 정도로 늘려도 좋을 것 같아요!)

- 추가적으로 골룸 생성 API가 없어서 단일 조회 인수 테스트에서 `roadmapRepository`를 의존합니다. 이는 골룸이 로드맵 본문을 의존하면서 영속화되어 있는 엔티티가 필요해서 따로 레파지토리를 통해 저장해주었어요.

+ 아 그리고, rest-docs 생성할 때 메서드 이름이 하위 패키지 이름이 되는데 이름이 너무 길면 중간에 잘리더라구요… ㅋㅋㅋㅋ
그래서 `GoalRoomReadApiTest`에서 `골룸_아이디와_사용자_아이디로_골룸_조회시_골룸_아이디가_유효하지_않으면_예외_발생()` 메서드는… ~한다 포맷을 지키지 못했습니다 🥹 이름 제한을 늘리는 걸 찾아보는데 안 보이네요…? 제가 버그 걸려서 그런 걸까요… ㅠ_ㅠ

## 🚀 요구사항 분석
- 골룸 단일 조회 기능을 구현한다.
	- 골룸 제목, 골룸의 로드맵 노드 리스트 (해당 노드의 제목과 시작 날짜, 종료 날짜, 인증 횟수), 총 골룸 기간
	- 로그인 시 해당 골룸에 대한 참여 여부를 추가적으로 반환한다.

2023-07-21 02:33 UTC, miseongk requested changes
져니 어떻게 이렇게 빠르게 잘 구현하시나요 너무 고생하셨어요👍
제 생각을 남겼으니 확인해주세요 ㅎㅎ

2023-07-21 02:33 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepository.java
> +}
사소하지만 메소드명이 findBy**GoalRoomAndMemberIdentifier** 이니까, 메소드 인자의 순서가 `GoalRoom`이 먼저 나오는게 더 좋을 것 같아요! 어떻게 생각하시나요??

2023-07-21 02:33 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
> +    private EntityManager entityManager;
얘는 사용하지 않네요🙃

2023-07-21 02:56 UTC, miseongk commented
> 로그인한 사용자에 대한 endpoint를 /goal-rooms/certified/{goalRoomId}로 만들기는 했는데, path의 경우 계층형 데이터에 잘 어울리는 URI이다 보니 어울린다는 생각이 잘 안 들어서, 혹시 좋은 의견이 있으면 제시 부탁드립니다! 🥹 로그인한 경우는 해당 골룸에 참여하고 있는지에 대한 여부를 추가로 반환해줍니다.

적절한 uri를 생각해보려는데 정말 어렵네요,, `/goal-rooms/certified/{goalRoomId}` 이렇게 하니 골룸들 중에 인증된 골룸 중에서 골룸을 조회하는 느낌도 드네요. 흠.. 아니면 순서를 바꾸는건 어떤가요? `/goal-rooms/{goalRoomId}/certified` 이렇게요!

> 해당 골룸에 참여하고 있는지에 대한 여부를 추가 쿼리를 날려서 우선 간단하게 구현하였는데, 골룸 조회 시 한 번에 조회하는 게 나을지, 아니면 이대로 가면 좋을지도 의견 부탁드립니다!

골룸 조회할 때 로그인 한 사용자가 조회할 일도 많아서 자주 요청되긴 하겠네요..? 근데 한 번에 조회하는 것이 좀 복잡할 것 같아서 저는 일단은 이대로 가도 좋을 것 같아요!

2023-07-22 09:09 UTC, younghoondoodoom requested changes
고생하셨습니다 져니! 테스트도 충분한 것 같고, 프로덕션 코드도 꼼꼼하게 하신 것 같아요!
> 로그인한 사용자에 대한 endpoint를 /goal-rooms/certified/{goalRoomId}로 만들기는 했는데, path의 경우 계층형 데이터에 잘 어울리는 URI이다 보니 어울린다는 생각이 잘 안 들어서, 혹시 좋은 의견이 있으면 제시 부탁드립니다! 🥹 로그인한 경우는 해당 골룸에 참여하고 있는지에 대한 여부를 추가로 반환해줍니다.

좀 더 계층적으로 생각해보면 `/certified/goal-rooms/{goalRoomId}`가 나을 것 같습니다! 
그리고 controller도 `CertifiedGoalRoomController`와 `GoalRoomController`가 나뉠 수도 있을 것 같고.. 잉건 좀 애매할 수도 있을 것 같네요. 아니면 `CertifiedController(prefix = /certified)`가 상위에 있고 각 `CertifiedXXXController`가 상속을 받게 하는 것도 괜찮을 수도 있고.. 나중에 한번 얘기해봐요!

>해당 골룸에 참여하고 있는지에 대한 여부를 추가 쿼리를 날려서 우선 간단하게 구현하였는데, 골룸 조회 시 한 번에 조회하는 게 나을지, 아니면 이대로 가면 좋을지도 의견 부탁드립니다!

저는 `GoalRoom`에서 `GoalRoomPendingMember`를 가지고있게해서 양방향 연관관계로 구현을 했습니다! 뭐가 더 나을지는 모르갰지만, 조금 더 객체지향적으로 하려면 그게 나을 수도 있을 것 같아요. 져니와 다른 분들 생각이 궁급합니다!

> 아 그리고, rest-docs 생성할 때 메서드 이름이 하위 패키지 이름이 되는데 이름이 너무 길면 중간에 잘리더라구요… ㅋㅋㅋㅋ
그래서 GoalRoomReadApiTest에서 골룸_아이디와_사용자_아이디로_골룸_조회시_골룸_아이디가_유효하지_않으면_예외_발생() 메서드는… ~한다 포맷을 지키지 못했습니다 🥹 이름 제한을 늘리는 걸 찾아보는데 안 보이네요…? 제가 버그 걸려서 그런 걸까요… ㅠ_ㅠ

이렇게 하면 아마 될거에요!
```java
.andDo(document("골룸_아이디와_사용자_아이디로_골룸_조회시_골룸_아이디가_유효하지_않으면_예외_발생", // 여기에 문서 이름을 직접 명시
        responseFields(
             // 어쩌고저쩌고
        )


제 생각 간단하게 남겼으니까 참고 부탁드립니다~💪

2023-07-22 13:17 UTC, Ohjintaek reviewed
역시 엄청난 속도의 져니... 수고하셨습니다
동적 쿼리에 대해서 아직 잘 몰라서 코멘트 드릴 수 있는 부분이 많지 않네요. 통합 테스트에서 로그인 상태에서 조회 요청을 보낼 때만 추가해주면 감사하겠습니다😊😊

> 로그인한 사용자에 대한 endpoint를 /goal-rooms/certified/{goalRoomId}로 만들기는 했는데, path의 경우 계층형 데이터에 잘 어울리는 URI이다 보니 어울린다는 생각이 잘 안 들어서, 혹시 좋은 의견이 있으면 제시 부탁드립니다!
이 부분에 대해서는 하나의 API로 처리하는 방법을 생각해보려 했는데 어렵네요. 적당한 방법이 생각안난다면 저는 `/certified`가 제일 앞에 오는 게 나을 거 같아요

> 해당 골룸에 참여하고 있는지에 대한 여부를 추가 쿼리를 날려서 우선 간단하게 구현하였는데, 골룸 조회 시 한 번에 조회하는 게 나을지, 아니면 이대로 가면 좋을지도 의견 부탁드립니다!
추가 쿼리를 날리는 게 크게 비용이 드는 거 같지 않아서 괜찮다고 생각합니다. 아니면 두둠이 구현한 것처럼 양방향을 선택한다면 골룸에서 바로 알 수 있겠네요

2023-07-23 03:56 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
> +                                                         @PathVariable("goalRoomId") final Long goalRoomId) {
앗 `@MemberIdentifier`만 사용하더라도 괜찮지 않나요?
두 어노테이션을 함께 붙여서 2중 방어를 하자고 하시는 거죠?!

2023-07-23 03:58 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
> +    private EntityManager entityManager;
헉 테스트 때문에 둔 거였는데 안 지우고 올려버렸네요... 🥹

2023-07-23 04:09 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
> +        // expected
전에 밀리가 이런 식으로 작성한다고 말씀하시길래 반영해봤어요! 
저는 페어 프로그래밍 할 때 종종 이렇게 쓰시는 분들을 뵀어서 이 방식도 좋다구 생각해요 ㅎㅎ

2023-07-23 04:10 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +
예리하시네요...

2023-07-23 13:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +        return goalRoomPendingMemberRepository.findByGoalRoomAndMemberIdentifier(identifier, goalRoom).isPresent();
> existBy를 사용하지 않은 이유는 inner join을 사용하기 위해 + count(*) 하는 과정이 부하가 클 것이라고 생각했어요!

엇 이 부분은 위와 같은 이유로 사용하지 않았습니다!
지금 알아보니까 JPARepository에서 활용하는 existsBy~를 사용했을 때는 (JPQL X) 알아서 limit 1을 걸어줘서 최적화가 되기는 하네요. 근데 count 쿼리의 경우 데이터의 개수를 카운트 하기 위해 테이블 전체를 스캔해야 돼서 (테이블 풀 스캔이 발생합니다) 성능상 이슈가 있을 것 같아요!
만약 인자로 memberId 값을 받는다면 existBy를 활용할 텐데 identifier를 받고 있는지라 메서드로 활용은 불가능할 것 같아서 inner join을 해서 fk는 인덱스가 걸려 있을 테니 좀 더 빠르게 조회될 수 있지 않을까 생각했습니다!
나중에 더미 데이터 넣어서 한 번 분석해봐야겠네용

2023-07-23 13:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/QuerydslRepositorySupporter.java
> +    }
넵 생각해보니 생성자 주입을 하려면 해당 메서드의 생성자가 1개여야 하는데 저희는 도메인 클래스를 받는 생성자가 있어서 생성자 주입을 하기에는 어려울 것 같아요...! (내부적으로 querydsl이나 queryFactory 같은 값은 빈으로 주입받는 게 아니라 초기화 작업도 필요하다 보니까 setter 주입으로 하는 게 맞을 것 같습니다!)

2023-07-23 15:36 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
> +                                                         @PathVariable("goalRoomId") final Long goalRoomId) {
> 개인적으로 2가지를 함께 사용한다면 @MemberIdentifier만 단독으로 사용할 경우는 없을 테니까 해당 어노테이션의 리졸버에서 인증 헤더를 체크하는 부분은 제거해도 될 것 같은데, 어떻게 생각하시나요?

아하 그렇네요! `@MemberIdentifier`만 단독으로 사용할 일은 절대 없으니까 인증헤더를 체크하는 부분은 제거해도 될 것 같네요! 
근데 지금까지 리뷰하면서 확인해봤는데 다들 `@Authenticated` 어노테이션을 안쓰셨더라구요..! 그래서 둘 다 붙이기에 너무 번거로운가 하는 생각도 드네요🤔 이 부분은 확실하게 이야기 하고 정하는게 좋을 것 같아요!

2023-07-24 00:59 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    @BatchSize(size = 10)
제가 BatchSize를 잘못 알고 사용했던 것 같네요 ㅎㅎㅎ...
현재는 1인 엔티티에서 n인 엔티티를 가져오는 경우니까 where절을 통해서 로드될 테니 설정할 필요가 없을 것 같네요.
제거하도록 하겠습니다!

2023-07-24 01:30 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
> +
앗 이게 나눈 이유가...
저희가 실제로 가입 처리를 할 때도 처음에 프로필 이미지 정보를 받지 않고, 나중에 회원 정보를 수정하면서 프로필 이미지를 넣기 때문에 해당 플로우를 비슷하게 따라가기 위해서 메서드를 추가해두었습니다!
제 테스트에서 프로필 이미지가 없어도 충분히 잘 돌아가기 때문에 우선 해당 프로덕션 코드는 제거하도록 하겠습니다!

2023-07-24 01:35 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
> +        return values;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
방어적 복사 할게요......... 죄송합니다...

2023-07-24 01:41 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +    }
id가 null인 경우에 equals를 타는 경우가 있을까요...?
즉시 로딩이라면 값은 채워져 있을 것이고, 지연 로딩이라면 id를 접근했을 때 필드값이 채워지기 때문에 null이 들어오지 않을 것 같아서요!
근데 이거랑 별개로 BaseEntity 쪽에 id를 위임하는 게 더 좋을 것 같다는 생각이 듭니다 ㅠㅠ equals hashcode가 현재 너무 남발되는 느낌이 들어서요!

2023-07-25 04:53 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                                        fieldWithPath("isJoined").description("골룸 참여 여부 (true / false)"))))
responseField만 있으면 적용해볼만 한데 문서화에 필요한 다른 필드값들도 같이 필요하다 보니까 적용하기 애매하네요...
나중에 develop으로 두둠이 작성해주신 코드가 올라가면 해당 포맷 맞춰서 전반적으로 리팩터링 진행해보겠습니다!

2023-07-25 06:17 UTC, Cl8D commented
위의 리뷰까지 반영 완료했습니다 🙇‍♀️
골룸 단일 조회 시 현재 인원 수랑 모집 인원 수가 반영되도록 추가하였습니다~

2023-07-25 07:08 UTC, Ohjintaek reviewed
수고하셨어요 져니~
전 이 PR엔 수정 요청이 거의 없었어서 바로 approve합니다

2023-07-25 07:32 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +    }
인정합니다👍 제가 잘못 생각했네요!

2023-07-25 07:44 UTC, miseongk approved these changes
리뷰 반영하시느라 고생하셨어요!!
approve 할게요~~😊

2023-07-25 07:44 UTC, younghoondoodoom approved these changes
고생하셨습니다 져니~!
다시 남기신 코멘트에 대해서 확인하고 모두 Resolve conversation 했습니다! 
final 잘못 붙히신게 있어서 이 부분만 확인해 주세요! Approve 하겠습니다💪

2023-07-25 07:44 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMember.java
> +    private final Double accomplishmentRate = 0.0;
save action으로 final이 붙은거 같네요!

2023-07-25 07:48 UTC, Ohjintaek approved these changes

2023-07-25 08:25 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMember.java
> +    private final Double accomplishmentRate = 0.0;
요 부분은 다시 제거하더라도 붙을 것 같아서 우선 두고, 나중에 수정하려구요!! ㅠㅠ

2023-07-25 08:25 UTC, merged