[feat/CK-26] 골룸 참가 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #24
Opened 2023-07-20 09:16 UTC by Ohjintaek

## 📌 작업 이슈 번호
[CK-26](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-26)

## ✨ 작업 내용
- 골룸에 참가하는 기능을 만들었습니다. 다음과 같은 경우에 참가가 불가능합니다.
  - 골룸 아이디가 존재하지 않는 경우
  - 모집 중인 골룸이 아닌 경우
  - 제한 인원이 가득찬 골룸일 경우
  - 이미 참석한 골룸일 경우
- 로그인하지 않은 상태로 골룸 참가 요청이 오는 경우 요청이 실패합니다.

## 💬 리뷰어에게 남길 멘트
- 연관관계 신경쓰는 게 가장 어렵네요. Entity에 취약점이 있는지 봐주시면 감사하겠습니다.
- 골룸 참가 제약 조건에 따른 예외 호출을 도메인과 서비스에 나뉘어져 있습니다. 각 레이어에서 발생해야 한다고 생각하기 때문에 그렇게 하긴 했는데 기능에 따른 어떤 예외가 발생하는지 한 눈에 발생하는지 모른다는 단점도 있는 거 같습니다. 객체에 isValidate()와 같이 물어봐서 서비스에서 예외처리하는 게 더 나은지 의견 주시면 감사하겠습니다.
- 이미 참석한 골룸인지 알기 위한 로직이 제대로 된 건지 잘 모르겠네요. `GoalRoom`의 validateParticipation() 메서드에 대해 의견주시면 감사하겠습니다.

## 🚀 요구사항 분석
- [x] 사용자들이 골룸에 참여할 수 있다.
    - [x] 로그인한 상태에서만 골룸에 참여할 수 있다.
    - [x] 이미 참여한 골룸에는 참여할 수 없다.
    - [x] 이미 시작한 골룸에는 참여할 수 없다.
    - [x] 제한 인원이 가득 찬 골룸에는 참여할 수 없다.
- [x] 사용자의 참가에 따른 엔티티를 수정한다
    - [x] 골룸 엔티티의 현재 인원 수를 수정한다
    - [x] 임시 골룸 사용자 엔티티를 하나 더 저장한다

- request
    - /api/goal-rooms/{goalRoomId}/join

2023-07-21 02:40 UTC, Cl8D requested changes
고생하셨어요 썬샷~! 
몇 가지 리뷰를 달았는데 한 번 보시구 천천히 적용해주세요!

2023-07-21 02:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
> +        Assertions.assertAll(
요부분은 변경 감지에 대해서도 테스트를 한 것이죠?
다만 `findAllByGoalRoom()`가 테스트를 위한 메서드인 게 마음에 걸리네요 🥹

2023-07-21 02:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceTest.java
> +    GoalRoomService goalRoomService;
요기도 private로 막아줄 수 있겠네요!

2023-07-21 02:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceTest.java
> +                .thenThrow(new AuthenticationException("존재하지 않는 회원입니다."));
`memberRepository.findByIdentifier()`는 Optional 형태죠!
레파지토리가 예외를 발생시키는 것이 아닌, 서비스에서 Optional의 값이 비어있을 때 오류를 나타내는 형태여서 위 코드는 레파지토리가 예외를 터트리는 것처럼 보일 것 같아요! 
```java
when(memberRepository.findByIdentifier(any()))
                .thenReturn(Optional.empty());
```
요런 식으로 수정해야 한다고 생각합니다!
(하위에서도 Optional을 반환하는 경우 다 그렇게 수정해주세요!!)

2023-07-21 02:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceTest.java
> +        final GoalRoom goalRoom = 골룸을_생성한다(creator, roadmapContent, 1);
혹시 세 번째 인자로 들어가는 값에 대해서 변수로 추출하는 건 어떨까요?
`final int limitedMemberCount = 1;`
이런 식으로 선언해두면 테스트가 더 이해하기 쉬울 것 같아요!

2023-07-22 17:17 UTC, miseongk requested changes
썬샷 고생하셨어요☀️
제 생각을 남겨보았는데 확인해주세요 ㅎㅎ

> 골룸 참가 제약 조건에 따른 예외 호출을 도메인과 서비스에 나뉘어져 있습니다. 각 레이어에서 발생해야 한다고 생각하기 때문에 그렇게 하긴 했는데 기능에 따른 어떤 예외가 발생하는지 한 눈에 발생하는지 모른다는 단점도 있는 거 같습니다. 객체에 isValidate()와 같이 물어봐서 서비스에서 예외처리하는 게 더 나은지 의견 주시면 감사하겠습니다.

저는 도메인에 로직이 풍부한 게 더 좋다고 생각해서 도메인에서 할 수 있는 처리라면 도메인에서 하는 것이 좋아요😊

2023-07-23 15:09 UTC, younghoondoodoom requested changes
고생하셨습니다 썬샷~! 구현도 제대로 된 것 같고, 테스트도 충분하다고 느껴지네요! 
앞서 다른 분들이 리뷰를 많이 남겨주셔서, 중복되는 부분은 따로 이야기 하지 않았습니다! 간단하게 제 생각 남겼으니 참고 부탁드립니다🙇‍♂️

2023-07-23 15:09 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
> +                                fieldWithPath("recommendedRoadmapPeriod").description("로드맵 추천 기간")
저는 이 부분 때문에 테스트 가독성이 떨어지는 것 같아서 추상화 했습니다!
https://github.com/woowacourse-teams/2023-co-kirikiri/pull/28/commits/6908cf91e648c59d6239d73c691f0230c2125d3b
썬샷도 괜찮은 것 같으면 추상화를 해보는건 어떨가요?

2023-07-23 15:09 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +    }
상수로 선언하지 않고 메소드를 따로 만들어서 사용하는 이유가 있나요??

2023-07-25 12:13 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    private void validateParticipation(final GoalRoomPendingMember member) {
`is~`라는 네이밍이면 boolean을 반환해야할 거 같은데 `validatedAlreadyParticipated()`는 어떤가요?

2023-07-25 12:26 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +                .anyMatch(goalRoomPendingMember -> Objects.equals(member.getMember(),
```
return (a == b) || (a != null && a.equals(b))
```
Objects.equals가 이렇게 구현되어 있으니 두 객체의 주소값이 같다면 같은 객체로 판정합니다. 같은 엔티티라면 true가 나오니 괜찮은 거라고 생각했는데 취약한 경우가 있을까요?

2023-07-25 12:49 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                .join(anyString(), anyLong());
😅 헤더가 없을 때 골룸 참가 요청이 안 된다는 걸 테스트하고 싶었는데 생각해 보니 컨트롤러 이전에 발생하는 일이라 여기엔 맞지 않는 것 같네요. 무엇보다도 저런 예외 메시지를 반환하는 부분도 없구요 ㅋㅋㅋㅋㅋ

삭제하겠습니다.

2023-07-25 12:55 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                        )));
```
.andExpect(jsonPath("$.message").value("존재하지 않는 골룸입니다. roadmapId = 1"))
```

이 부분으로 반환하는 body의 메시지 검증으로 부족할까요?

2023-07-25 12:55 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
> +                .isEqualTo(savedRoadmap);
불편하시다니 편안하게 해 드리겠습니다

2023-07-25 13:28 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
> +        Assertions.assertAll(
처음에 생성할 때 충분히 추후에 추가될 수 있는 메서드라고 생각했습니다.
- 해당 골룸에 참가하고 있는 사용자 리스트 반환
- 골룸 시작 시 PendingMember들을 GoalRoomMember로 이관

2023-07-25 13:34 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceTest.java
> +                .thenThrow(new AuthenticationException("존재하지 않는 회원입니다."));
아 맞네요😅😅
서비스 내부의 기능을 무시하고 바로 원하는 예외를 던져서 서비스의 기능을 제대로 테스트하고 있지 못하고 있었네요

2023-07-25 13:41 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +class GoalRoomReadApiTest extends ControllerTestHelper {
컨트롤러 테스트도 CreateApi로 바꿔주었습니다!!!

2023-07-25 13:53 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +        goalRoomPendingMember.updateGoalRoom(this);
Member를 받았을 때 GoalRoom이 GoalRoomPendingMember를 생성하는 역할을 가진 거 같아서 생성할 때 외부에서 넣어주는 방식으로 구현했었습니다. 다만 맥락상 더 어울리거나 이해하기 쉬운 편은 Member를 넣어주는 거 같아서 고민이 되는 부분이네요.

하지만 더 궁금한 부분은 골룸이 만들어질 때 "시진이"는 사실 반드시 있을 수  밖에 없다고 생각해서 생성자에서 받아주는 식으로 구현한 건데 일단 텅 빈 멤버인채로 생성한 뒤에 addMember와 같은 식으로 구현하는 경우도 있더라구요. 이 부분에 대해서 다른 분들의 생각이 궁금합니다. 나중에 conflict 해결할 때 합쳐야 되는 부분이구도 하구요

2023-07-25 16:49 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    private LimitedMemberCount limitedMemberCount;
두둠이 구현할 때 제약사항 넣으려고 따로 분리할 거라고 얘기를 했었어서 저도 나중에 conflict 해결할 때 편하려고 따로 분리했었어요.😁😁

2023-07-25 17:27 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> -        final RoadmapCategory roadmapCategory = findRoadmapCategoryById(request.categoryId());
헉 큰일날 뻔 했네요...😢
정말 죄송하고 감사합니다

2023-07-25 17:33 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
> +    }
선언해놓고 UnauthorizedException을 호출하는 곳이 없네요. 두둠 말대로 기존 커스텀 예외로도 충분하니 삭제해주었습니다

2023-07-25 17:55 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +    }
취향 차이인거 같긴 한데 가장 밑에 둬서 잘 안 보이게 하는 것도 좋아하고 Member 내에 들어가는 값이 의미를 가지는 테스트인 경우 그 테스트 메서드 내부에서 직접적으로 어떤 값이 들어갔는지 알 수 있어서  메서드를 선호하는 편입니다

2023-07-25 18:01 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +        if (!status.equals(GoalRoomStatus.RECRUITING)) {
```
if (status != GoalRoomStatus.RECRUITING)
```
져니가 enum은 메서드를 사용하지 않고 연산자로 비교 가능하다고 추천해줘서 위와 같이 바꿨는데 이 경우는 어떤가요?

2023-07-25 18:07 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
> +                                fieldWithPath("recommendedRoadmapPeriod").description("로드맵 추천 기간")
나중에 한 번 참고해서 적용해볼게요!!!

2023-07-26 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    private void validateParticipation(final GoalRoomPendingMember member) {
오오 좋아요 👍

2023-07-26 09:51 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +                .anyMatch(goalRoomPendingMember -> Objects.equals(member.getMember(),
equals, hashcode는 동등성 비교를 위해서 사용하는데 동일성 비교 때 쓰이는 주소값을 기준으로 하는 게 조금 어색하지 않을까요? 😮
아마 BaseEntity를 상속받으면 이 부분은 해결될 것 같아요! (develop으로 merge 시에)

2023-07-26 09:51 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/LimitedMemberCount.java
> +    private Integer value;
사실 제 개인 취향이었어서 (숫자 관련 필드에 null이 디폴트인 게 쪼끔 별로였음) 반영하지 않으셔도 됩니다!

2023-07-26 09:52 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                        )));
아 해당 부분을 못 봤네요 🥲 충분합니다!

2023-07-26 09:55 UTC, Cl8D approved these changes
썬샷 고생하셨어요!! 👍
저는 approve 하겠습니다! merge 파이팅!!

2023-07-27 06:18 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +        goalRoomPendingMember.updateGoalRoom(this);
제가 밀리의 요지를 잘못 파악했었네요.. `GoalRoomPendginMember`를 받아서 등록하는 것에는 동의합니다! 다만 안에서 updateGoalRoom을 호출하는것이 조금 어색한 것 같다라는 내용이었습니다!

2023-07-27 06:35 UTC, younghoondoodoom approved these changes
고생하셨습니다 썬샷~! 
방금 구두로 `GoalRoomPendingMember`와 관련된 내용만 수정해주세요~
이만 Approve 하겠습니다!

2023-07-27 06:42 UTC, miseongk approved these changes
고생하셨습니다~~ 
approve 할게요!

2023-07-27 06:42 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    private void setLeader(final Member member) {
setLeader라는 메서드명 보다 updateLeader는 어떠신가요?
set은 setter 느낌이 강해서 안에서 로직이 수행되는지 모르고 잘못 사용될 수도 있을 것 같아요!
(추후에 public 메서드로 열 때)

2023-07-29 04:44 UTC, merged