[feat/CK-24] 골룸 목록 조회 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #26
Opened 2023-07-20 13:34 UTC by miseongk

## 📌 작업 이슈 번호
[CK-24](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-24)

## ✨ 작업 내용
- 골룸 목록을 조건에 따라 정렬하여 조회하는 API를 구현했습니다.
- 정렬 조건은 '최신 생성된 순', '참여 중인 인원 순'이 있습니다.

## 💬 리뷰어에게 남길 멘트
- 참여 중인 인원 순은 단순히 골룸에 참여한 사람의 수가 많은 순으로 정렬하지 않고, 제한 인원 수와 현재 참여 인원 수의 비율로 정렬했습니다. 
마감 임박 순이라는 워딩이 더 적절할 것 같네요 🤔
- 골룸 목록 조회할 때, 골룸의 `startDate`와 `endDate`를 전달해야 하는데, 이 값은 저희가 따로 데이터베이스에 관리하고 있지 않습니다. 그래서 골룸의 로드맵 노드 테이블에 있는 노드들 중에서 가장 첫번째 노드의 시작 날짜를 `startDate`로, 노드들 중에서 가장 마지막 노드의 종료 날짜를 `endDate`로 반환하고 있습니다! 이게 전체 골룸의 기간이 되는거구요!
그래서 데이터 베이스에서 골룸 목록을 가져올 때 골룸 로드맵 노드를 `startDate`로 정렬해서 가져오도록 했습니다.
이런 로직이 괜찮은지 한번 봐주세요 ㅎㅎ (`GoalRoomRoadmapNodes`, `GoalRoomQueryRepositoryImpl` 이 클래스에 있습니다!)
- 제가 QueryDsl을 처음 써봐서 제대로 짰는지 모르겠네요ㅠㅠ 일단 돌아가게는 했는데, 성능같은 것을 고려하는 걸 아직 잘 못해서 그 부분 확인해 주시면 감사하겠습니다🥲

## 🚀 요구사항 분석
- [x]  골룸 목록을 조회한다.
    - [x]  표시될 정보는 **제목, 골룸 리더 정보, 현재 인원 수, 모집 인원 수, 생성 날짜, 시작 날짜, 종료 날짜**이다.
        - [x]  골룸 리더 정보에는 회원 Id, 닉네임이 있다.
        - [x]  현재 모집 중인 골룸만 표시한다.
    - [x]  정렬 기준은 **최신 생성된 순, 참여 중인 인원 순**이다.
        - [x]  정렬 기준의 디폴트는 최신 생성된 순이다.

2023-07-22 09:49 UTC, Cl8D requested changes
고생하셨어요 밀리!! 통합 테스트 보니까 정말... 고생하셨네요 ㅠㅠ
리뷰 보시구 반영하실만한 거 참고해주세요!

> 응답 DTO를 GoalRoomForListResponse라고 했는데, 단일 조회 시 사용하는 DTO와 공유할지 어떻게 될 지 아직 몰라서 목록 조회를 위한 DTO를 따로 만들었습니다..! 네이밍이 좀 별로인 것 같은데.. 추천해주시면 감사하겠습니다🫠
저는 개인적으로 `GoalRoomResponses` 정도면 충분하지 않나 생각합니다!

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +        this.roadmapContent = roadmapContent;
생성자 체이닝을 사용하면 좋을 것 같아요! 😮

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
> +    private LocalDateTime joinedAt;
갑자기 생각난 건데, 요런 식으로 createdAt의 데이터만 분명하게 필요한 데이터들이 있을 테니 BaseTimeEntity에서 BaseCreatedTimeEntity를 따로 분리해서 관리하는 건 어떻게 생각하세요?! (막상 joinedAt 필드를 보니까, 이 필드를 위해서 `@EntityListeners` 어노테이션에 대한 의존 관계를 가지고 있는 게 마음이 안 좋네요 🥲)

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
> +        return role.equals(GoalRoomRole.LEADER);
Enum은 ==으로도 비교가 가능하답니다! 😶

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +    }
개인적으로 여기에서 `Member` 엔티티를 바로 반환하기보단, GoalRoomPendingMember에서 getMember를 하는 로직은 외부 서비스에서 호출해도 좋을 것 같아요! (도메인 결합도를 줄이면 좋으니까요!)

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNode.java
> +    private final Integer checkCount = 0;
인증 횟수 필드를 final로 막은 이유가 있으실까요? 😮
0으로 초기화되어 있는 이상 나중에 업데이트가 될 값일 텐데, final로 막으면 제대로 동작을 안 하지 않을까요?

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    @OneToMany(fetch = FetchType.LAZY,
개행 컨벤션! 👀

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
~~골룸 노드맵 생성할 때 노드의 순서가 꼭 보장되고, 내부에서 시작 / 종료 기간이 오름차순이어야 정상적으로 실행될 로직이겠네요 👀~~

> 그래서 골룸의 로드맵 노드 테이블에 있는 노드들 중에서 가장 첫번째 노드의 시작 날짜를 startDate로, 노드들 중에서 가장 마지막 노드의 종료 날짜를 endDate로 반환하고 있습니다! 이게 전체 골룸의 기간이 되는거구요!

DB 조회 시 반영이 되는 부분이었군요!
하지만 버그 가능성을 염두해 둬야 할 것 같아요! (우선은 넘어가도 됩니당 ㅎㅎ)

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
> +    Page<GoalRoom> findGoalRoomsPageByCond(GoalRoomFilterType filterType, Pageable pageable);
final 컨벤션 👀

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .offset(pageable.getOffset())
나중에 무한스크롤 방식으로 간다면 no-offset 전략을 선택할 거여서 이 로직이 조금 달라질 거예요.
기획 확정되면 변경될 수 있는 사항이니 우선 기억만 해두셔도 좋을 것 같아요! 😮

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
leftJoin을 사용하셨군요! 
`goalRoomPendingMembers`나 `goalRoomRoadmapNodes`가 없더라도 골룸 정보는 조회되어야 하기 때문에 leftJoin을 활용한 것은 좋은 전략이에요.

하지만 만약 1번 골룸에 대해서 goalRoomPendingMembers에 2명의 멤버, goalRoomRoadmapNodes에 3개의 노드가 있다면 결과가 어떻게 나올까요? 😮
우리가 원하는 건 1번 골룸에 대한 정보만 필요한데, 아마 더 많은 개수의 골룸 정보가 나올 거예요.
1:N 관계에서 조인을 사용할 때는 특히 더 주의해야 하는 부분이죠! (사실 저는 여러 개의 1:N에서는 조인을 잘 안 쓰는 것 같아요 ㅎㅎ)

이에 대해서 어떤 식으로 처리하면 좋을지 한 번 고민해보는 게 좋을 것 같아요 😎

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .orderBy(sortCond(filterType), goalRoomRoadmapNode.startDate.asc())
date에 대한 조건도 벼롣의 메서드로 분리해도 좋지 않을까요? (시작 날짜에 대해서 오름차순으로 정렬)

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +
카운트 쿼리는 원본 select절이랑 동일한 구조로 들어가야 한답니다!
`select *` -> `select count(*)` 이 차이라고 보셔도 돼요 ㅎㅎ

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +    }
나중에 develop으로 merge 할 때 리팩터링 하면 좋을 것 같아요!
제가 이번 PR에서 페이징 처리에 대해서 쉽게 할 수 있도록 헬퍼 메서드를 몇 개 생성해두었는데, 이를 활용하면 좋을 것 같아요!

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +        return goalRoom.limitedMemberCount.divide(goalRoom.goalRoomPendingMembers.values.size()).asc();
오 비율을 이렇게 설정하셨군요!
궁금한 게 `goalRoomPendingMembers.values.size()`가 0인 경우는 어떻게 동작하나요?!
자동으로 0으로 가는 건지, 아니면 예외 처리가 필요한지 궁금하네요 😮

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +                roadmapCategory);
엇 저는 메서드로 분리한 거 좋았는데 다시 푸셨네요!! 🥲

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
> +        }
두 값 (`GoalRoomFilterTypeDto`, `GoalRoomFilterType`)이 완전히 일치함을 보장한다면 valueOf을 바로 호출해도 충분하답니다! (저도 처음에 밀리처럼 했다가 나중에 수정했어요 ㅎㅎ 비즈니스로 나갈 오류가 아닌 것 같아서!)

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
> +    }
`goalRoom`을 통해 `member`에 대한 정보도 가져오고 있네요!
`goalRoom` 조회 시 member도 함께 조회할 수 있도록 join을 해도 좋지 않을까요? 😮

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +@SuppressWarnings("NonAsciiCharacters")
와 몰랐는데 코드가 너무 길면 기본으로 리뷰할 때 코드를 안 펼쳐줘서(?) 이 부분은 코드 리뷰를 못할 뻔 했네요... ㅋㅋㅋㅋ
잘 확인하고 리뷰해야겠어요 😮

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +    @Autowired
`@SpringBootTest` 시 모든 빈이 로드되기 때문에 `@Autowired`를 붙이지 않아도 생성자 주입이 된답니다!

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                                        fieldWithPath("data[0].goalRoomLeader.name").description("골룸 리더의 닉네"))
닉네?! 👀

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +    void 골룸을_최신순으로_조회한다() throws UnsupportedEncodingException, JsonProcessingException {
테스트가 어마어마하네요... 🥹

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +        goalRoomPendingMemberRepository.save(new GoalRoomPendingMember(GoalRoomRole.LEADER, 골룸2, 골룸2에_참여한_사용자));
참가 인원 수에 따라 정렬하는 테스트인데 참가 인원이 똑같은 상태네요!
복사 붙여넣기 하면 안 돼요 밀리 😔

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +        assertThat(최신순_골룸_목록_조회_응답값).isEqualTo(최신순_골룸_목록_조회_예상_응답값);
최신순?! 👀

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +                () -> assertThat(goalRoomsPage.getContent()).usingRecursiveComparison()
record에 대해서는 usingRecursiveComparison()을 사용하지 않아도 동등성 비교가 가능합니다~!

2023-07-22 09:49 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +        goalRoom2.joinGoalRoom(GoalRoomRole.LEADER, goalRoomPendingMember2);
요기도 마찬가지로 참여 중인 인원수를 변경한 상태로 테스트를 해야 할 것 같아요!

2023-07-22 16:59 UTC, Ohjintaek requested changes
목록 조회는 테스트 //given에서 선언해줄 변수들이 두 배네요😵 수고하셨어요!!

골룸의 기간을 계산할 때 각 노드들이 겹치지 않는다는 제약이 없어서 오류가 있을 수도 있을 거 같네요. 이 부분은 정책을 정해서 골룸 생성할 때 막던지, 전체 노드의 시작 날짜와 끝나는 날짜를 비교해야 할 수도 있을 거 같아요

2023-07-22 16:59 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +        return goalRoom.limitedMemberCount.divide(goalRoom.goalRoomPendingMembers.values.size()).asc();
여기 골룸에 참여중인 멤버 수를 얻기 위해 goalRoom.getCurrentPendingMemberCount()를 사용할 수 있지 않을까요?

2023-07-22 16:59 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +@SuppressWarnings("NonAsciiCharacters")
저도 통합 테스트 본 적 없는데 갑자기 서비스 테스트라서 올려봣네요 ㅋㅋㅋㅋ

2023-07-23 15:50 UTC, younghoondoodoom requested changes
고생하셨습니다 밀리~! 구현 잘 된 것 같고, 테스트도 충분하네요👍
아직 해당 브랜치에 전에 사용하던 `@AuthPrincipal`이 있네요! 이 부분 삭제 해주시면 좋을 것 같아요!
다른 분들과 겹치는 리뷰는 생략했습니다! 간단하게 제 생각 남겼으니 참고 부탁드립니다🙇‍♂️

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +        return ResponseEntity.created(URI.create(httpServletRequest.getRequestURI() + "/" + id)).build();
오 이렇게도 표현할 수 있군요! `httpServletRequest.getRequestURI()`로 하신 이유가 있으신가요? 저는 명시적으로 적는게 가독성 측면에서는 나을 수도 있을 것 같습니다!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    }
외부에서 `GoalRoomPendingMember`를 받지 않고 안에서 생성해주는 이유가 있을까요?

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +        return new ArrayList<>(values);
방어적 복사👍

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +    }
저는 개인적으로 `Member`를 반환하는것은 찬성입니다..! 객체간 결합도가 높긴하지만, 이미 필드로 가지고있으니 결합도가 높은것은 어쩔 수 없는것 같은데 밀리의 생각이 궁금하네요!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNode.java
> +    private final Integer checkCount = 0;
intellj save action이 자동으로 주입해줬군요.. 그 옵션을 빼야 겠네요ㅠ

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +        values.add(goalRoomPendingMember);
여기도 가능하다면 방어적 복사를 하면 좋을 것 같네요!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +        this.values = values;
`GoalRoomPendingMembers`를 불변객체로 만들어서 안정성을 높이기위해 방어적 복살로 내부 에다가 추가하면 어떨까요? 
```java 
this.values.addAll(new ArrayList<>(values));
```

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
이 메소드가 항상 보장이 되기 위해서, 정렬하는 로직을 먼저 호출하는게 좋을 것 같아요!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
> +        this.values.addAll(roadmapNodes);
방어적 복사를 했으면 좋겠네요!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
> +        this.values.addAll(roadmapNodes.getValues());
여기서 방어적 복사를 하는 로직을 만들어서 생성자에서 호출하면 좋겠네요!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
> +        this.values.add(roadmapNode);
이 부분도 방어적 복사가 이뤄지면 더 안전한 객체가 될 것 같습니다!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
위 문제를 해결하기 위해서 `distinct()`를 활용할 수 있을 것 같습니다!

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
`leftJoin`👍

2023-07-23 15:50 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                                        fieldWithPath("data[0].goalRoomLeader.name").description("골룸 리더의 닉네"))
저는 이 부분 때문에 테스트 가독성이 떨어지는 것 같아서 추상화 했습니다!
https://github.com/woowacourse-teams/2023-co-kirikiri/pull/28/commits/6908cf91e648c59d6239d73c691f0230c2125d3b
밀리 괜찮은 것 같으면 추상화를 해보는건 어떨가요?

2023-07-24 10:53 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNode.java
> +    private final Integer checkCount = 0;
헉 맞아요 save action이 붙여준 것 같아요🥲

2023-07-24 11:03 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
> +    private LocalDateTime joinedAt;
좋아요! 아까 져니가 말씀하신 부분이네요!
저는 찬성입니다~~

2023-07-24 11:36 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +    }
저는 결합도는 생각하지 않고 의미적으로만 생각해서 Member를 꺼내서 전달했었어요! 
골룸의 리더를 찾는데 GoalRoomPendingMember를 전달하는 것보다 Member를 전달하는게 의미적으로 자연스럽다고 생각했어요. 그런데 결합도가 높아지는 문제가 있긴 하네요,, 흠,, 어렵네요 어떡하죠? ㅎ

2023-07-24 11:39 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
여기서 말하는 버그 가능성은 DB조회 시 데이터베이스에서 일어나는 버그를 말씀하시는 건가요?!

2023-07-24 12:02 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +
헉 그렇군요 뭣도 모르고 썼네요,,,, 😅

2023-07-24 12:08 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +    @Autowired
앗 그런데 `@SpringBootTest` 때문이 아니라 IntegrationTest에 `@TestConstructor(autowireMode = TestConstructor.AutowireMode.ALL)`가 있어서 `@Autowired`를 붙이지 않아도 되는거네요! 
지금 보니까 제 IntegrationTest에 저 어노테이션이 안붙여져있어서 오류가 났고, 그래서 생성자에 `@Autowired`를 붙였었네요!

2023-07-24 12:15 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +        goalRoomPendingMemberRepository.save(new GoalRoomPendingMember(GoalRoomRole.LEADER, 골룸2, 골룸2에_참여한_사용자));
참가 인원은 똑같은데 제한 인원수가 달라서 제대로 동작해요! 
참가 인원 순이라는 워딩이 한번에 와닿지 않는 것 같네요,, **골룸 참가율..? 순**이 더 좋을 거 같은데 변경할게요~!

2023-07-24 17:26 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
이 부분에 대해서 찾아보다가 잘 모르겠어서 디버깅을 해봤는데 아래와 같은 결과가 나왔어요!
goalRoomPendingMembers에 2명의 멤버, goalRoomRoadmapNodes에 3개의 노드를 설정해주고 해봤어요.
그랬더니 골룸 하나에 GoalRoomPendingMembers의 사이즈가 2, GoalRoomRoadmapNodes의 사이즈가 3으로 나오더라구요!
<img width="541" alt="스크린샷 2023-07-25 오전 2 15 54" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/39994337/30b5e8e5-c1f8-47de-b35e-23df181ee52d">
DB에서는 left join을 하면 골룸에 대해서는 동일한 결과가 나오지만, jpa에서 객체로는 GoalRoom이 List<GoalRoomPendingMember>를 가지고 있어서 동일한 결과가 나오지 않은것 같아요!

그래서 결론은 left join을 사용해도 중복되지 않는것 같은데, 제가 제대로 디버깅 한게 맞겠...죠?
확인부탁드립니다~~🙇‍♀️

2023-07-25 03:54 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +                roadmapCategory);
맞아요.. 저도 이전에 분리한 게 좋았는데 알고보니까 makeRoadmap이라는 메서드명이 인자 순서만 다르고 동일하더라구요 ㅠㅠ
마땅한 메서드명을 못찾아서 다시 풀었는데, 다시 분리해볼게요!

2023-07-25 04:17 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
> +        }
아하 그렇네요!
그런데 `GoalRoomFilterTypeDto`, `GoalRoomFilterType` 이 완전히 일치함을 보장하는것은 그냥 저희가 실수하지 않는 방법밖에는 없는거겠죠..?

2023-07-25 05:00 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
앗 아뇨!
개발자가 새로운 기능을 개발할 때 골룸 노드맵 정보를 반환할 일이 있을 때 정렬을 깜빡하고 안 했다면 해당 코드는 버그 가능성이 있다는 생각이 들었어요! 도메인 객체가 항상 정렬된 상태로 만들어져야 잘 동작하는 코드니까요!

2023-07-25 05:02 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +    }
흐음... 의미적으로는 그게 더 어울릴 것 같네요. 
대기 리스트에서 하나의 대기를 가져오는 것보다 그 안에 있는 리더를 가져오는 게 더 의미상으로 적합하니까요.
그대로 가셔도 좋아요!

2023-07-25 05:04 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
> +        }
넵!
개발자가 코드를 잘 짜면 되는 거죠 ㅎㅎ enum에 대해 정의를 잘하면 되는 거니까요!
아니면 아예 ServerException으로 가는 게 어울릴 것 같아요.

2023-07-25 05:19 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
엇 그런가요? 
혹시 flush를 하고 나서도 확인해보셨을까요? 😮

2023-07-25 06:45 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
>      private static final int CONTENT_MAX_LENGTH = 150;
헉 그렇네요..! 큰일날뻔했네요.. 감사합니다 수정했습니다!

2023-07-25 07:22 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
정렬하는 로직은 DB에서 쿼리로 설정해주었어요!

2023-07-25 07:28 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +        return ResponseEntity.created(URI.create(httpServletRequest.getRequestURI() + "/" + id)).build();
명시적으로 적으려다가 api라는 prefix가 변경이 될 수도 있을 것 같아서 저렇게 했었습니다!
yml에 path를 적어놓은 것은 변경될 수 있는 값이라고 생각해서 직접 적어주지 않는게 낫겠다고 판단했는데,
만약 변경될 확률이 적다면 굳이 저렇게 하지 않아도 될 것 같아요!
이부분은 어떻게 생각하시나요??

2023-07-25 07:33 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    }
의미적으로 골룸에 참여할 때 GoalRoomPendingMember를 인자로 받아서 추가하기보다, 어떤 사용자가 골룸에 참여하려고 하면 (Member를 받아서) 메서드 내부에서 PendingMember로 변경해서 추가하는게 좋겠다고 생각했어요! 

'골룸 대기 사용자가 골룸에 참여한다'보다 '사용자가 골룸에 참여한다.' 가 자연스럽지 않나요?!
골룸에 참여하는 joinGoalRoom이라는 메서드를 외부에서 사용할 때는 대기자 명단으로 들어가는지 그냥 골룸 참여자 명단으로 들어가는지 내부의 행위에 대해서는 몰라도 된다고 생각했어요!
이 부분은 다들 어떻게 생각하시나요?

2023-07-25 07:35 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +        return goalRoom.limitedMemberCount.divide(goalRoom.goalRoomPendingMembers.values.size()).asc();
여기서 `goalRoom`은 QGoalRoom.goalRoom을 static import한 것이에요! 그래서 일반 GoalRoom 엔티티 내부의 메서드를 사용할 수 없어요!

2023-07-25 07:37 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
아하 그렇군요!
그렇다면 DB에서 정렬을 하더라도 코드 단에서 방어적으로 한 번 더 정렬을 수행한 뒤 하는게 좋겠네요..🤔

2023-07-25 12:20 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
앗 그렇군요,, flush/ clear 하니까 중복되네요...ㅠㅠ

밑에 져니가 리뷰 남겨주신 'Member도 함께 조인하는 것'과 이 '중복문제'를 계속 해결해보려고 했는데, 
GoalRoomPendingMember와 GoalRoomRoadmapNode가 각각 GoalRoom과 1:N 관계여서 조인이 한번에 안되더라구요,,
그래서 GoalRoomPendingMember -> Member -> MemberProfile은 연관관계가 잘 이어져서 중복되지 않기 때문에, 골룸과 이 3개의 테이블을 조인하도록 했습니다. 그리고 이후에 GoalRoomRoadmapNode를 사용하는 시점에 select 쿼리가 나가도록 (일단은) 했습니다😭 해결 방법을 못찾겠더라구요,,,, 

만약 이 부분이 성능상 너무 좋지않다싶으면, 추후에 성능 개선을 해볼 수 있도록 하면 좋을 것 같아요. 
사실 GoalRoomRoadmapNode를 조인하려는 이유는 골룸의 시작 날짜와 종료 날짜를 받아오는 것 때문인데요. 이 시작 날짜와 종료 날짜를 아예 GoalRoom 테이블에 골룸 생성 시 함께 필드에 저장하는 방법도 있을 것 같습니다!

2023-07-25 12:23 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                                        fieldWithPath("data[0].goalRoomLeader.name").description("골룸 리더의 닉네"))
너무 좋은 것 같아요! 두둠의 코드가 머지된 이후에 수정하도록 할게요!!

2023-07-26 01:27 UTC, miseongk commented
리뷰 반영 완료했습니다!
아직 resolve되지 않은 코멘트 확인부탁드려요~🙇‍♀️

2023-07-26 08:30 UTC, Ohjintaek approved these changes
어프루브 드립니다~

2023-07-26 09:39 UTC, Cl8D approved these changes
고생하셨어요 밀리!! 👍
merge 작업이 엄청 빡셀 것 같다는 예감이 드네요...
조금만 더 파이팅해요 :D

2023-07-27 06:42 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +        return ResponseEntity.created(URI.create(httpServletRequest.getRequestURI() + "/" + id)).build();
오 저도 그럼 동의합니다!

2023-07-27 07:35 UTC, younghoondoodoom approved these changes
고생하셨습니다 밀리~! 이만 Approve 하겠습니다. 파이팅 하세요💪

2023-07-27 07:35 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(goalRoom.goalRoomRoadmapNodes.values, goalRoomRoadmapNode)
골룸의 총 기간, 시작, 종료 등에서 시작 날짜와 종료 날짜를 사용하겠네요. 그때마다 `GoalRoomRoadmapNode`를 join하는 것은 비효율적인 것 같긴해요! 저도 시작날짜와 종료날짜가 GoalRoom에 있으면 좋을 것 같습니다!

2023-07-28 04:39 UTC, merged