[feat/CK-62] 로드맵 리뷰 생성 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #27
Opened 2023-07-20 14:03 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-62](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-62)

## ✨ 작업 내용
- 로드맵 리뷰 생성 기능을 추가하였습니다. 리뷰 생성 로직이 생각보다 까다로워서 시간이 좀 더 걸렸네요...
- 원래 로드맵 목록 조회 필터링 중에서 리뷰와 관련된 부분도 이번에 수정할까 고민하다가, 리뷰 생성 기능이 완전히 develop에 merge된 다음에 적용하는 게 나을 것 같아서 진행하지 않았습니다. 다음 스프린트 때 적용하면 될 것 같아요.

## 💬 리뷰어에게 남길 멘트
- DTO 패키지의 경우 develop으로 올라간 거 받으려고 여기 브랜치에서는 작업하지 않았습니다! (골룸 단일 조회 쪽에서 작업해두었어요!)
- 리뷰 작성 기능에서 생각보다 여러 레파지토리를 의존하고 있는데, 서비스를 분리하는 게 나을까요? (근데 분리하기도 좀 애매하기는 해요…)
- 말씀드렸던 것처럼 리뷰 엔티티와 로드맵 사이의 양방향 의존 관계를 설정하였습니다. 더 좋은 방법이 있는지는 고민해봐야 할 것 같아요.

- 그리고 현재 통합 테스트에서 레파지토리를 많이 의존하는데요! 우선 리뷰를 작성하기 위해서는 참여한 골룸이 완료해야 합니다. 아마 실제 프로덕션 구현상 골룸 완료에 대한 update 쿼리는 변경 감지를 통해서 생성할 것 같아서 테스트를 위한 메서드를 만들기가 좀 그렇더라구요… 
	- 그래서 우선 골룸 생성할 때 애초부터 status를 `COMPLETED`로 설정한 상태로 만들었습니다.

- 그리고… 조금 이상한 게 로드맵 생성 API를 만들고 왜 또 로드맵을 저장하는지 이상하게 느껴질 수 있는데요. 이전 PR 보냈던 골룸 단일 조회랑 동일한 사용 예제예요.
	- 로드맵 저장 후 조회를 통해 반환 받은 정보에 로드맵 본문 아이디가 없다 보니까 해당 response 값을 바탕으로 로드맵 엔티티를 새로 만들다 보니 내부에 있는 값들이 영속화가 되지 않아서 연관된 엔티티에 대한 정보가 세팅이 되지 않아요. 
	- 하지만 외래키 제약 조건으로 인해서 해당 값이 엔티티로 생성될 때 비어있으면 안 되다 보니까 로드맵 자체를 다시 저장해서 저장된 값 (영속화된 값)을 가져오고, 해당 값으로부터 본문 정보를 가져와서 골룸을 생성해주었습니다.
- 즉, 로드맵 생성 API 호출 > 반환받은 로드맵 아이디를 바탕으로 로드맵 조회 API 호출 > 조회를 통해 얻은 response 값으로 로드맵 엔티티를 만들려고 했으나 외래키 제약 조건으로 인해 연관된 엔티티 값들까지 함께 채워져 있어야 함 > 이를 위해 또 다시 로드맵 저장…하는 로직입니다.
- 나중에 골룸 생성 API가 있다면 해당 API를 호출해서 리팩터링을 할 수 있을 것 같은데, 골룸 API에서도 결국 골룸 생성을 위해서라면 로드맵 본문 ID 정보가 필요해서 저희 API 응답값도 다시 맞춰봐야 할 것 같아요. 생각보다 연관된 엔티티에 대한 정보들이 많이 필요할 것 같습니다…!

- 또한, `Roadmap` 엔티티에서` isCreator()` 메서드에 대해 `equals` & `hashcode`를 재정의하였는데도 id 값을 비교하는 이유는,
로드맵에 대해서 member를 조회해올 때 지연로딩으로 인해서 member 엔티티를 프록시 객체로 설정해두어서 직접적으로 필드에 대해 접근하지 않으면 프록시 객체에 대해서 비교를 하다 보니 항상 false가 나오더라구요…

```java
public boolean isCreator(final Member member) {
    return Objects.equals(creator.getId(), member.getId());
}
```

혹시 이 부분에 대해서 좋은 아이디어가 있으신 분은 리뷰 부탁드립니다!! 객체 내부 메서드로 사용하기에는 지연로딩이랑 함께 사용하기가 어렵네요 ;ㅅ; (제가 잘 몰라서 이렇게 된 것일 수도 있습니다!)

## 🚀 요구사항 분석
- 로드맵에 대한 리뷰를 생성한다
	- 로드맵을 생성한 크리에이터는 리뷰를 달 수 없다.
	- 로드맵에 참여한 사람만 리뷰를 달 수 있다.
	- 리뷰는 1개만 달 수 있다.
	- 로드맵에 대한 완료된 골룸에 대해서만 리뷰를 달 수 있다.
- 리뷰는 내용과 별점 정보를 받을 수 있으며, 별점 정보는 필수값이 아니다.

2023-07-23 17:04 UTC, miseongk requested changes
져니 로드맵 리뷰 생성 구현까지 너무 고생하셨습니다👍
테스트도 많던데 이해하기 쉽게 잘 짜시는 것 같아요 ㅎㅎ
리뷰가 늦어져서 죄송합니다🙇‍♀️

2023-07-25 05:26 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +    @PostMapping("/reviews/{roadmapId}")
저도 밀리가 말씀해주신 게 더 잘 어울린다고 생각해요! 변경하였습니다 ㅎㅎ

2023-07-25 05:30 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
리뷰의 경우 로드맵의 변경 감지로 save가 되다 보니까 id를 어떤 식으로 얻어와야 할지 고민이더라구요 🥲
헤더에 값을 채워주기 위해서 다시 조회 쿼리를 날리는 것이 낭비라는 생각이 들어서 반환을 하지 않았는데, 이에 대해서는 어떻게 생각하시나요?

2023-07-25 05:31 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMember.java
> +    private final Double accomplishmentRate = 0.0;
아 그런 거였네요... 🥲
추후 변경되는 로직이 생겼을 때 final을 붙이면 되지 않을까 싶습니다!

2023-07-25 05:32 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapReview.java
> +        final String rateRegex = String.format(RATE_FORMAT, MAX_RATE, MIN_RATE, MIN_RATE, MAX_RATE - 1, RATE_UNIT);
앗 그러네요!! 리팩터링을 진행하고 수정했어야 했는데 그대로 둬버렸네요.
해당 부분은 제거하겠습니다!

2023-07-25 05:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +        final RoadmapReview roadmapReview = new RoadmapReview(request.content(), request.rate(), member);
엇 혹시 mapper로 만들어야 하는 이유가 있을까요?
`final RoadmapReview roadmapReview = new RoadmapReview(request.content(), request.rate(), member);`
이 과정을 Mapper로 위임하라는 말씀이실까요?

2023-07-25 05:35 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapReviewSaveRequest.java
> +        Double rate
헉 제가 리뷰 내용이 필수고 별점이 optional이라고 착각했네요 🥲
해당 부분은 수정하도록 하겠습니다!

2023-07-25 05:45 UTC, Cl8D commented
밀리 피드백까지 반영 완료했습니다~!

2023-07-25 11:41 UTC, Ohjintaek approved these changes
수고하셨습니다 져니
복잡해 보이는 부분이 리뷰 작성에 대한 제약 사항을 구현하기 위해 서비스에서 많은 일을 하는 부분인데 통합테스트가 잘 됐다면 충분히 구현이 잘 된 것으로 생각할 수 있을 것 같아요😁
`isCreator` 메서드는 리뷰 달았다가 PR 본문에 이유를 적어 놨길래 다시 지웠는데 지연 로딩이라 안 되는 건 신기하네요.

저는 바로 Approve 드리겠습니다. 리뷰를 테스트를 Roadmap 테스트에 넣을지 Create로 나눈 부분에 넣을지만 고민해주시면 감사하겠습니다

2023-07-26 04:50 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +        final RoadmapReview roadmapReview = new RoadmapReview(request.content(), request.rate(), member);
아니요!
그 컨트롤러에서 전달한 RoadmapReviewSaveRequest의 결합을 끊어주기 위해 DTO를 새로 만들어서 서비스 내에서 사용한다고 지금까지 이해했었는데, 그 이유가 아닐까요..?

2023-07-26 04:51 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
음 그럼 우선은 저희가 따로 리뷰에 대해 조회하는 페이지도 없고 기능도 생각해놓지 않은 상태라 굳이 id를 전달하지 않아도 괜찮을 것 같네요!

2023-07-26 14:03 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +        final RoadmapReview roadmapReview = new RoadmapReview(request.content(), request.rate(), member);
아아, 저는 객체 자체를 완전히 넘겨준다면 DTO를 통해 결합을 끊어주는 게 맞다고 생각하는데, 위의 상황에서는 실제 파라미터로 들어가는 값이 String, Double, Member 타입이다 보니까 따로 포장을 하지 않았어요!
VO나 다른 값을 사용하게 된다면 해당 mapper에서 생성해서 넘겨주는 게 맞다고 생각하는데, 여기는 기본 타입이랑 도메인 객체여서 포장하기 애매하다 생각했어요. 이에 대해서는 어떻게 생각하시나요? 😮

2023-07-26 15:02 UTC, Cl8D commented
리뷰 반영 완료했습니다! 🙇‍♀️

2023-07-27 05:29 UTC, younghoondoodoom requested changes
고생하셨습니다 져니~! 리뷰가 너무 늦었네요.. 
리뷰 남겼으니 참고 부탁드립니다~!

2023-07-27 05:29 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapReview.java
> +            throw new BadRequestException(String.format("리뷰는 최대 %d글자까지 입력할 수 있습니다.", CONTENT_MAX_LENGTH));
domain에서 `BadRequestException`를 사용하면서 드는 생각이 presentation에서 사용하는 exception이 domain에서도 사용하는게 조금 걸리네요. 차라리 domain에서 발생하는 에러를 따로 정의하고 service layer에서 특정 에러를 Presentation의 에러로 바꿔주는건 어떨까 생각이 들어요. 
바꾸자는건 아닌데 그랬으면 어땠을까 하는거니까 답변 안하고 넘어가셔도 됩니다!

2023-07-27 05:29 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/exception/ForbiddenException.java
프로덕션 코드에서 사용하지 않는 예외인데 정의하신 이유가 있으신가요?

2023-07-27 05:29 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
> +        doThrow(new ForbiddenException("로드맵에 대해서 완료된 골룸이 존재하지 않습니다. roadmapId = 1L memberIdentifier = cokirikiri"))
실제로 서비스에서는 `BadRequestException`이 던져지는 것 같습니다!

2023-07-27 07:00 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +    }
이게... develop에서 받아온 건데...... 🥲........ 다른 곳은 적용되어 있을 텐데..........
우선 여기서도 해둘게요.....

2023-07-27 08:14 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapReview.java
> +public class RoadmapReview extends BaseTimeEntity {
앗... 뭔가 꼬인 것 같네요. 수정하겠습니다!

2023-07-27 08:17 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapReview.java
> +            throw new BadRequestException(String.format("리뷰는 최대 %d글자까지 입력할 수 있습니다.", CONTENT_MAX_LENGTH));
예외는 common에 있기 때문에 domain과 presentation에서 사용되는 게 동일해도 괜찮다고 생각합니다!
계층간 예외를 철저하게 하는 경우는 백엔드 서버 쪽에서 사용자에게 내려가는 메시지를 정의해줄 때 필요하다고 생각해요.
지금은 클라이언트 개발자를 대상으로 하고 있기 때문에 괜찮지 않을까 생각합니다 😮

2023-07-27 08:18 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/exception/ForbiddenException.java
이게... Intellij 버그로 인해서 이전의 코드가 섞여들어간 것 같아요 🥲 수정하겠습니다!

2023-07-27 12:05 UTC, Cl8D commented
요기까지 리뷰 반영 완료했습니다 🙇‍♀️

2023-07-28 09:11 UTC, younghoondoodoom approved these changes
고생하셨습니다 져니~! 이만 Approve할게요

2023-07-28 10:09 UTC, miseongk approved these changes
고생하셨습니다~~ approve 할게요~!

2023-07-29 07:21 UTC, merged