[feat/CK-23] 골룸 생성 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #28
Opened 2023-07-20 16:20 UTC by younghoondoodoom

## 📌 작업 이슈 번호
[CK-23](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-23)

## ✨ 작업 내용
- 골룸 생성 기능을 구현했습니다. 워낙 많은 정보를 받아서 저장하다보니 mocking이나 인수테스트가 쉽지 않았네요!

## 💬 리뷰어에게 남길 멘트
- 인수테스트나 controller 테스트 할때 느낀건데, spring validation을 이용한 입력 값 검사 테스트가 굉장히 많지만 크게 의미 없다고 생각이 들었습니다. 예를들어 @NotNull을 테스트하는데, 단지 필드마다 메세지가 다르기 때문에 각각 테스트 해봐야합니다. 그리고 메세지가 "...은 빈값이면 안됩니다"같은 것이 반복이 될텐데, 이 메세지가 클라이언트에 의미 있는 메세지 같지 않습니다. 단순히 우리의 디버깅 용도일뿐.. 
그래서 그냥 "빈 값인 요청이 있습니다." 정도만 되어도 디버깅하기 편할것 같은데 여러분 생각은 어떠신가요?
- jpa의 양방향 연관관계 항상 유지하기가 굉장히 어렵다는 생각이 드네요. 부모에서 양방향 편의 메소드를 호출해서 자식도 부모를 가질 수 있는 메소드를 작성 합니다. 근데 애초에 자식을 생성할 때, 생성자에서 **영속화 되어있는 부모**를 받아야합니다! 영속화 되어있지 자식이 부모 id를 몰라서 `DataIntegrityViolationException`이 터집니다. 
그렇다면 자식을 생성자를 통해 생성하고, 부모의 양방향 편의 메소드를 호출하는 사이에는 자식만 부모를 알고 부모는 자식을 모르는 상황이 생기네요. 이 부분을 이해하고 있는 사람은 이 둘을 호출하겠지만, 사용자 입장에서 그냥 자식은 일단 부모 모르게 생성하고, 부모의 양방향 편의 메소드를 호출하면 되는거 아냐?라는 생각이 들 것 같습니다.
제가 이해한게 잘못됐거나 해결할 수 있는 좋은 아이디어 있으신 분은 제발 말씀해주세요ㅠㅠ
```java

## 🚀 요구사항 분석
- [x] 골룸 이름, 노드 별 기간, 최초 투두, 제한 인원 수, 컨텐츠 아이디 입력
    - [x] 골룸 이름 길이 : 1 ~ 40
    - [x] 노드 별 기간 : 입력 개수와 로드맵 노드 개수가 다르면 예외 발생
    - [x] 투두 리스트 : 첫 투두에 대해서만 생성
    - [x] 제한 인원 수 : 1 ~ 20
- [x] 골룸 이름 중복 가능
- [x] 생성 하자마자 골룸 상태는 인원 모집 중
- [x] 반환 시 Location header에 골룸 id를 포함 시킨다.
- [x] 골룸 생성 시 방장은 골룸 대기자 명단에 들어감

2023-07-22 13:08 UTC, Cl8D requested changes
두둠 정말 고생 많으셨어요 👍
간단하게 리뷰 남기려고 했는데 거의 2시간 동안 리뷰만 했네요…ㅎ
골룸 생성 로직이 정말 중요한 부분인데 꼼꼼하게 잘 짜주신 것 같아요!
천천히 보시구 반영할 부분 반영해 주세요~!

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/helper/FieldDescriptionHelper.java
> +    }
오 Helper 클래스를 생성하셨네요 👍
너무 좋은데 early return을 사용하시면서 if-else가 있는 것은 참을 수가 없네요… 🫣

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/helper/FieldDescriptionHelper.java
> +        }
생성자 체이닝을 통해 `restriction` 필드가 있는 생성자와 없는 생성자로 나누는 게 좋을 것 같아요!
외부에서 null을 통해서 직접 초기화하지 않아도 사용할 수 있도록요!

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +        assertDoesNotThrow(() -> goalRoom.participate(goalRoomPendingMember));
참여한 후에 goalRoomPendingMembers에 대해 getter로 값을 확인하면 테스트를 위한 Getter여서 별로겠죠...?

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +    void 골룸_참여_시_이미_참여한_사람이_다시_참여할_떼_예외를_던진다() {
`다시_참여할_떼`…? 😩

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomToDoTest.java
> +    void 골룸의_이름_길이가_1미만_40초과일_때_정상적으로_생성된다(final int length) {
테스트 메서드 이름이 심상치 않네요… ☹️

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomIntegrationTest.java
> +        final String 액세스_토큰 = BEARER + 로그인_응답_바디.accessToken();
테스트 가독성을 위해 여기까지 하나의 메서드로 분리해도 좋을 것 같아요!

하위에서 로드맵_id를 얻어내는 부분도 메서드로 추출하면 좋을 것 같네요! (67~69라인) 혹은 로드맵_생성 쪽에서 한 번에 해서 받아와도 되구요!

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomIntegrationTest.java
> +    void 골룸_생성_시_컨테츠id가_빈값일_경우() throws JsonProcessingException {
두둠 테스트 짜다가 쓰러지신 건 아니죠…?

2023-07-22 13:08 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomIntegrationTest.java
> +        final GoalRoomCreateRequest 골룸_생성_요청 = new GoalRoomCreateRequest(null, 정상적인_골룸_이름, 정상적인_골룸_제한_인원, 골룸_투두_요청, 골룸_노드_별_기간_요청);
위 테스트에서 null 값이 중요한 포인트인 것 같은데, 해당 값에 대해서 변수로 추출하면 더 이해하기 쉬운 테스트가 될 것 같아요!
마찬가지로 하위 메서드에서도 테스트 대상 변수는 따로 추출해두는 게 더 좋을 것 같습니다 ㅎㅎ

2023-07-22 19:40 UTC, Ohjintaek requested changes
수고하셨습니다 두둠😆
단순히 읽는 것만 해도 쉽지가 않네요

> 그렇다면 자식을 생성자를 통해 생성하고, 부모의 양방향 편의 메소드를 호출하는 사이에는 자식만 부모를 알고 부모는 자식을 모르는 상황이 생기네요. 이 부분을 이해하고 있는 사람은 이 둘을 호출하겠지만, 사용자 입장에서 그냥 자식은 일단 부모 모르게 생성하고, 부모의 양방향 편의 메소드를 호출하면 되는거 아냐?라는 생각이 들 것 같습니다.

저도 계속 헷갈려서 나중에 다 같이 엔티티들 필드 보면서 재정비하는 시간을 가지면 어떨까 하는 생각을 해요. 근데 진짜 `사용자 입장에서 그냥 자식은 일단 부모 모르게 생성하고, 부모의 양방향 편의 메소드를 호출하면 되는거 아냐?` 하는 생각 자주 했는데 아니었던 건가요...

2023-07-22 19:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
> +                                        fieldWithPath("data[0].roadmapContentId").description("로드맵 아이디"),
뭔가 바꾸면서 프로젝트의 몇몇 roadmapId가 roadmapContentId로 바뀐 거 같긴 한데 이 부분은 나중에 conflict 해결할 때 해도 될 거 같습니다!!

2023-07-22 19:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +    private static MemberProfile memberProfile;
static으로 선언한 이유가 있나요?

2023-07-22 19:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +        assertDoesNotThrow(() -> goalRoom.participate(goalRoomPendingMember));
이 테스트를 보고 든 생각인데요...
골룸이 만들어지고 처음으로 들어오는 사용자의 역할이 FOLLOWER면 잘못된 거라는 생각이 들었는데 예외처리하는 건 어떨까요?😅

2023-07-22 19:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/vo/GoalRoomNameTest.java
> +    void 골룸의_이름_길이가_1미만_40초과일_때_정상적으로_생성된다(final int length) {
여기도 네이밍 수정이 필요합니다ㅎㅎ

2023-07-22 19:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomIntegrationTest.java
> +class GoalRoomIntegrationTest extends IntegrationTest {
수고하셨습니다
양이 어질어질하네요😵😵

2023-07-22 19:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceTest.java
> +    void 골룸_생성_시_존재하지_않은_로드맵_컨텐츠의_노드사이즈와_요청의_노드사이즈가_다를때_예외를_던진다() {
'존재하지_않은'을 빼야 할 거 같아요

2023-07-23 11:13 UTC, miseongk requested changes
두둠 생성 기능 구현하느라 정말 고생하셨어요🕺
테스트 양이 정말 많네요,,,
제 생각을 남겼으니 확인해주세요!

2023-07-23 11:13 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +                () -> assertThat(예외_메시지).contains("존재하지 않는 로드맵입니다. roadmapContentId = " + 존재하지_않는_로드맵_아이디)
이 부분도 잘못 수정됐는데 수정해주세요~~

2023-07-23 11:13 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomIntegrationTest.java
와우 통합테스트 하시느라 고생하셨어요👍

2023-07-24 13:53 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +        final RoadmapContent roadmapContent = findRoadmapContent(goalRoomCreateDto.roadmapContentId());
`checkNodeSizeEqual` 말씀하시는건가요?
해당 검증 로직은 `roadmapContent`를 찾아온 후 검증이 가능한데 어떤거 말씀하시는건지 확인 부탁드립니다!

2023-07-24 13:58 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +                .collect(Collectors.toList());
`toList()`는 불변 객체를 만들어줘서 이렇게 했었는데 객체에서 방어적 복사를 하니까 `toList()`도 가능하겠네요!

2023-07-24 14:11 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +        goalRoom.participate(goalRoomPendingMember);
`makeGoalRoomPendingMember`를 보시면 `GoalRoomPendingMember`를 생성할때 이미 영속화 된 골룸을 넣어줘야 `DataIntegrityViolationException`이 발생하지 않습니다. 
이렇게 되면 `GoalRoomPendingMember`를 생성할 때, 양방향 편의 메소드인 `goalRoom.participate(goalRoomPendingMember);`를 무조건 호출해줘야합니다. 자식 부모 간의 관계에 대해 일관성을 가져야하기 때문이에요! 그렇게 되면 개발자가 `GoalRoomPendingMember`를 생성할 때 알아야하는건 2가지 입니다.
1. `GoalRoomPendingMember`를 생성할 때는 영속화된 `GoalRoom`을 받아야한다.
2. `GoalRoomPendingMember`을 생성하고 나서 양방향 편의 메소드를 꼭 호출해야한다. 

당연히 부모 생성 > 자식 생성 > 부모에 자식 추가 흐름을 생각할 수도 있다고 생각합니다만, 다르게 생각하면 부모 생성 > 부모 영속화 > 자식이 부모를 알도록 생성 > 부모에 자식 추가 느낌이라서 조금 어색하다고 느꼈습니다! 이부분은 어쩔 수 없는것 같긴하네요🥲

2023-07-24 14:21 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +    }
이 메소드는 `roadmapNodeId`를 입력으로 받아 `RoadMapContent`에서 `RoadmapNode`를 찾는 메소드 입니다..!

아래 것은 dto가 가지고있는 `goalRoomRoadmapNodeDtosSize`를 검사하는 것이라서 goalRoomNodeSize와도 조금 다른 결인것 같았습니다! 어떻게 생각하시나요??

2023-07-24 14:25 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomControllerTest.java
> +    void 골룸_생성_시_골룸_제한_인원이_null일_경우() throws Exception {
프론트 분들의 편의를 위해서 하나하나 해야한다고 생각했는데, 잘 사용하시지 않으신다고 하니 수정하겠습니다!

2023-07-24 14:34 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/helper/FieldDescriptionHelper.java
> +    }
저도 이런 제 자신이 밉네요

2023-07-24 14:40 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/AuthControllerTest.java
> +        );
그럴 수도 있겠네요! 저는 본테스트는 테스트의 역할만 하고 문서화는 따로 추상화 하는게 나을 것 같다는 생각이 들었습니다! 문서화 코드 때문에 테스트 코드의 가독성이 많이 떨어진다고 생각했어요!

2023-07-24 14:59 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +    public GoalRoom(final Long id, final GoalRoomName name, final LimitedMemberCount limitedMemberCount, final RoadmapContent roadmapContent) {
이 부분은 정말 애매한것 같네요! 제 생각에도 객체 입장에서는 필수 값인 크리에이터를 받는게 좋을 것 같아요. 근데 생성자가 생성의 책임 이외의 행동을 너무 많이하면(양방향 연관관계 메서드를 호출)하면 해당 객체 사용자 입장에서는 그냥 생성만 했는데, 예상치 못하게 연관관계가 들어갔다고 생각해서 헷갈릴 수 있는 포인트가 된다고 생각해요!
생성자가 생성에 대한 책임만 가지고, `add~`비슷한 메소드가 따로 있으면 사용자는 public api인 `add~`를 호출하면 어떤 행동을 하겠구나 유추할 수 있을 것 같은데 어떻게 생각하시나요?

2023-07-24 15:05 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +    private static MemberProfile memberProfile;
`@BeforeAll`을 사용하려면 static이어야 합니다!

2023-07-24 15:09 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
> +        assertDoesNotThrow(() -> goalRoom.participate(goalRoomPendingMember));
그럼 getter를 열어야해서.. 고민해보겠습니다!

2023-07-25 17:14 UTC, miseongk approved these changes
두둠 리뷰 반영과 새로운 요구사항 추가하시느라 고생하셨어요!!
큰 특별한 리뷰는 없는 것 같고, 오타가 여러개 보여서 그 부분 리뷰 남겼어요!

추가적으로 투두에 대한 리뷰도 확인부탁드립니다~!
저는 여기서 approve 할게요 ㅎㅎ

2023-07-26 00:18 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +        final RoadmapContent roadmapContent = findRoadmapContent(goalRoomCreateDto.roadmapContentId());
`findRoadmapContent()`가 먼저 나와서 존재 여부를 확인하고, convert 로직을 진행하는 게 어떨까라는 의견이었습니다!

2023-07-26 01:29 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomToDo.java
> +    private Period period;
투두는 골룸 생성 할 때 하나만 받기 때문에 당연히 한개를 생성합니다!
그리고 db가 투두와 노드는 연관관계가 없습니다..!

2023-07-26 02:47 UTC, Cl8D requested changes
고생하셨어요 두둠~
테스트가 정말 엄청 빡세네요...
거의 구두로 리뷰 드린 것 같아서 merge 하셔도 좋을 것 같습니다!
파이팅하세요!!

2023-07-26 02:47 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
> +    }
`updateGoalRoom()`을 사용해도 될 것 같아요! (생성자가 다양하다 보니까 혼동이 올 수 있을 것 같아서요.)

2023-07-26 02:47 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
> +    public boolean containGoalRoomPendingMember(final GoalRoomPendingMember goalRoomPendingMember) {
`add()` 메서드처럼 `contains()`로만 하더라도 충분히 의미 전달이 될 것 같습니다!

2023-07-26 02:47 UTC, Cl8D approved these changes

2023-07-26 04:58 UTC, Ohjintaek approved these changes
수고하셨습니다 두둠
중간에 인증 노드는 노드 진행 기간 날짜만큼만 올릴 수 있다는 제약에서 한 번 더 봤으면 좋겠는 부분이 있어서 코멘트 남겨드렸어요

2023-07-26 04:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNode.java
> +        if (checkCount > period.getTimeInterval()) {
여기서 getTimeInterval이 두 LocalDate 사이의 기간을 계산한 건데 사이의 기간이니까 +1을 해줘야 하지 않을까요?
예를 들어 노드 기간이 11일부터 14일이면 3이 나올 건데 사실 4일 동안 진행되는 기간이니까요. 근데 이 부분은 테스트 코드로 잘 검증해봐야 할 필요가 있을 거 같아요

2023-07-27 02:04 UTC, merged