[feat/CK-63] 로드맵 리스트와 로드맵 단일 조회를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #29
Opened 2023-07-23 06:35 UTC by evencoding

## 📌 작업 이슈 번호
https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-63

## ✨ 작업 내용
- 로드맵 목록 조회 UI 구현
- 로드맵 단일 조회 UI 구현
- 로드맵 목록, 단일 조회를 fetching하는 API 로직 구현

## 💬 리뷰어에게 남길 멘트
API 요청에 대한 응답이 아직 제가 기대했던 데이터가 아니기 때문에 Dummy 데이터가 적용되어 있습니다
ex)
<img width="398" alt="image" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/88191233/13edf3cc-6b32-4676-9da2-46c5a79ea8b4">

Mutation의 경우 use~와 같이 한번 더 추상화하여 사용할 수 있도록 해주었는데,
Query의 경우 Suspense와 ErrorBoundary가 사용된다는 가정하에, 굳이 또 한번 추상화해야할까라는 생각이 들었어요
리뷰어 분들의 의견 부탁드립니다

코드가 완벽한 상태가 아닙니다
작업의 내용이 확장됨에 따라 점점 커져서 한번 리뷰를 받고 싶다고 생각했습니다😭
 

## 🚀 요구사항 분석
- 로드맵 목록 조회 UI 구현
- 로드맵 단일 조회 UI 구현
- Dummy Data를 사용한 UI 구현
- 로드맵 목록, 단일 조회를 fetching하는 API 로직 구현

2023-07-23 09:14 UTC, sh981013s requested changes
코드 너무너무 흥미롭게 잘 봤어요!! 

확실히 노고가 느껴지더군요..! 

너무 고생하셨고 몇가지 사소한 부분만 확인 부탁드려요!~

2023-07-23 09:14 UTC, sh981013s commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  );
>Mutation의 경우 use~와 같이 한번 더 추상화하여 사용할 수 있도록 해주었는데,
>Query의 경우 Suspense와 ErrorBoundary가 사용된다는 가정하에, 굳이 또 한번 추상화해야할까라는 생각이 들었어요
>리뷰어 분들의 의견 부탁드립니다

저는 해당 상황에서 의미가 있지 않을까라고 생각했어요!
로드맵 디테일 페이지에서 필요한 쿼리문이 다른 컴포넌트에서 사용될 경우도 있고,

단일 컴포넌트가 fetching 하는 로직까지 책임을 질 필요가 있을까..? 라고 생각했었어요!

우디의 의견이 궁금쓰 합니다 😁

2023-07-23 09:14 UTC, sh981013s commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  console.log(data);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 우디의 짜증이 느껴지는군요..

이럴때는 해당 컴포넌트에서 eslint disable 옵션을 사용하는 부분이 어떨까 생각해요..!

2023-07-23 09:14 UTC, sh981013s commented on client/src/constants/roadmap/difficulty.ts
> +} as const;
호오 아이콘을 위한 친구이군요!!

좋습니다~ 😆

2023-07-23 09:14 UTC, sh981013s commented on client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
> +  console.log(data);
eslint 가 괴롭히셨군요..! 

생각을 해봤는데 차후 사용을 할 로직이기에 (현재는 더미 데이터) 남기고 싶은 마음은 이해하나,

그래도 develop-client 병합될 코드인만큼, 최대한 console 문 같은 라인은 없는게 어떨까 생각했어요..! query 문이 다 없어지는 한이 있더라도용

우디의 의견은 어떤가요?? 😁

2023-07-23 09:14 UTC, sh981013s commented on client/src/components/roadmapListPage/categories/Categories.tsx
> +const Categories = ({ setDummyCategoryId }: any) => {
의도된 any 타입의 사용일까요?? 👀

2023-07-23 09:14 UTC, sh981013s commented on client/src/components/roadmapListPage/categories/Categories.tsx
>                <S.CategoryName>{name}</S.CategoryName>
up, down category 에 따라 중복을 줄일 수 있을 것 같은데

```tsx
const Categories = ({ setDummyCategoryId }: any) => {
  const categories = Object.values(CategoriesInfo);
  const upCategories = categories.slice(0, 5);
  const downCategories = categories.slice(5);
  
  const renderCategory = (category) => (
    <S.Category key={category.id} onClick={() => setDummyCategoryId(category.id)}>
      <SVGIcon name={category.iconName} />
      <S.CategoryName>{category.name}</S.CategoryName>
    </S.Category>
  );

  return (
    <S.Categories>
      <S.CategoriesRow>
        {upCategories.map(renderCategory)}
      </S.CategoriesRow>
      <S.CategoriesRow>
        {downCategories.map(renderCategory)}
      </S.CategoriesRow>
    </S.Categories>
  );
};

```

이러한 방식은 어떠실까용?/ 😁

2023-07-23 10:52 UTC, NaveOWO requested changes
우디 정말 수고햇어요!! 파일 체인지를 보니 열심히 작업해준 것 같아서 저도 반성하고 감미다..👍
컴파운드도 야무지게 사용해줬네요!! 감사해요~!
리뷰 반영하고 다시 요청해주세용~~

2023-07-23 10:52 UTC, NaveOWO commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  );
데이터를 패칭 하는 부분을 왜 패이지 최상단에서 해줬는지 궁금해요! 저 데이터가 필요한 컴포넌트에서 해주는게 컴포넌트의 관심사를 더 잘 분리할 수 있을것 같아서요😃

그리고 삼항연산자로 데이터를 패칭했을 때, data에 undefined값이 들어온다면, data를 사용하는 쪽에서 값이 있는지 없는지 한번 더 확인해줘야하는 비효율이 생길 것 같아요!!
useParams로 값을가져올 때 원하는 값이 존재하지 않으면 페이지에 에러를 띄우거나 에러 페이지로 넘기는 훅은 생생해보는게 어떨까요!?

2023-07-24 12:37 UTC, evencoding commented on client/src/components/_common/button/Button.styles.ts
> +  cursor: pointer;
맞아용! 하지만 이 브랜치는 해당 PR이 merge되기 이전에 develop 브랜치에서 떨어져나온지라 아직 적용이 되지 않았습니다!
하지만 이미 해당 PR에서 확인한 바 있으니 제거해도 괜찮겠네요🤩

2023-07-24 12:37 UTC, evencoding commented on client/src/components/_common/button/Button.styles.ts
> +  cursor: pointer;
오우 세심한 리뷰 감사합니다 제거했습니다🤩

2023-07-24 12:45 UTC, evencoding commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  console.log(data);
호옹 너무 좋은 아이디어입니다 ㅋㅋㅋ👍

2023-07-24 12:48 UTC, evencoding commented on client/src/App.tsx
> +                  </Suspense>
그렇겠네요! 네이브의 의견에 동의합니다!
제가 실수로 Page 파일에 도메인 로직을 삽입해서 이러한 상황이 발생한 것 같습니다!
page 파일에서 적용하도록 하겠습니다!

2023-07-24 13:11 UTC, evencoding commented on client/src/components/_common/paginator/Paginator.tsx
> +const Paginator = () => {
맞아요ㅠㅠ
모바일에서는 무한 스크롤이 확정이었지만, Web View에서는 확정이 아니라서 놔뒀었습니다
이제 확정이 났으니 제거하겠습니다🤩

2023-07-24 13:16 UTC, evencoding commented on client/src/components/_common/roadmapItem/RoadmapItem.tsx
> +};
너무나도 맞는 말입니다!
아래는, 추후 실제 데이터로 바꿔치기 할 때에도 바뀌지 않을 `진짜 RoadmapItemProps`이라고 생각했어요
```ts
type RoadmapItemProps = {
  item: RoadmapItemType;
  hasBorder?: boolean;
}
```

때문에 구별하기 위해서 이와 같이 작성했습니다
다소 불필요한 구분이었을까요?

2023-07-24 13:19 UTC, evencoding commented on client/src/components/_common/roadmapItem/RoadmapItem.tsx
> +const RoadmapItem = ({ item, dummyCategoryId, hasBorder = true }: RoadmapItemProps) => {
옹 세심한 리뷰 감사합니다🥹
이전에 카테고리 필터링 기능을 흉내내기 위해서 카테고리를 선택하면 아이템들의 카테고리 아이콘이 바뀌는 것을 확인하신 적이 있을거에요🤩
그것을 구현하기 위해서 임시로 작성한 로직입니다!
불필요함으로  제거하겠습니다!

2023-07-24 13:23 UTC, evencoding commented on client/src/components/roadmapListPage/categories/Categories.tsx
> +const Categories = ({ setDummyCategoryId }: any) => {
이전에 카테고리 필터링 기능을 흉내내기 위해서 카테고리를 선택하면 아이템들의 카테고리 아이콘이 바뀌는 것을 확인하신 적이 있을거에요🤩
그것을 구현하기 위해서 임시로 작성한 로직이기 때문에 any 타입을 지정했습니다!
제거했어야 했는데 미쳐 확인하지 못했네요!
꼼꼼한 리뷰 감사합니다!!

2023-07-24 13:47 UTC, evencoding commented on client/src/components/_common/box/Box.styles.ts
> +  border-radius: 2rem;
`border-radius`는 절대적인 값으로 적용되기 때문에 부엉이의 의견에도 동의하는 바입니다
큰 사각형에 비해서 작은 사각형에서는 사각형의 전체 모양에 더 큰 영향을 미치게 되므로 상대적으로 더 둥글게 보일 수 있기 때문에 rem으로 적용했습니다

하지만 border-radius에 대해서는 px 값을 적용하기로 이전에 이야기 했었으니 rem이 적용된 부분을 모두 수정하도록 하겠습니다🤩

2023-07-24 13:57 UTC, evencoding commented on client/src/components/_common/button/Button.styles.ts
> +  border-radius: 1rem;
모두 적용했습니다!
createRoadmap폴더의 경우는 네이브가 작업했던 것이 파일 이름이 바뀌는 것으로 PR에 추가된 내용이기 때문에 제가 직접 수정하진 않았습니다
충돌을 피하기 위해서 추 후, 깃의 캐시 초기화 후 진행 할 예정입니다

2023-07-24 14:00 UTC, evencoding commented on client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
> +  console.log(data);
부엉이가 작성한 Mutation과 같이 Hook으로 빼 놓는다면 굳이 없어도 실제 사용할 때를 제외하고는 로직이 필요없으니 이러한 상황도 생기지 않겠군요🤩

2023-07-24 14:09 UTC, evencoding commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  );
이건 제 실수였습니다!
페이지 폴더에는 도메인 로직을 삽입하지 않기로 했었죠🤩
좋은 지적 감사합니다!! 따로 컴포넌트를 생성해서 패칭을 해주도록 수정했습니다!

현재 Suspense로 감싸져있기 때문에 data가 undefined인 상태(비동기 요청이 완료되지 않은 상태)라면 Fallback 컴포넌트가 렌더링 되는 것을 확인했습니다!
또한, useQuery의 enabled 속성을 부여하는 것으로 `id`가 존재할 때에만 요청을 보내고 있기 때문에, 현재는 네이브가 말씀하신 훅이 필요하다고 느껴지지 않았어요🥲

위의 패칭 로직은 추상화하도록 하겠습니다
네이브가 말씀하신 훅은 추 후에 필요성이 느껴진다면 다시 한 번 생각해보는 방향으로 가도 괜찮을까요?🥹

2023-07-24 15:01 UTC, evencoding commented on client/src/components/roadmapListPage/categories/Categories.tsx
>                <S.CategoryName>{name}</S.CategoryName>
너무 좋네요🤩
적용해 보았습니다!!

2023-07-24 15:26 UTC, evencoding commented on client/src/components/roadmapListPage/categories/Categories.tsx
> +  const downCategories = categories.slice(5);
단순 레이아웃 때문이 맞습니다
CSS로 구현할 수 있지만, 단순히 `flex-wrap: wrap;`을 사용한다면 9개가 모두 일렬로 나열되지 않을 경우, `8 / 1`, `7 / 2` 와 같이 나열되게 됩니다
이는 `5 / 4`로 나열하려는 제 의도와는 달랐어요🥹

`flex-basis`를 사용해서 제 의도와 같이 구현하는 것도 가능합니다! 하지만 이럴 경우 확실한 `break point`가 필요했어요
현재 전체 카테고리에 대해서 어떻게 처리할지(이것 또한 하나의 박스로 둬야할지) 등등에 대한 것들이 결정되지 않았기에, 이정도의 디테일은 추 후에 잡아가면 좋겠다고 생각했어요 (변할 가능성이 크다고 생각했습니다)

아래와 같이 함수를 정의해서 중복만 제거하고 추 후 CSS를 사용해서 구현하는 방향으로 가면 어떨까 생각하는데 괜찮을까요🥺
```tsx
const Categories = () => {
  const categories = Object.values(CategoriesInfo);
  const upCategories = categories.slice(0, 5);
  const downCategories = categories.slice(5);

  const renderCategory = ({ name, id, iconName }: CategoryType) => {
    return (
      <S.Category key={id}>
        <SVGIcon name={iconName} />
        <S.CategoryName>{name}</S.CategoryName>
      </S.Category>
    );
  };

  return (
    <S.Categories>
      <S.CategoriesRow>{upCategories.map(renderCategory)}</S.CategoriesRow>
      <S.CategoriesRow>{downCategories.map(renderCategory)}</S.CategoriesRow>
    </S.Categories>
  );
};
```

2023-07-24 15:34 UTC, evencoding commented on client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
> +export const ItemInfos = styled.div``;
현재 적용할 속성은 없지만, 적절한 네이밍을 사용한다면 컴포넌트의 내부에서 children들의 성격을 알려주기 위한 좋은 도구가 된다고 생각했습니다🤩
다만, 현재 적절한 네이밍이라고 생각되지는 않네요😭 제거하도록 하겠습니다!

2023-07-24 15:41 UTC, evencoding commented on client/src/components/_common/box/Box.tsx
> +const Box = ({ children }: PropsWithChildren) => {
버튼 컴포넌트는 재사용할 수 있기 때문에 보다 의미있는 컴포넌트로 수정하겠습니다🤩

단, 이 Box 컴포넌트는 RoadmapItem에 매우 종속적이고 현재 재사용할 곳이 없이 때문에 제거하도록 하겠습니다!

2023-07-24 15:44 UTC, evencoding commented on client/src/components/_common/box/Box.tsx
> +export default Box;
`재사용 할지도..?`라는 마음으로 생성하니 Box 컴포넌트 내부에서 어떻게 쓰이겠다 등 예상할 수가 없네요😭
Button 컴포넌트와는 달리 Box 컴포넌트는 RoadmapItem에 매우 종속적이고 현재 재사용할 곳이 없이 때문에 제거하도록 하겠습니다!

2023-07-25 01:43 UTC, evencoding commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  );
부엉이의 의견이 적극 동의합니다!
제가 잘 못 생각했었네요🥹

```ts
export const useSignUp = () => {
  // ...

  return {
    signUp: mutate,
  };
};
```
mutation의 경우 위와 같이 실행 함수를 내보내주는데, query의 경우 `useQuery`를 통해 바로 실행하니 불필요하다고 생각했었네요

```ts
export const useRoadmapDetail = (id: string) => {
  return useQuery([QUERY_KEYS.roadmap.list, id], () => (id ? getRoadmapById(id) : null), {
    enabled: !!id,
  });
};
```
위와 같이 추상화하면 매우 편하게 재사용이 가능할 뿐 아니라 컴포넌트의 역할 분담도 확실히 챙길 수 있겠어요🤩

2023-07-25 01:43 UTC, evencoding commented on client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
> +  );
완료 했뜹니다🤩

2023-07-25 02:39 UTC, evencoding commented on client/src/components/_common/button/Button.tsx
> +export default Button;
```ts
type ButtonProps = {
  variant: 'primary';
} & PropsWithChildren;
```
버튼에 variant prop을 추가하는 것으로 웹 페이지의 기본 버튼 스타일을 가진 버튼이라는 것을 명시함과 동시에, 확장성을 열어두었습니다!
더 좋은 의견있으시다면 공유 부탁드리겠습니다🤩

2023-07-25 04:51 UTC, sh981013s commented on client/src/components/_common/button/Button.tsx
> +export default Button;
좋습니다!!

2023-07-25 04:52 UTC, sh981013s commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  );
크으으.. 너무 좋습니다!! 👍

2023-07-25 04:53 UTC, evencoding commented on client/src/components/roadmapListPage/categories/Categories.tsx
>                <S.CategoryName>{name}</S.CategoryName>
코맨트를 깜빡했었네요! 적용했습니다🤩

2023-07-25 04:56 UTC, sh981013s approved these changes
볼륨이 꽤나 큰 이슈였는데 너무 고생하셨어요!! 머지하셔도 좋을 듯 싶습니다 😁

2023-07-25 06:05 UTC, NaveOWO commented on client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
> +  );
suspense를 고려하지 못했네요..!! 뭔가 데이터를 패칭할 때 패칭로직을 사용하면서 그 안에는 아무것도 패칭 안할꺼지롱~ 하는 플로우가 어색하다고 느꼈던 부분이었어요!! 근데 동작에는 이상이 없다니 조금 더 생각해봐도 되는 부분인 것 같아요!!

2023-07-25 06:05 UTC, NaveOWO commented on client/src/components/roadmapListPage/categories/Categories.tsx
> +  const downCategories = categories.slice(5);
이런 이유가 있을줄은 몰랐네요!! 우디 방법이 좋은 것 같아요!!

2023-07-25 06:05 UTC, NaveOWO approved these changes
우디 리뷰반영도 너무 수고하셨어요!!!

2023-07-25 08:10 UTC, merged