[feat] 로드맵 목록 필터링 조회 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #3
Opened 2023-07-13 06:39 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-18](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1/backlog?selectedIssue=CK-18)

## ✨ 작업 내용
- 로드맵 목록 조회 API 기능을 추가하였습니다.
- 카테고리 번호와 필터링 조건에 따라서 로드맵 목록이 반환됩니다.
	- 카테고리 번호를 받지 않으면 전체 로드맵을 대상으로 필터링하도록 만들었습니다!
	- 필터링 조건의 경우 이번 스프린트에서 골룸 엔티티가 없는 관계로 최신순으로만 정렬하도록 만들었습니다. 
- 페이지(page)와 한 페이지에서 받을 로드맵 개수(size)를 받아서 동적으로 페이징 처리를 진행하였습니다.
    - 추후 페이징 관련 객체 처리를 공통으로 하기 위해서 `PageResponse` 객체를 생성하였습니다.

## 💬 리뷰어에게 남길 멘트
- `RoadmapService`의 `generatePageRequestAppliedOffset()` 같은 경우 메서드명이 애매하다는 생각이 드는데, 어떤 메서드 이름이 좋을지 추천해주시면 감사드리겠습니다!
- 여기서 Offset의 경우 내부적으로 페이징 처리 시 0부터 시작해야 하는데, 클라이언트로부터 받는 값은 1부터 시작해서 해당 값을 뺀 상태로 `PageRequest`를 새롭게 생성해주었습니다. 
- 로드맵 생성이나 다른 API가 아직 없다 보니까 인수 테스트 과정에서 `Repository`를 바로 의존하고 있습니다 🥲 추후 api가 추가되면 리팩터링을 진행해야 될 것 같아요!

## 🚀 요구사항 분석
- 로드맵 목록 조회 시 1차적으로 다음과 같이 필터링이 가능하다.
	- ~~모든 로드맵에 대해서~~ / ~~특정 카테고리에 대해서~~
- 2차적으로 정렬 조건에 대해서 필터링이 가능하다.
	- ~~최신순~~ / 생성된 골룸이 많은 순 / 참여 인원이 많은 순
- ~~로드맵 아이디, 제목, 소개글, 난이도, 추천 기간, 크리에이터 정보, 카테고리 정보~~, 태그 정보, 리뷰 개수, 진행 중인 골룸의 수, 목표를 달성한 사람의 수

--> 밑줄 친 부분이 이번 스프린트에서 진행한 내용입니다 😊
리뷰 잘 부탁드립니다!

2023-07-13 07:48 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
> +    private PageResponse<RoadmapResponse> createRoadmapPageResponse() {
이 부분 메서드를 한글로 했어야 했는데... 🥲 수정하겠습니다!! ㅠ_ㅠ

2023-07-13 07:55 UTC, younghoondoodoom requested changes
고생하셨습니다 져니 👍 역시 잘 짜주시네요..

제 생각에는 `PageRequest`에 대한 offset -1 하는거를 공통으로 처리했으면 좋겠네요!
interceptor나 argumentResolver 같은 곳에서 처리 가능할 거 같은데 나중에 얘기해보시죠.
아니면 Spring의 PageRequest말고 저희 어플리케이션용 사용하는 PageRequest를 만들어서 Spring의 PageRequest를 넣으면 -1을 자동으로 해주는 방법도 좋을 것 같네요!

제 생각을 코멘트로 남겼는데 참고 부탁드립니다🙇‍♂️

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
> +@Getter
필요한 필드에 대한 Getter만 여는게 좋지 않을까요??

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
> +@Getter
이것도 필요한 Getter만 여는게 좋아보여요!

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
> +    }
위에는 생성자 chain을 사용했는데 여기는 사용하지 않으신거 같아요!

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfileImage.java
> +    }
이것도

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +@Getter
이것도 필요한 Getter만 여는게 좋지 않나요??

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +        if (content.getRoadmap() != this) {
이 부분은 RoadmapContent한테 물어볼 수 있을 것 같아요
```java
content.isSameRoadmap(roadmap)
```

그리고 동일성 비교보다는 equals&hashcode를 구현해서 동등성 비교를 하신 이유가 있으신가요??

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +            this.roadmap.getContents().remove(this);
이 부분도 roadmap한테 위임하면 좋을 것 같아요
```java
roadmap.removeContent(this)
```

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +            roadmap.getContents().add(this);
이 부분들도 roadmap한테 위임할 수 있을 것 같습니다!

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/RoadmapQueryRepository.java
> +    Page<Roadmap> getRoadmapPagesByCond(final RoadmapCategory category, final RoadmapOrderType orderType,
findBy를 사용하지 않으신 이유가 있나요?

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +    public PageResponse<RoadmapResponse> getRoadmapsByFilterType(final Long categoryId,
getter 같은 느낌이 있어서 find 같은 표현은 어떤가요? 그리고 roadmap이라는 단어는 service에도 포함되어있어서 빼도 자연스러울 것 같아요!

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
> +        }
예외 변환 편안하네요

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
> +                jsonPath("$.data[1].category.name").value("IT"))
응답 json 값을 String으로 변환하고 객체로 바꾸어서 usingRecursiveComparison 같은거 쓰면 좋을 것 같네요!

2023-07-13 07:55 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +    }
사용하지 않는 생성자 같아요

2023-07-13 11:04 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
> +    }
여기는 생성자가 한 개여서 체이닝을 사용하지 않았습니다!
추후 생성자가 여러 개가 되었을 때 체이닝을 사용하도록 하겠습니다 😊

2023-07-13 11:06 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/RoadmapQueryRepository.java
> +    Page<Roadmap> getRoadmapPagesByCond(final RoadmapCategory category, final RoadmapOrderType orderType,
딱히 없는데...! findBy로 수정하도록 하겠습니다! ㅎㅎ

2023-07-13 12:03 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +        if (content.getRoadmap() != this) {
쓰읍... 반대가 아닐까요?...

2023-07-14 01:54 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +@RequiredArgsConstructor
final 키워드가 붙어 있는 필드들에 대해서 생성자를 만들어줘요! 
모든 필드에 대한 생성자를 만들어주는 `@AllArgsConstructor` 어노테이션과, 빈 생성자를 만들어주는 `@NoArgsConstructor`도 있습니다! (access 레벨을 잘 지정해줘서 private, protected, public 생성자를 자유롭게 만들 수 있어요 ㅎ_ㅎ)

2023-07-14 02:49 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +    public void updateRoadmap(final Roadmap roadmap) {
양방향 연관관계 때문에 만든 메서드이긴 한데... 뭔가 명시적으로 setter를 쓰기에는 또 애매해서 우선은 이렇게 해두었어요!
다른 방향으로 바꾸는 게 좋을까요?

2023-07-14 03:02 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/RoadmapQueryRepositoryImpl.java
> +        if (category == null) {
null이라는 것은 객체가 애초에 생성이 되어 있는지 체크하는 것이니까 ==을 통해서 동일성 비교를 통해서 주소값을 비교해줘도 충분한다고 생각을 했어요. 객체가 생성되지 않았음 = 객체의 주소값이 없음 이런 느낌이니까요!

2023-07-14 03:05 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +@Transactional(readOnly = true)
저는 클래스 레벨에 `@Transactional(readOnly=true)`을 붙이고, 메서드 레벨에서 CUD 연산이 필요할 때 `@Transactional`을 붙이는 편이에요! (R 연산이 필요할 때는 아예 안 붙이구요!) 클래스 레벨보다 메서드 레벨에서 적용한 게 우선 적용되기 때문에 괜찮지 않을까요?

2023-07-14 03:07 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
> +                    .contextPath(API_PREFIX))
Rest Docs를 위해서는 `documentationResultHandler.document` 이쪽에 적는 값이구, 거기서 적은 param의 경우 mockMvc에서 `MockHttpServletRequestBuilder`을 통해서 요청에 대한 정보를 지정해주는 거예요! ㅎㅎㅎ

2023-07-14 04:11 UTC, Cl8D commented
- 스프링에서 제공하는 페이징 인터페이스 대신, 컨트롤러에서 받을 커스텀 페이지 객체를 추가하였습니다!
- Test에서 사용하기 위한 ObjectMapper에 대해 Config 클래스를 추가하였습니다. (Java Time Module 적용)
위 리뷰까지 피드백 완료했어요, 변경된 부분이 조금 생겨서 다들 확인 부탁드립니다! 😊

2023-07-14 04:21 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +@Transactional(readOnly = true)
그렇게 해도 되네요😊 좋습니다!!

2023-07-14 04:35 UTC, Ohjintaek approved these changes

2023-07-14 07:10 UTC, miseongk requested changes
져니 고생하셨어요👍
querydsl 부분은 제가 공부가 필요한 부분이라 제대로 못봤어요,, 조만간 공부 해오겠습니당
리뷰가 별거 없긴한데 그래도 확인해주시고 알려주세요! 그때 바로 approve 할게요!

2023-07-15 05:09 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +            .get("/api/roadmaps?page=1&size=10&filterType=LATEST&categoryId=" + travelCategory.getId())
앗 사실 그부분은 고민인 게, 현재는 필터 조건이 최신순밖에 없지만 필터 조건이 더 추가된다면 이에 대해서 다 검증하는 게 오히려 테스트 비용이 너무 크지 않을까 고민이 되었어요 🥲
하지만, URI에 따라서 요청이 잘 오는지도 검증하는 것도 좋은 것 같아서, filterType만 보낼 때 / category만 보낼 때 / 둘 다 보낼 때 / 둘 다 보내지 않을 때 정도는 추가해두겠습니다!

2023-07-15 05:56 UTC, Cl8D commented
- 여기까지 리뷰 반영 완료하였습니다!
- `@DirtiesContext`와 `@TestConstructor(autowireMode = AutowireMode.ALL)`을 함께 사용할 경우 오류가 발생하는 문제가 있어서, 인수 테스트 쪽은 빈 주입 시 `@Autowired`를 활용하였습니다. 추후 인수 테스트 쪽은 빈 주입을 받아서 처리하는 로직 대신에 api 요청을 통해 검증할 수 있기 때문에 이 부분은 이번 주 스프린트 종료 후 리팩터링 진행할게요! 😊

2023-07-15 06:26 UTC, younghoondoodoom approved these changes
리뷰 잘 반영해주셨네요! 고생하셨습니다 져니💪

2023-07-15 08:25 UTC, miseongk approved these changes
고생하셨어요!!👍

2023-07-15 10:35 UTC, merged