Feature/ck 22
woowacourse-teams/2023-co-kirikiri pull request #30
Opened 2023-07-23 20:48 UTC by Ohjintaek

## 📌 작업 이슈 번호
[CK-22](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-22)

## ✨ 작업 내용
- 사용자가 자신이 참여한 골룸의 목록을 조회할 수 있는 기능을 만들었습니다.
  -  골룸의 현재 상태(모집중, 진행중, 완료)도 같이 반환합니다.
- 사용자가 자신이 참여한 골룸 페이지를 조회할 수 있는 기능을 만들었습니다. 

## 💬 리뷰어에게 남길 멘트
- 일단 너무 늦어서 죄송합니다. 예상한 시간보다 2배는 더 걸리는 거 같네요. Querydsl을 잘 모르지만 여러 테이블을 조인해서 가져와야 하는 경우가 생겨서 사용해보았습니다. 동적으로 구현하는 데 도움을 받았다기 보다 빌더형으로 쿼리를 짜는 게 편한 거 같습니다. 일단 '이러면 되겠지'하는 마음으로 작성한 거라 그 부분을 유심히 봐주시면 감사하겠습니다.
- 현재 GoalRoomMember 테이블은 전혀 신경 쓰지 않고 GoalRoomPendingMember만 있다고 가정하고 작성했기 때문에 나중에 추가해야 할 코드들이 좀 있습니다. GoalRoomPendingMember에서 GoalRoomMember로 데이터를 이관하는 부분은 다 같이 상의했으면 좋을 거 같아요.
- 골룸이 어느 로드맵에서 생성되었는지를 알기 위해 GoalRoomService에서 RoadmapRepository에 직접 접근하고 있는데 괜찮겠죠? 만들 때는 괜찮은가 싶다가도 지금 생각하니 갑자기 크게 상관없는 거 같기도 하네요. 어떻게 생각하시는지 알려주시면 좋을 거 같아요.
- 골룸 단일 조회와 목록 조회에 사용한 DTO를 밀리와 져니가 만든 것과 최대한 호환되도록 만들었는데 나중에 프론트엔드와 상의 후 좀 바뀔 가능성도 있어요

## 🚀 요구사항 분석
- 사용자 골룸 조회 API
- [x] 자신이 참여한 골룸 목록을 볼 수 있다.
    - [x] 골룸의 상태에 따라 조회할 수 있다.
- [x] 자신이 참여한 골룸의 단일 조회 페이지를 볼 수 있다.

2023-07-25 08:21 UTC, Cl8D requested changes
고생하셨어요 썬샷!
사용자의 골룸 조회 시 기존에 있는 response 값을 사용하는 것보다 아예 내려가야 하는 정보가 달라질 것 같아서, 프론트분들이랑 대화 나눠보고 변경되어야 할 부분이 많을 것 같아요!
그리고 controller에 대해서 개인적인 의견을 담아봤는데 보시구 참고 부탁드립니다!

2023-07-25 08:21 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomService.java
> +    private final RoadmapRepository roadmapRepository;
> 골룸이 어느 로드맵에서 생성되었는지를 알기 위해 GoalRoomService에서 RoadmapRepository에 직접 접근하고 있는데 괜찮겠죠? 만들 때는 괜찮은가 싶다가도 지금 생각하니 갑자기 크게 상관없는 거 같기도 하네요. 어떻게 생각하시는지 알려주시면 좋을 거 같아요.

저는 서비스에서 하위 레파지토리끼리 연관관계를 가지는 게 좋다고 생각해서 지금 구조 좋아요!

2023-07-25 08:21 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceTest.java
> +        goalRoom.updateStatus(GoalRoomStatus.RECRUITING);
골룸에서 아마 초기값이 RECRUITING이어서 따로 설정해주지 않아도 될 것 같아요!

2023-07-31 04:37 UTC, Ohjintaek commented
인증 피드 조회 시에 같이 구현해서 이 PR은 닫겠습니다

2023-07-31 04:37 UTC, closed without merging