[feat/CK-64] 로드맵 태그 생성 기능을 추가한다
woowacourse-teams/2023-co-kirikiri pull request #37
Opened 2023-07-26 10:05 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-64](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-64)

## ✨ 작업 내용
- 로드맵 생성 시 태그 정보를 함께 받아오도록 추가하였습니다.
- 로드맵 단일 조회 시 태그 정보도 함께 반환하도록 수정하였습니다.
- 로드맵 목록 조회 시 태그 정보를 반환하고 + 기존의 페이징 쿼리를 무한스크롤로 변경하였습니다.

## 💬 리뷰어에게 남길 멘트
- 크게 추가한 부분이 없어서 아마 금방 보시지 않을까 싶습니다!
- 무한 스크롤 과정에서 no-offset 전략을 선택하면서 가장 마지막으로 조회한 로드맵의 pk 값을 받아오도록 수정하였습니다!
- 기존의 PageRequest dto는 우선 남겨두었는데, 나중에 완전히 무한스크롤로 변경이 되면 그때 삭제하지 않을까 싶습니다!

## 🚀 요구사항 분석
- 로드맵 생성 시 태그는 최소 0개, 최대 5개까지 달 수 있다.
- 로드맵 태그의 이름은 최소 1글자, 최대 10글자이다.
- 로드맵 태그의 이름은 중복될 수 없다.

2023-07-28 02:41 UTC, younghoondoodoom requested changes
고생하셨습니다 져니~! 기능 구현과 테스트는 잘 된것 같아요! 
태그는 nullable로 알고 있는데, 이 부분에 대한 처리에 대해서 생각해보면 좋을 것 같아요! 
추가로 제 생각 남겼으니 참고 부탁드립니다🙇‍♂️

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapTags.java
> +    private final List<RoadmapTag> values = new ArrayList<>();
중복은 허용하지 않은 제약 조건이 있고, 순서가 중요하지 않으니 자료구조를 Set으로 하시는건 어떤가요?

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapTags.java
> +    }
방복

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +    }
`addTags`라는 의미와 맞게 set이 아닌 add가 되었으면 좋겠네요!
```java
public void addTags(final RoadmapTags tags) {
       this.tags.addAll(tags)
}
```

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
아래에 
```java
private OrderSpecifier<?> sortCond(final RoadmapFilterType orderType) {
        return roadmap.id.desc();
    }
```
이 부분은 파라미터 orderType을 사용하지 않고있네요. 미리 분기 처리를 해두시는게 재사용하기 편할 것 같아요!

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +                        lessThanRoadmapId(lastRoadmapId),
가장 마지막 로드맵 id를 받아서 그 전에 있는 로드맵들을 가져오는 조건 같은데 이게 왜 필요한지 궁금합니다!
만약 생성 순서 때문에 그렇다면 createdAt 같은 것을 정의해서 사용하는게 낫지 않나요?

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +        roadmap.addTags(roadmapTags);
아래의 `makeRoadmapTags`에서 .toList()로 인해 불변 객체가 생성 되고 있습니다! 
그리고 `roadmap.addTags()`는 tags 필드를 set 하고 있어서 `roadmapTags`는 불변 객체를 사용하게 됩니다! 
addTags에서 방어적 복사를 통해서 기존 List에 add 해주도록 수정하면 여기 코드는 수정할 건 없지만 조심해야할 포인트인 것 같습니다

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/request/RoadmapSaveRequest.java
> +        List<@Valid RoadmapNodeSaveRequest> roadmapNodes,
타입에 넣어줘도 동작하는군요..!

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapTags.java
> +    @JoinColumn(name = "roadmap_id", updatable = false, nullable = false)
단방향 `@OneToMany`라서 `nullabe = false`를 붙히셨는데 저희 태그는 null 허용 아닌가요?

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
로드맵이 설정되지 않은 경우도 테스트 했으면 좋겠어요!

2023-07-28 02:41 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
테스트가 굉장히 많네요.. 고생하셨습니당

2023-07-28 02:54 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapTagSaveDto.java
> +        String name
엇 `@NotEmpty`면 무조건 태그를 작성해야 하지 않나요?
태그의 경우 필수적으로 들어갈 필요가 없는 인자여서 별도로 제약 조건을 설정하지 않았습니다!

2023-07-28 02:57 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
분기 처리를 하려면 어떤 정렬 조건으로 해야 할지 명시를 해줘야 하는데, 나중에 구현할 때 넣어주는 게 좋을 것 같아서 따로 지정하지 않았습니다! (어차피 디폴트가 최신순이어서 현재는 최신순으로만 내려가는 게 배포 시에 오류가 덜 발생할 것 같아요.)

2023-07-28 02:58 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapTags.java
> +    @JoinColumn(name = "roadmap_id", updatable = false, nullable = false)
roadmap_tags 테이블에 존재하는 데이터에 대해서는 모두 roadmap_id를 가지고 있어야 하기 때문에 nullable을 지정해줘야 합니다! 태그 자체는 null이 허용이겠지만 없는 태그는 테이블에 들어가지 않을 테니까요!

2023-07-28 03:00 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
혹시 로드맵이 설정되지 않은 경우가 어떤 경우일까요??...

2023-07-28 03:05 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +                        lessThanRoadmapId(lastRoadmapId),
no-offset 방식으로 구현하기 위해서 추가한 조건입니다!
사실 이 부분은 그 다음 PR인 CK-67에서 좀 수정된 부분이라 ㅠ 언급을 드렸어야 했는데 빠뜨렸네요.

offset 방식의 경우 클라이언트가 첫 번째 요청 이후 두 번째 요청을 할 때 첫 번째 요청에서 포함된 부분도 전부 메모리로 가져와서 원하는만큼만 끊어서 반환하다 보니 성능적으로 이슈가 있는데요!
현재 디폴트 조회가 최신순이다 보니까 id를 기준으로 정렬하게 되고, 클라이언트가 반환받은 아이디 리스트 중에서 가장 작은 값을 가져와서해당 값 이전의 값들을 바로 검색해서 offset으로 인한 문제점을 해결하기 위해 적용한 것입니다!
다만 변수명이 적합하지 않아서 다음 PR에서는 `lastValue`로 이름을 수정하기는 했습니다!

2023-07-28 03:09 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
아아 태그..

2023-07-28 03:09 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapTags.java
> +    @JoinColumn(name = "roadmap_id", updatable = false, nullable = false)
제가 착각했네요!

2023-07-28 04:38 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
추가해두었습니다~

2023-08-01 06:18 UTC, younghoondoodoom approved these changes
고생하셨습니다 져니~! Approve 할게요~!

2023-08-01 13:48 UTC, merged