[feat/CK-67] 로드맵 검색 기능을 추가한다
woowacourse-teams/2023-co-kirikiri pull request #40
Opened 2023-07-27 17:02 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-67](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-67)

## ✨ 작업 내용
- feature/CK-64로부터 분기해서 작업하였습니다. 커밋이 중복된 것들이 있어서 실제로는 `640ba90` 커밋부터 보시면 돼요! (feat: 로드맵 동적 검색 쿼리 추가)
- 로드맵 검색 기능을 추가하였습니다.
- 제목, 크리에이터, 태그 정보에 대해서 검색이 가능하며 다중 검색이 불가능합니다. (제목 + 크리에이터 동시 검색 X)
- 무한스크롤로 구현하였으며, 필터링도 함께 적용할 수 있도록 만들었습니다. (현재는 최신순만 가능)

## 💬 리뷰어에게 남길 멘트
- RoadmapSearchDto에서 title 값이 비어서 오면 검색 키워드에 대한 검증 로직이 탈 필요가 없으니까 null 값을 전달해주는데, 이를 서비스에 두기에는 안 울려서  RoadmapSearchDto에서 책임을 가지도록 하려고 했어요.
	- 하지만 레코드의 생성자 레벨을 조절하고 싶었는데, 해당 기능은 따로 없는 것 같더라구요… 
	- 그래서 **record 대신에 차라리 class를 쓰는 게 더 어울릴 것 같아서** 그렇게 만들었는데, 좋은 의견 있으시면 공유 부탁드립니다!
- no-offset 전략 관련해서 고민하다가, 한 가지 고민되는 게 생겨서 공유드립니다!
- 현재는 최신순으로만 정렬해서 상관없지만 다른 순서로 정렬하게 되면 id 기준으로 정렬이 안 되잖아요…?! 그래서 lessThanRoadmapId() 같은 메서드가 적용이 안 될 것 같다는 생각이 들어서 (id를 기준으로 판단하는 거니까) 우선 TODO 처리만 해두었습니다.
	- 예를 들어 골룸 개수순이 정렬 조건이라면(필터링) 마지막 요청으로 받은 골룸 개수중에 가장 작은 값을 보내야 쿼리상으로 처리가 가능하겠죠? 그래서 **기존의 lastId라는 쿼리 파라미터를 lastValue로 수정**하였습니다.

## 🚀 요구사항 분석
1. 로드맵은 제목 / 태그 / 크리에이터로 검색할 수 있다.
2. 다중 검색은 불가능하고, 각각에 대해 1개씩 검색이 가능하다. 
3. 제목 / 태그 검색
    - 검색어에 공백이 있으면 제거한다.
    - 검색어는 최소 1글자부터 가능하다.
    - 검색 대상의 공백을 신경쓰지 않고 검색이 가능하도록 만든다.
4. 검색 결과는 무한스크롤로 반환한다.
5. 검색에 대해서 정렬 조건을 적용할 수 있다.

2023-08-01 02:45 UTC, younghoondoodoom requested changes
고생하셨습니다 져니~! 테스트가 상당히 많네요.. 정말 고생하셨습니다🙌

> no-offset 전략 관련해서 고민하다가, 한 가지 고민되는 게 생겨서 공유드립니다!
현재는 최신순으로만 정렬해서 상관없지만 다른 순서로 정렬하게 되면 id 기준으로 정렬이 안 되잖아요…?! 그래서 lessThanRoadmapId() 같은 메서드가 적용이 안 될 것 같다는 생각이 들어서 (id를 기준으로 판단하는 거니까) 우선 TODO 처리만 해두었습니다.
예를 들어 골룸 개수순이 정렬 조건이라면(필터링) 마지막 요청으로 받은 골룸 개수중에 가장 작은 값을 보내야 쿼리상으로 처리가 가능하겠죠? 그래서 기존의 lastId라는 쿼리 파라미터를 lastValue로 수정하였습니다.

일단 리뷰에서 말씀드렸던 것처럼 id를 기준으로 최신순을 검색하는 것이 조금 어색합니다. 저는 이 부분을 created_at으로 수정 했으면합니다.
그렇다면 `lastValue`가 `LocalDateTime`이 됩니다. 만약 `reviewRate`로 정렬을 하면 `double`형을 받겠죠? `lastValue`를 활용하기 어려워질 것 같습니다!

각 정렬 조건에 대해 dto를 만들거나(만약 해당 dto가 null이면 그 조건은 안타게 설정) `lastValue`에 generic type을 이용할 수 있을 것 같습니다(형변환을 해야할 것 같긴하네요)!

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
> 그래서 record 대신에 차라리 class를 쓰는 게 더 어울릴 것 같아서 그렇게 만들었는데, 좋은 의견 있으시면 공유 부탁드립니다!

그냥 record를 이용해서 canonical constructor를 이용해도 되지않나요? 파라미터에 null이 들어오면 해당 필드에 null을 넣어주는 것이 지금 정팩메의 역할인 것 같은데, 그냥 그대로 넣어줄거라면 바로 넣어줘도 될 것 같습니다! 그리고 RoadmapSearchTitle 같은 값들도 외부에서 생성해서 넣어준다면 검증 로직을 탈 일이 없을 것 같습니다.
다른 이유로 정팩메를 이용하신거라면 설명 부탁드립니다!

```java
public record RoadmapSearchDto(

        RoadmapSearchTitle title,
        Long creatorId,
        RoadmapSearchTagName tagName
) {
}
```

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchTagName.java
이것도 이렇게 record를 활용해서 바꿀 수도..?
```java
public record RoadmapSearchTagName(
        String value
) {

    private static final int MIN_LENGTH = 1;


    public RoadmapSearchTagName {
        final String name = removeBlank(value);
        validateLength(name);
    }

    private String removeBlank(final String name) {
        return name.replaceAll(" ", "");
    }

    private void validateLength(final String name) {
        if (name.length() < MIN_LENGTH) {
            throw new BadRequestException(
                    String.format("검색어는 최소 %d자부터 가능합니다.", MIN_LENGTH));
        }
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final RoadmapSearchTagName that = (RoadmapSearchTagName) o;
        return Objects.equals(value, that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }
}
```

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchTitle.java
이것도 record를 사용할 수 있을 것 같습니다!

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomScrollRequest.java
> +        int size
이 값들에 validation을 적용해도 좋을 것 같아요!

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodesTest.java
> +                LocalDate.of(2023, 7, 25), 10, new RoadmapNode("로드맵 제목 1", "로드맵 내용 1"));
제 코드에서 `GoalRoomRoadmapNode`가 만들어질때 오늘 이전인 `LocalDate`가 설정이 되면 오류가 납니다! 계속 테스트가 돌 수 있게 `LocalDate.now()`를 활용하는 건 어떨까요?

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
> +}
인수 테스트가 상당히 깔끔하네요👍

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
> +    void 정상적으로_생성한다() {
무엇이 정상적으로 생성되는지 적어주시면 좋을 것 같네요!

2023-08-01 02:45 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
그리고 동시 검색이 허용되지 않으려는 조건을 넣으려면 canonical constructor에서 validation을 진행할 수 있을 것 같아요!

2023-08-01 04:02 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +        return roadmap.id.lt(lastValue);
> 각 정렬 조건에 대해 dto를 만들거나(만약 해당 dto가 null이면 그 조건은 안타게 설정) lastValue에 generic type을 이용할 수 있을 것 같습니다(형변환을 해야할 것 같긴하네요)!

형변환보다는 조건마다 dto를 만드는 게 더 어울릴 것 같다는 생각이 드네요!! dto를 만드는 방향으로 수정해보겠습니다.
그리고 createdAt순으로 정렬하도록 수정하겠습니다! 😊

2023-08-01 04:22 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
> +    List<Roadmap> searchRoadmaps(final RoadmapFilterType orderType,
오버로딩을 사용하면 테스트에서 캐스팅이 필요한데 요런 코드 괜찮으실까요?
```java
when(roadmapRepository.findRoadmapsByCond((RoadmapCategory) any(), any(), any(), anyInt()))
                .thenReturn(roadmaps);
```

2023-08-01 04:41 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
record를 사용하지 않은 이유는 record는 항상 모든 인자에 대한 생성자가 열려있다는 점입니다.
저는 정팩메를 통해서만 객체를 생성하고 싶은데 레코드에 대해서는 항상 모든 인자를 받아 객체를 생성할 수 있다 보니 다른 개발자 입장으로서는 잘 모르고 혼용할 수 있을 것 같아 레코드 대신에 클래스를 사용했습니다!

2023-08-01 04:45 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
동시 검색의 경우 validation까지 걸 필요가 있을까? 라는 생각도 들었습니다!
현 스펙상 검색 자체는 가능하지만 클라이언트에서 클릭 이벤트 자체를 막으면 되는 것이고, 악성 사용자가 검색을 한다고 해서 검증되지 않는 결과값을 반환받을 뿐이지, 잘못된 예외 사항으로 내려갈 필요는 없다고 생각해서 검증하는 로직을 추가하지는 않았습니다.
두둠은 동시 검색을 하는 시도 자체를 잘못된 예외 사항으로 보는 게 조금 더 적합하다고 생각하시나요?! 궁금합니다!

2023-08-01 06:21 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
> +    List<Roadmap> searchRoadmaps(final RoadmapFilterType orderType,
오 변수명 좋아요! 별개로 테스트에서 캐스팅 대신 다음과 같이 사용할 수 있을것 같아요!
```java
when(roadmapRepository.findRoadmapsByCond(any(RoadmapCategory.class), any(), any(), anyInt()))
                .thenReturn(roadmaps);
```

2023-08-02 06:32 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodesTest.java
> +                LocalDate.of(2023, 7, 25), 10, new RoadmapNode("로드맵 제목 1", "로드맵 내용 1"));
아마 이부분은 develop 올라가면 수정이 되어 있을 것 같아서...! (제가 한 작업 범위가 아닌지라 ㅠ)
우선은 넘어가겠습니다!!

2023-08-02 06:51 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomScrollRequest.java
> +        int size
size에 대해서는 validation을 적용해두겠습니다!

2023-08-02 08:04 UTC, Cl8D commented
여기까지 리뷰 반영 완료했습니다! 🙇‍♀️🙇‍♀️

2023-08-02 08:29 UTC, younghoondoodoom approved these changes
고생하셨습니다 져니~! Approve 할게요! 
토스 합격 축하드려요💵

2023-08-02 08:29 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
클라이언트가 이벤트 자체를 막더라도 서버는 그런 경우도 막아야한다고 생각합니다. 클라이언트에 의존하는 것처럼 되니까요!
근데 이 경우에는 레코드의 생성자에서 `CustomScrollRequest`을 받지못하니 dto를 사용하는게 좋을 것 같아요!

2023-08-02 11:09 UTC, merged