[feat/CK-75] 인증 피드 추가 API를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #41
Opened 2023-07-29 20:32 UTC by Ohjintaek

## 📌 작업 이슈 번호

[CK-75](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-75)

## ✨ 작업 내용
- 골룸 참여자가 인증 피드를 등록할 수 있는 API를 구현했습니다.
- 사용자가 등록한 이미지를 서버가 존재하는 파일 시스템에 저장합니다(실제 서버에 배포할 때도 저장 경로를 수정해야 되고 추후 S3 사용할 때도 경로 변경해야 되서 변동성이 높습니다)
- 인증 피드 등록 시 골룸 참여자의 달성률을 업데이트하는 기능을 추가했습니다.
- 나중에 사용자 골룸 단일 조회를 위해 골룸의 특정 노드에 등록된 인증 피드만 조회하는 기능을 추가했습니다.

## 💬 리뷰어에게 남길 멘트
- **(중요)** 현재 사용자가 등록한 이미지의 저장 경로가 스프링 부트가 동작하는 환경의 C 드라이브("C://")입니다. 테스트에서 Mock 이미지를 사용하는데 진행하면서 실제로 해당 경로에 파일이 생성됩니다. 테스트 내에 생성된 파일을 삭제하는 코드도 추가했는데 혹시 불안하시면 테스트 코드를 실제로 돌리지 않는 걸 추천드립니다.
- 원래 골룸 참가 API와 골룸 시작 기능이 분기 되기 전에 뻗어나온 branch지만 테스트를 좀 더 수월하게 하기 위해 미리 코드에 추가했습니다. 골룸 참가 기능과 시작 기능에 대해서는 코멘트 해주셔도 되고 안 해주셔도 됩니다. 이번 기능 구현하면서 실질적으로 추가된 부분은 `Domain`들과 `GoalRoomController`, `GoalRoomCreateService`, 그 외 골룸과 관련된 부분이라 그 부분을 중점적으로 봐 주시면 감사하겠습니다.
- 파일을 전달하고 처리하는 데에 시간을 많이 잡아먹었는데 제대로 될지 불안하네요. 테스트 하기도 좀 제한적이어서 불안한 부분이 있습니다. 특히 로컬에서 돌릴 때, 배포 서버에서 빌드 파일로 돌릴 때 등 환경에 따라 저장 경로를 어떻게 처리할 지 감이 안 잡혀서 혹시 좋은 방법 있으면 가르쳐주시면 감사하겠습니다.
- 인증 피드 조회 기능은 원래 따로 이슈가 있었는데 아직 해결되지 않은 이슈인 `사용자 골룸 단일 조회 API`에 추가할 예정이라 거기에 필요한 메서드만 간단히 작성하면 끝날 거 같아 같이 했습니다. 그 메서드를 검증하기 위해 통합 테스트에서 직접 Repository에 접근하는 불편한 부분이 있는데 나중에 수정하겠습니다.

## 🚀 요구사항 분석

### 인증 피드 추가 API

- [x] 인증 피드 추가 API 구현
    - [x] 인증용 사진(필수), 인증글(옵션)을 전달한다
    - [x] 인증피드 추가 요청은 하루에 한 번만 보낼 수 있다 (정해야 될 사항 : 시간을 언제를 기준으로 할지(**00시** or 04시))
    - [x] 노드 기간 동안 정해진 횟수만큼만 인증 피드 추가 요청을 보낼 수 있다.
- [ ] 이미지는 서버에 파일 시스템에 저장하고 db에는 해당 파일의 경로를 저장한다
- [x] 인증 피드 추가 시 해당 멤버의 달성률을 계산하고 db에 업데이트한다 (GoalRoomMember)

### 인증 피드 조회 기능 

- [x] 골룸의 인증 피드 조회 기능 구현
    - [x] 골룸 내의 현재 진행 중인 노드에서 등록된 피드만 전달한다

2023-07-30 04:40 UTC, Cl8D requested changes
고생하셨어요 썬샷! 👍
테스트 케이스가 정말 세세하게 잘 작성되어 있어서 너무 좋았어요 ㅎㅎ
다만 OS 환경의 차이로 인해서 저 같은 경우는 테스트 코드가 돌아가지 않는답니다 🥲
테스트는 어디서든 잘 동작해야 하고, 아마 이렇게 되면 CI 시에 오류가 발생할 것 같아요!
<img width="817" alt="스크린샷 2023-07-30 오후 1 39 01" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/46810837/60c85ce8-42a3-45fb-afdd-b231a00e06e2">
아무래도 윈도우랑 맥 환경 사이의 차이 때문이 아닐까 싶습니다 ㅎㅎ

1. `GoalRoomCreateServiceTest`에서 파일 업로드를 실제로 진행하고 있다는 점 (파일 업로드를 별도의 클래스로 위임한다면 여기서는 오류가 발생하지 않겠네요!)
2. E2E 테스트 과정에서 실제로 업로드를 진행하며 발생하는 오류

테스트 환경에서는 C:/ 같은 윈도우용 확장자를 사용하지 않도록 프로퍼티 파일을 잘 정의하면 해결할 수 있을 것 같아요. 한 번 같이 고민해봐요!! 💪

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +        final String uploadFilePath = "C:/";
현재는 인스턴스 내부에 저장되는 로직을 만드셨네요!
제 기억에도 윈도우 파일 시스템에서는 파일 업로드 로직을 구현할 때 C:/ 같은 path를 넣어줘야 됐던 것 같아요.
하지만 OS 환경이 다른 협업자, 혹은 실제 개발 서버로 배포되었을 때는 잘 동작하지 않게 되겠죠?
(현재는 최상단 경로에 저장되겠지만 실제로 인스턴스에서는 정적 파일을 위한 패키지를 만들어서 저장해두고, 특정 endpoint가 prefix로 붙어있을 때 nginx에서 해당 정적 파일 리소스가 존재하는 부분으로 서빙해주도록 만들 수도 있겠네요!)

보통 이런 기본 파일 path의 경우 프로퍼티 클래스로 분류해서 yml 같은 곳에 정의해두고 사용하는 게 좋을 것 같아요.
어떤 profile인지에 따라 (로컬, dev, prod...) 다른 프로퍼티 값을 가져오도록 해도 좋을 것 같구요.

사실 파일 업로드 처리는 어떤 클라우드 서비스 or 어떤 식으로 처리하는지에 따라서 로직이 확연하게 달라지는 부분이라 어렵네요 ㅎㅎ 
만약 s3를 사용하게 된다면 굳이 로컬에 저장하는 것이 없더라도 MultipartFile의 InputStream 값을 활용해서 바로 업로드도 가능할 거예요. (아마도... 제 기억으로는 그러네요 ㅋㅋㅋ)  우선 이건 다른 팀원분들도 다 알아야 하는 로직인 것 같아서, 월요일에 다 같이 이야기 해보면 좋을 것 같아요 😊

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +        final String fileName = System.currentTimeMillis() + "_" + checkFeedImage.getOriginalFilename();
랜덤하게 생성되는 파일 이름의 경우 테스트 시 용이하게 진행하기 위해서 `FileNameGenerator` 같은 인터페이스를 활용해서 처리하는 게 좋을 것 같아요!

추가적으로 파일을 저장할 때 추후 개발자가 직접 확인하거나 배치 처리 등으로 삭제 처리를 하기 위해서는 디렉터리 구조로 저장되는 게 좋을 것 같아요.
ex) {yyyy}/{mmdd}/{goalRoomId}/filename.ext -> 2023/0730/1/aaa.png 이런 식으로요!

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +            updateAccomplishmentRate(goalRoom, goalRoomMember);
달성률에 대한 부분은 try 구문 외부에 있어도 될 것 같아요 😊

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
> +                        documentationResultHandler.document(
description에 대한 정보가 빠져있네요!

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
> +
snippet 재정의 👍👍👍

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        final String imageUrl = 인증_피드_등록_응답.response().header("Location");
별건 아니지만 여기 변수가 영어로 쓰여있어요! ㅎㅎㅎ

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +                new GoalRoomRoadmapNodeRequest(로드맵_노드.getId(), 1, 오늘, 십일_후));
사소한 거지만 여기서 1이라는 변수는 테스트에서 중요한 역할을 하고 있기 때문에 변수로 추출해주면 더 좋을 것 같아요 😊

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
> +                LocalDate.now().atStartOfDay().plusDays(1));
여기서 내일에 대해 테스트를 하려면 `LocalDate.now().atStartOfDay().plusDays(1)`가 기준 값이니까 두 번째 인자는 `LocalDate.now().atStartOfDay().plusDays(2)`가 맞지 않을까요?
변수로 각각을 추출해주면 좀 더 좋을 것 같아요!

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
> +        assertThat(response).contains("originalFileName");
여기서 응답값을 contains로 하신 이유는 프로덕션 코드에서 현재 시간을 받아와서 파일 이름을 설정해주면서 해당 값에 대해 테스트가 불가능해지기 때문이겠죠?! 앞서 프로덕션 코드 부분에서 파일 이름에 대한 제너레이터를 인터페이스를 두는 건 어떠냐는 의견을 드렸었는데, 아마 해당 인터페이스를 활용하면 테스트에서도 response 값을 equalTo로 체크하실 수 있을 거예요!

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
> +                .thenReturn(goalRoomRoadmapNode.getCheckCount() + 1);
`goalRoomRoadmapNode.getCheckCount() + 1`에서 1을 더해주지 않더라도 테스트는 통과할 수 있지 않을까요?
인증 피드를 올리려고 할 때 이미 등록된 인증 피드의 개수가 꽉 차있으면 새로운 요청을 받을 수 없게 되는 것이니까요! 
조금 더 edge 값에 대해 테스트하는 느낌이 들 것 같아요.

2023-07-30 04:40 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +        final ImageContentType imageType = getImageContentType(checkFeedImage);
서버 측에서 지원할 수 있는 확장자로 파일 저장 요청이 들어오는지 검증하는 요청이네요!
해당 검증 로직은 `createCheckFeed()` 메서드의 `validateEmptyImage()` 메서드 바로 하위에 위치해도 좋을 것 같아요.
어차피 저장할 수 없는 값이라면 빠르게 검증을 진행해서 쿼리가 나가는 것을 최대한 줄이면 성능으로도 좀 더 이점을 볼 수 있을 것 같아요 ㅎㅎ

2023-08-01 09:46 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
> +                .orElseThrow(() -> new BadRequestException("잘못된 인증 피드 요청입니다."));
확실히 왜 인증 피드를 왜 등록 못하는지 모호하겠네요.. 감사합니다!!

2023-08-01 11:32 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
> +    boolean isMemberUploadCheckFeedToday(final GoalRoomMember goalRoomMember,
이건 꽤 복잡한 문제네요... COUNT를 사용하는 부분이 다른 데에도 있는 게 문제가 될 수 있겠어요.😩
COUNT를 사용하게 되는 경우 인덱스를 사용할 수 있도록 하거나 쿼리를 잘 설계하지 않는 이상 풀 테이블 스캔이 일어나는 거 같은데 불필요하게 List<CheckFeed>를 반환하는 것도 그닥 좋아보이진 않아서요.
일단 boolean 타입만 반환하는 경우만 Count 쿼리를 삭제해주었습니다

2023-08-01 11:36 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .leftJoin(member.memberProfile, memberProfile)
흠 이거 밀리 코든데 말해볼게요

2023-08-01 11:37 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +                .orderBy(sortCond(filterType))
Ditto

2023-08-01 11:52 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +    }
메서드 순서가 엉망진창이었네요🥴

2023-08-01 11:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +    public String createCheckFeed(final String identifier, final Long goalRoomId,
생각을 잠깐 해보니 현재 노드 아이디를 받아도 그 노드가 진짜로 현재 진행되고 있는 노드인지 골룸에 속한 아이디인지 등을 검증하면 비슷할 거 같아서 그냥 원래대로 하겠습니다ㅎㅎㅎㅎㅎ

2023-08-01 12:10 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +        }
져니 꼼꼼하시네요😆

2023-08-01 12:26 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
> +                        documentationResultHandler.document(
제가 이걸 다양하게 시도해 보다가 결국 못했거든요. 혹시 져니는 어떻게 하는지 아시나요? 아래 코드로 시도해봤어요
```
formParameters(
      parameterWithName("description").description("인증 피드 본문")
),
```

2023-08-01 12:27 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        final String imageUrl = 인증_피드_등록_응답.response().header("Location");
ㅎㅎㅎㅎㅎㅎ

2023-08-01 12:50 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
> +        assertThat(response).contains("originalFileName");
굉장히 좋은 거 같아요!!

2023-08-02 02:43 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
> +        assertThat(response).contains("originalFileName");
근데 같은 폴더 내에서라도 같은 이름을 가지는 파일 이름이 들어올 경우가 있을 거 같아서 `System.currentTimeMillis()`를 붙이는 걸 제거할 순 없을 거 같아요. 어떻게 생각하세요?

2023-08-02 02:45 UTC, Ohjintaek commented
리뷰 반영했습니다 져니
아마 어떤 환경에서 실행하든 테스트가 돌아가도록 됐을 거 같긴 한데 확인 부탁드립니다🤔

그리고 지금은 local에서 실행할 때만 yaml파일을 작성해놨는데 다른 profile들에 대해서는 private repository에 추가해야 할 거 같습니다. 이런 방식으로요
```
file:
  upload-dir: /home/ubuntu/images/
  server-path: http://dev.kirikiri.lol/images/
```

2023-08-02 05:34 UTC, Cl8D approved these changes
고생하셨어요 썬샷! 테스트도 안 깨지고 잘 돌아가네요 😊
리뷰 몇 가지 남겼는데 확인하시구 반영할 것들 반영해 주세요!! 
서브모듈만 잘 챙겨서 push 해주시면 좋을 것 같습니다!

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
> +        assertThat(response).contains("originalFileName");
넵 프로덕션에서는 제거할 수 없죠!
다만 테스트 코드에서는 해당 인터페이스에 대해서 재정의가 가능하니까 테스트에 대해서만 다시 수정하면 되지 않을까 싶어요!

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
> +    @Query("SELECT Count(cf)"
엇 대문자로 쓰는 거 좋았는데 왜 바꾸셨어요!! ㅋㅋㅋㅋ

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/CheckFeedFilePathGenerator.java
> +        final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MMdd");
`"yyyy/MMdd"`에 대한 부분을 `String.format("yyyy%sMMdd", DIRECTORY_SEPERATOR)`와 같이 변경할 수 있을 것 같아요!

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/FileService.java
> +        }
해당 디렉터리에 파일이 존재하면 return을 해주고, 바로 try-catch로 하면 depth를 줄일 수 있을 것 같아요!

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
>          }
상위에서 IOException에 대해서 잡아주었기 때문에 여기에서는 별도로 try-catch문을 사용하지 않아도 되지 않을까요? 😮

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/CheckFeedFilePathGenerator.java
> +public class CheckFeedFilePathGenerator implements FilePathGenerator {
`FilePathGenerator` 타입으로는 빈 등록이 하나만 가능해요!
현재 `CheckFeedFilePathGenerator` 클래스의 경우 인증 피드에 대한 이름만 생성이 가능한 형태여서, `FilePathRandomGenerator` 같은 클래스 이름을 사용하고 어느 곳에서든 사용할 수 있도록 만들어주면 좋을 것 같아요.
메서드 인자도 goalRoomID 대신에 그냥 id 같이 좀 더 범용적인 이름을 사용해도 좋을 것 같구요!

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/CheckFeedFilePathGenerator.java
> +        return dateString + DIRECTORY_SEPERATOR + goalRoomId + DIRECTORY_SEPERATOR;
그리고 느낀 건데 단순히 goalRoomId로 구분되는 게 아니라 여기는 골룸의 인증피드에 대한 이름을 생성하는 것이니까, 해당 메서드의 인자로 enum 값을 받아서 디렉터리명을 동적으로 받아도 좋을 것 같네요!

ex)
```java
enum ImageDirType {
	CHECK_FEED("goalroom/checkfeed/"),
	ROADMAP_NODE ("roadmap/"),
	...

	private final String dirName;
}
```

```java
public String makeFilePath(final Long id, final ImageDirType dirType) {
	...
	return dateString + DIRECTORY_SEPERATOR + CHECK_FEED.getDirName() + id + DIRECTORY_SEPERATOR;
}
```

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
>          }
`validateCheckCountAndReturn`
하나의 메서드에 2가지의 행위가 들어가 있네요!
1. 검증하는 행위
2. 반환하는 행위

저는 개인적으로 
```java
final int memberCheckCount = checkFeedRepository.countByGoalRoomMemberAndGoalRoomRoadmapNode(member,
                goalRoomRoadmapNode);
```
이 변수는 `createCheckFeed()` 메서드에서 바로 호출되어도 될 것 같고, 하나의 validation 메서드만 있어도 될 것 같아요!

2023-08-02 05:34 UTC, Cl8D commented on backend/kirikiri/src/test/resources/application.yml
> +  server-path: http://localhost/images/
포트번호도 함께 붙여줘야 좀 덜 어색한 형태가 될 것 같아요! 😊

2023-08-02 12:06 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/CheckFeedFilePathGenerator.java
> +        final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MMdd");
👍👍

2023-08-02 12:06 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
> +    @Query("SELECT Count(cf)"
왔다갔다 하다가 저렇게 해버렸네요🥴

2023-08-02 12:08 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
> +                        documentationResultHandler.document(
mockMvc에서 리퀘스트 정의할 때 미디어타입을 multipart-form-data인걸 명시해주지 않아서 인식을 못 한 거였습니다ㅜㅠㅠㅠ

2023-08-02 16:27 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
>          }
`fileService.uploadFileAndReturnPath()` 쪽에서 IOException에 대한 핸들링을 해주기 때문에 여기서 다시 try-catch를 통해 잡을 필요가 없다는 의미였습니다!

2023-08-03 05:54 UTC, merged