[feat/CK-71] 골룸을 나가는 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #42
Opened 2023-07-29 22:47 UTC by miseongk

## 📌 작업 이슈 번호
[CK-71](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-71)
## ✨ 작업 내용
- 골룸 나가기 기능을 구현했습니다.
- 골룸 목록 조회 통합 테스트 수정했습니다.

## 💬 리뷰어에게 남길 멘트
- `GoalRoomMember`와 `GoalRoomPendingMember`가 필드도 거의 비슷하고, 하는 일이 비슷해서 `BaseGoalRoomMember`라는 추상 클래스를 만들어서 상속받도록 수정했습니다! 
    - 골룸을 나가는 로직에서 골룸이 시작되기 전이면 `GoalRoomPendingMember`의 메서드 호출, 골룸이 완료된 후이면 `GoalRoomMember`의 메서드를 호출하는 차이가 있고, 내부 동작은 동일하기 때문에 중복되는 메서드를 클래스로 빼는게 좋을 것 같았습니다! 이 부분 확인부탁드립니다!

## 🚀 요구사항 분석
- [x]  골룸을 나간다.
    - [x]  골룸이 시작되기 전에 나갈 수 있다.
    - [x]  골룸이 진행중이면 나갈 수 없다.
    - [x]  골룸이 완료된 후에 나갈 수 있다.
- [x]  골룸의 리더가 나가면 그 다음으로 들어온 팔로워가 리더가 된다.
- [x]  골룸에 아무도 남아있지 않으면 해당 골룸은 삭제된다.

2023-08-01 02:38 UTC, Ohjintaek requested changes
수고하셨어요 밀리 👍👍
저번에 주석처리한 골룸 목록 조회 테스트까지 처리하느라 고생하셨을 것 같네요
GoalRoomMember와 PendingGoalRoomMember를 묶는 걸 생각만 해봤는데 잘 해주셔서 너무 좋네요. 잘 쓰겠습니다ㅎㅎ

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
> +        final GoalRoomMember goalRoomMember = new GoalRoomMember(GoalRoomRole.LEADER, LocalDateTime.now(), null, null);
골룸 멤버들을 추상화시켰으니 BaseGoalRoomMember로 선언하는 건 어떨까요?

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
> +        final Member member1 = new Member(1L, new Identifier("identifier1"),
현재 Member의 동등성을 id 값이 같은 것으로 비교하고 있어서 영속화가 되기 전이라면 id가 null이라서 같은 멤버로 판단하더라구요. Member의 경우에 반드시 값을 가지고 있어야 되고 unique한 필드인 identifier와 nickname을 equals와 hashCode에 추가하는 건 어떨까요?

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        골룸.complete();
이 부분은 나중에 Scheduler로 골룸 종료 기능을 추가한 후에 바꿔야 하니 TODO를 남기는 건 어떠세요?

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        goalRoomMemberRepository.save(골룸_참여자);
이 부분은 goalRoomCreateService의 startGoalRooms를 한 번 호출하면 되지 않을까요?

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        assertThat(골룸_생성_응답_바디.message()).isEqualTo("골룸에 참여한 사용자가 아닙니다. memberId = 3");
회원 생성을 두 번만 했는데 왜 memberId가 3이 나오나요? 😵

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        goalRoomMemberRepository.save(골룸_참여자);
이 부분 역시 goalRoomCreateService의 startGoalRooms를 사용하면 좋을 거 같습니다

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +    void 모집중인_골룸을_나갈때_리더가_나가면_다음으로_들어온_사용자가_리더가_된다() throws JsonProcessingException {
다음으로 들어온 사용자가 리더가 된다는 걸 검증하기에는 남은 사용자가 한 명밖에 없어서 세 명을 참여시키는 건 어떨까요?

2023-08-01 02:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        assertThat(골룸_목록.data().get(0).goalRoomLeader().name()).isEqualTo("name2");
다른 부분은 TODO로 남겨놨는데 이건 왜 확인하셨나요ㅋㅋㅋㅋㅋㅋ 근데 안 하면 불안하긴 해요😆😆

p.s. 밑에 ReadIntegrationTest를 보니 골룸 단일 조회 API가 있던데 적용할 수 없는 경우일까요?

2023-08-01 17:00 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMembers.java
> +    public GoalRoomMember findByMember(final Member member) {
그렇네요 Optional로 감싸서 반환해서 외부에서 처리하도록 하는 것이 훨씬 좋겠네요👍👍👍

2023-08-01 17:06 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
> +        final GoalRoomPendingMembers goalRoomPendingMembers = findGoalRoomPendingMembers(goalRoom);
오... 왜 이생각을 못했을까요 😭
뭔가 레포지토리랑 엮여있어서 도메인으로 역할을 주지 않았던 것 같아요. 그런데 조금 더 고민해보니 충분히 가능했네요 ㅎㅎ

그리고 제가 아까 goalRoomPendingMembers.remove() 하면 delete 쿼리가 안나간다고 했었는데, 골룸 내부의 필드에서 remove를 해주니 쿼리가 날라가더라구요! 잘 생각해보니 당연한거였어요. goalRoom과 goalRoomPendingMember의 엔티티의 관계에 persist.remove가 걸려있어서 저절로 쿼리가 나가는게 맞고, 제가 처음에 했던 것은 골룸 내부에 있는 goalRoomPendingMembers에서 remove 한게아니고, 서비스에서 레포지토리에서 받아온 펜딩 멤버에서 remove를 해서 쿼리가 날라가지 않았던거였어요..!

썬샷 덕분에 많이 배웠네요 😄

2023-08-01 17:12 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
> +        final GoalRoomMember goalRoomMember = new GoalRoomMember(GoalRoomRole.LEADER, LocalDateTime.now(), null, null);
GoalRoomMember와 GoalRoomPendingMember에 대한 테스트는 각각 도메인을 테스트하는 거라 BaseGoalRoomMember로 선언하는 것보다 직접 클래스를 선언하는 것이 명확해보여서 놔둬도 괜찮을 것 같은데, 어떻게 생각하시나요??

2023-08-01 17:27 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        goalRoomMemberRepository.save(골룸_참여자);
그 메서드가 머지가 안됐을 때 만들었던 거라,,,
나중에 같이 수정할게요!

2023-08-02 01:41 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        assertThat(골룸_생성_응답_바디.message()).isEqualTo("골룸에 참여한 사용자가 아닙니다. memberId = 3");
로드맵 생성할 때 회원이 생성되서 총 3명이에요!

2023-08-02 02:00 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
> +        assertThat(골룸_목록.data().get(0).goalRoomLeader().name()).isEqualTo("name2");
골룸 목록 api로 확인하면 모집중인 골룸만 조회되서 완료된 골룸에 대해서 내부값을 못봤어요ㅠㅠ
근데 골룸 단일 조회 api가 있는줄 몰랐네요,, 추가하겠습니다!

2023-08-02 02:34 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
> +        final Member member1 = new Member(1L, new Identifier("identifier1"),
흠 그렇네요! 그런데 영속화 되기 이전에 동등성을 비교할 일이 있을까요??
회원가입을 한 이후에는 보통 데이터베이스에서 멤버를 꺼내와서 사용하니까 아이디가 없는 경우가 있을까해서요! 
어떻게 생각하시나요??

2023-08-02 05:03 UTC, miseongk commented
리뷰 반영 완료했습니다~!
리뷰 덕분에 조금 더 깔끔한 코드가 됐어요 ㅎㅎ
코멘트도 남겼으니 확인해주세요!!

2023-08-02 05:06 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
> +        final Member member1 = new Member(1L, new Identifier("identifier1"),
보통 테스트 실패 때문에 문제가 되는 경우가 많았는데 테스트코드를 좀 더 잘 짜면 상관없는 문제일 거 같긴 하네요

2023-08-02 05:07 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
> +        final GoalRoomMember goalRoomMember = new GoalRoomMember(GoalRoomRole.LEADER, LocalDateTime.now(), null, null);
좋아요!!

2023-08-02 05:47 UTC, Ohjintaek approved these changes
수고하셨어요 밀리~

2023-08-02 05:47 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
> +
빈 개행 있어요

2023-08-05 19:50 UTC, merged