Feature/ck 86
woowacourse-teams/2023-co-kirikiri pull request #45
Opened 2023-07-30 16:40 UTC by NaveOWO

## 📌 작업 이슈 번호

## ✨ 작업 내용

## 💬 리뷰어에게 남길 멘트

## 🚀 요구사항 분석

2023-07-30 17:03 UTC, sh981013s requested changes
고생하셨어요 네이브!!  

코드 잘 읽었습니답!

전반적으로 깔끔해서 읽기 편했네여. 다만 태그를 길게 입력했을 때 resizing 되며 흔들리는 것만 잡아주시면 너무 좋을 것 같네여!  고생하셨어요~

2023-07-30 17:03 UTC, sh981013s commented on client/src/hooks/roadmap/useCreateTag.ts
> +  };
이부분은 `checkTagCountUnderFive` 도 좋지만 조금 더 범용적으로 `checkIsTagCountNumberValid` 로 하고 tag.length 인 4 를 상수화 하여 유지보수성을 높이면 어떨까용??

2023-07-30 17:03 UTC, sh981013s commented on client/src/components/roadmapCreatePage/tag/tag.styles.ts
> +  /* ${({ theme }) => theme.fonts.nav_title} */
필요한 주석이었을까여??? 😀

2023-07-30 17:03 UTC, sh981013s commented on client/src/components/roadmapCreatePage/tag/TagItem.tsx
> +        maxLength={10}
10도 같이 매직넘버가 아니라면 상수화를 진행해보면 어떨까여??

2023-08-02 06:27 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/tag/tag.styles.ts
> +  /* ${({ theme }) => theme.fonts.nav_title} */
왜 주석 쳐놧지..? 감사해요~!

2023-08-02 06:34 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/tag/TagItem.tsx
> +        maxLength={10}
좋은 생각아에요~ 수정했습니다!

2023-08-02 06:36 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/tag/Tag.tsx
> +        {checkTagCountUnderFive() && <S.AddButton onClick={getTagText}>+</S.AddButton>}
그런 것 같아요!! `getAddedTagText` 라는 네이밍으로 수정했습니다!

2023-08-02 06:44 UTC, NaveOWO commented on client/src/components/roadmapCreatePage/tag/TagItem.tsx
> +        readOnly={props.readOnly}
사실 귀찮아서 그냥 input에 readOnly 준건데 사용자의 조작은 생각하지 못했어요..!! 
우디 말대로 새로운 컴포넌트 만들어서 다시 수정했습니다!! 그리고 우디말대로 하니깐 이전에 버그 하나 해결됨 ㄷ ㄷ

2023-08-02 06:50 UTC, sh981013s approved these changes
굿굿이요~~~~~~~~~~👍👍👍

2023-08-02 07:35 UTC, evencoding approved these changes
너무 고생하셨어요🤩

2023-08-02 07:37 UTC, merged