[feat/CK-95] 골룸 상단부분 데이터를 매핑한다
woowacourse-teams/2023-co-kirikiri pull request #46
Opened 2023-07-30 17:12 UTC by sh981013s

## 📌 작업 이슈 번호

[CK-95](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-95)

## ✨ 작업 내용

![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/81363031/68d62f12-5a28-4982-96c2-478dcb5bd550)

- msw 오류 해결
  - 사실 왜 해결되었는지 정확히는 잘 모르겠지만, index.tsx 에서 msw 구동 방식을 조금 바꿔봤습니다. 제 로컬에서는 정상작동!

- 골룸 단일 조회 mocking fixture 생성 및 handler 연결
- 골룸 단일 조회 fetching hook 구현 
- 골룸 단일 조회 상단 header 에 데이터 매핑

## 💬 리뷰어에게 남길 멘트

- 코드를 보며 얘기해보고 싶은 부분이 있어 files changed 에 코멘트로 달아놓겠습니다! 확인 부탁드려용

## 🚀 요구사항 분석

- 골룸 상단부분 데이터 매핑

2023-07-30 17:13 UTC, sh981013s commented on client/src/apis/axios/client.ts
> +  (response) => response.data,
저는 이전에는 tanstack query 가 내부 data 까지 반환해주는줄 알았는데, 실제로 현 상태에서는 그대로 반환하더군요..?

혹시 아시는바가 있으실까여?

2023-07-30 17:16 UTC, sh981013s commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
> +  const { goalroomId } = useParams() as GoalRoomDashboardContentParams;
`useParams` 를 썻을 때 타입이 `T  | undefined` 가 나오는 상황에 대하여 찾아봤는데 도저히 type guard 를 할 수 있는 방법을 모르겠더라고요.. 그래서 우선 단언을 하긴 했는데, 조언이 있을까여??

2023-07-31 05:35 UTC, NaveOWO requested changes
엉 아픈데도 너무 고생했어요👍 수정요청한 부분만 고쳐주세요~!

2023-07-31 05:35 UTC, NaveOWO commented on client/src/apis/axios/client.ts
> +  (response) => response.data,
엇뜨 저는 response 자체를 반환한다고 알고있는데요..!! 근데 이부분은 tanstack query 쓰는 부분이 아닌딩!?

2023-07-31 05:35 UTC, NaveOWO commented on client/src/apis/goalRoom.ts
> +export const browseGoalRoom = async (goalRoomId: string) => {
데이터를 받아오는 부분은 get- post- patch- 같이 prefix를 통일하는게 가독성이 좋을 것 같아요!

2023-07-31 05:35 UTC, NaveOWO commented on client/src/apis/goalRoom.ts
> +  return data;
그리고 roadmap부분에는 client,get 자체를 리턴하고있는데, 이부분에서는 거기서 data를 뽇아내서 리턴하고있어요!! 통일해야할 것 같은데, 어떤게 더 좋을 것 같나요!?

저는 crud 모두 함수가 아니라 반환값을 리턴하는게 좋을 것 같아요! 데이터 패칭을 매핑하는 함수라면 안전하게 그 반환값만 사용할 수 있는게 좋을 것 같아서요!

2023-07-31 05:35 UTC, NaveOWO commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
> +  const { goalroomId } = useParams() as GoalRoomDashboardContentParams;
맞아요..!!  prarms가 없는 곳에서 저 훅을 쓸 수도 있어서 undefined가  나오는데, 커스텀 훅을 새로 생성해서 반환값이 undefined일 때는 에러를 던지고 아닐 때 params를 반환하게 하게 하는게 좋은 방법인 것 같은데 어떠세요!?
`useValidParams` 이런 식의 훅이요!

2023-07-31 05:35 UTC, NaveOWO commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
> +      />
goalRoom객체 자체를 넘겨서 받는 곳에서 구조분해 할당하는건 어뗘..!?
객체로 묶어서 인자를 한번에 주면 가독성도 좋아지고, goalRoom에 대한 prop이 늘어났을 때에도 유동적으로 사용할 수 있어서 더 효율적인 코드가 될 것 같아요!

2023-07-31 05:35 UTC, NaveOWO commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
> +  endDate,
위의 리뷰 참고!

2023-07-31 05:35 UTC, NaveOWO commented on client/src/hooks/queries/goalRoom.ts
> +export const useFetchGoalRoom = (goalRoomId: string) => {
id가 서버에서 string으로 내려오나요!?

2023-07-31 05:35 UTC, NaveOWO commented on client/src/index.tsx
> +      onUnhandledRequest: 'bypass',
폼 미쳤다

2023-07-31 05:40 UTC, evencoding reviewed
부엉이!
몸도 안좋은데 너무 고생하셨어요😭

코드에 배울점이 많아서 정말 재미있네요!!
몇 가지 코맨트만 확인 부탁드릴게요!

2023-07-31 05:40 UTC, evencoding commented on client/src/constants/goalRoom/recruitmentStatus.ts
> +const recruitmentStatus: { [key in GoalRoomRecruitmentStatus]: string } = {
recruitmentStatus의 타입은 따로 type으로 선언하지 않으신 이유가 궁금해용!

2023-07-31 05:40 UTC, evencoding commented on client/src/hooks/queries/goalRoom.ts
> +  };
넘 좋아용👍

2023-07-31 05:40 UTC, evencoding commented on client/src/mocks/fixtures/goalRoom.ts
> +  },
Depth가 깊은 상수 객체에 대해서, 이렇게 불변성을 챙기는 거 너무 좋은 것 같네요🤩

많이 배워요👍

2023-07-31 05:40 UTC, evencoding commented on client/src/apis/axios/client.ts
> +  (response) => response.data,
저도 내부 data를 반환해주는 걸로 알고 있어서 이상하다고 생각했어요
이 부분은 따로 찾아보고 공유하겠습니다🤩

2023-07-31 05:40 UTC, evencoding commented on client/src/apis/goalRoom.ts
> +  return data;
저도 이 부분에 대해서 프론트끼리 컨벤션을 만들면 좋겠다고 생각했어요!!

2023-07-31 05:40 UTC, evencoding commented on client/src/index.tsx
> +      onUnhandledRequest: 'bypass',
미춌따이

2023-07-31 11:27 UTC, sh981013s commented on client/src/apis/axios/client.ts
> +  (response) => response.data,
엇 알겠습니다..!

2023-07-31 11:44 UTC, sh981013s commented on client/src/apis/goalRoom.ts
> +export const browseGoalRoom = async (goalRoomId: string) => {
오오 좋아요!! `getGoalRoomDashboard` 로 네이밍 변경했어요~!!

```ts
export const getGoalRoomDashboard = async (goalRoomId: string) => {
  const { data } = await client.get<GoalRoomBrowseResponse>(
    `/api/members/goal-rooms/${goalRoomId}`
  );

  return data;
};

```

2023-07-31 11:46 UTC, sh981013s commented on client/src/apis/goalRoom.ts
> +  return data;
저도 관심사를 분리하려 반환값인 `data` 를 반환하도록 했었어요! 괜찮으실까요???

2023-07-31 11:46 UTC, sh981013s commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
> +  const { goalroomId } = useParams() as GoalRoomDashboardContentParams;
쒸잇..  너무 좋은데여..?

https://github.com/woowacourse-teams/2023-co-kirikiri/pull/46/commits/c64f0de7007b1cc39fcc7e1fb3658e0a45db27ba

useValidParams 훅 생성 후 적용했습니다~!

2023-07-31 11:51 UTC, sh981013s commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
> +      />
저도 여기서 턱 막혀서 한참을 고민했었는데 고마워요!!

> goalRoom에 대한 prop이 늘어났을 때에도 유동적으로 사용할 수 있어서 더 효율적인 코드가 될 것 같아요!

이말이 와닿았네요! 객체 자체를 넘기도록 수정했습니다~!

```tsx
const GoalRoomDashboardHeader = ({ goalRoomData }: GoalRoomDashboardHeaderProps) => {
  const { name, status, currentMemberCount, initMemberCount, startDate, endDate } =
    goalRoomData;

  return (
    <header>
      <S.GoalRoomDashboardTitle>{name}</S.GoalRoomDashboardTitle>
      <S.GoalRoomLabel>
        <SVGIcon name='ITIcon' />
        <span>{recruitmentStatus[status]}</span>
      </S.GoalRoomLabel>
      <S.GoalRoomLabel>
        <SVGIcon name='PersonIcon' />
        <span>
          {currentMemberCount} / {initMemberCount} 명 참여 중
        </span>
      </S.GoalRoomLabel>
      <S.GoalRoomLabel>
        <SVGIcon name='CalendarIcon' />
        <span>
          {startDate} ~ {endDate}
        </span>
      </S.GoalRoomLabel>
    </header>
  );
};
```

2023-07-31 11:52 UTC, sh981013s commented on client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
> +  endDate,
확인이요!!

2023-07-31 11:52 UTC, sh981013s commented on client/src/hooks/queries/goalRoom.ts
> +export const useFetchGoalRoom = (goalRoomId: string) => {
아뇨아뇨! useParam 으로 추출한 값이 string 타입이며, 인자로 넣는 곳입니다!

2023-07-31 11:54 UTC, sh981013s commented on client/src/constants/goalRoom/recruitmentStatus.ts
> +const recruitmentStatus: { [key in GoalRoomRecruitmentStatus]: string } = {
`GoalRoomRecruitmentStatus` 로 이미 선언해둔 상황입니다!

```ts
export type GoalRoomRecruitmentStatus =
  | 'RECRUITING'
  | 'RUNNING'
  | 'COMPLETED'
  | 'RECRUIT_COMPLETED';
```

여기서 사용한 객체는 영어로 내려온 서버 데이터를 한글로 변환하려 만든 객체이구요!

2023-07-31 12:27 UTC, evencoding commented on client/src/apis/goalRoom.ts
> +  return data;
쪼~아용!

2023-07-31 12:39 UTC, evencoding approved these changes
코맨트 확인 고마워요 부엉이🤩

고생하셨어요
approve 하겠습니다!

2023-08-01 04:28 UTC, NaveOWO approved these changes
엉 수고 많앗어요~~!~!!! useValidParams에서 단언부분이 좀 신경쓰이긴 한데... 다음에 같이 고민해봐용~

2023-08-01 04:30 UTC, merged