[feat/CK-68] 사용자가 생성한 로드맵의 목록을 조회하는 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #47
Opened 2023-07-30 17:42 UTC by miseongk

## 📌 작업 이슈 번호
[CK-68](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-68)

## ✨ 작업 내용
- 사용자가 생성한 로드맵을 최신순으로 조회하는 기능을 구현했습니다.
- 로그인한 사용자의 로드맵 목록을 조회하는 기능이고, 아직 저희 기능에 특정 사용자가 생성한 로드맵을 조회하는 기능이 없어서 `memberId`를 Path Parameter로 받지 않았습니다. 
- 로드맵의 상세 내용을 반환하는 것이 아니라, 사용자 페이지에 보여질 간단한 데이터만 반환합니다.

## 💬 리뷰어에게 남길 멘트
- 무한스크롤 방식으로 구현했는데, 이 부분은 져니의 [Feat/CK-67 PR](https://github.com/woowacourse-teams/2023-co-kirikiri/pull/40)에 이미 구현되어 있는데 아직 머지가 되지 않아서 그대로 옮겨서 사용했습니다!
- 사용자가 생성한 로드맵을 조회할 때 정렬 기준을 설정하는 기능이 없고 최신순으로만 조회하기 때문에, 무한 스크롤 방식에서 이전에 받았던 로드맵의 id(쿼리 파라미터의 `lastValue`)보다 작은 데이터를 받아오도록 구현했습니다!
- 로드맵의 간단한 데이터를 반환한다는 의미로 `RoadmapSummaryResponse`라는 네이밍을 사용했습니다! (별로라면 추천부탁드립니다.. ㅎㅎ) 이 객체는 나중에 다른 사용자의 로드맵 목록을 조회하는 기능이 생기면 재사용할 수 있을 것 같습니다!
- 로드맵 태그도 반환해야 하는데, 아직 태그 기능이 머지되지 않아서 추후에 추가하도록 하겠습니다.

## 🚀 요구사항 분석
- [x]  로그인한 사용자가 생성한 로드맵을 최신순으로 조회한다.
    - [x]  로드맵 아이디, 로드맵 제목, 난이도, 카테고리, 태그(추후 추가)
    - [x]  무한스크롤 방식으로 구현한다.

2023-08-01 03:19 UTC, Ohjintaek requested changes
수고하셨어요 밀리
큰 수정요청 사항은 없는데 말씀하신대로 로드맵에 CreatedAt이 생기면 repository의 로직을 좀 수정해주면 좋을 거 같아요!!
`RoadmapSummaryResponse`같은 이름의 경우 저는 더 많은 정보가 될 거 같다는 생각이 들어서 `MemberRoadmapResponse`는 어떨까요? 저는 사용자가 참가한 골룸목록을 반환할 때 저런 네이밍을 썼어요. 이것도 api처럼 맞추는 게 좋을 거 같아서 맘에 안 드시면 같이 얘기해보시죠😆

2023-08-01 03:19 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
> +    void 사용자가_생성한_로드맵_조회한다() {
말투가 딱딱하네요

2023-08-01 03:19 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
> +import static java.util.List.of;
실수로 List.of를 static으로 import한 거 같아요.
아니면 List.of 치기가 귀찮으셨나요?😁😁

2023-08-02 05:28 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +    @GetMapping("/me")
아 그럼 사용자가 참여한 골룸 목록은 MemberController에 있나요?!
저는 로드맵 하위로 넣어서 저렇게 했어요!

2023-08-02 05:29 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
> +        return roadmap.id.lt(lastValue);
그렇더라구요🤷🏻‍♀️

2023-08-02 05:30 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
> +    List<Roadmap> findRoadmapsWithCategoryByMemberOrderByIdDesc(final Member member, final Long lastValue,
추후에 id말고 createdAt으로 정렬하게 될 테니 썬샷이 말씀해주신 네이밍이 더 좋을 것 같네요!

2023-08-02 12:19 UTC, miseongk commented
리뷰 반영 완료했고, 
추가적으로 골룸 목록 조회 API를 특정 로드맵에 대한 골룸 목록을 조회하도록 수정했습니다!

2023-08-02 12:51 UTC, Ohjintaek approved these changes
테스트 이리저리 옮기고 수정을 엄청나게 한 게 보이네요
수고하셨습니다 밀리!!😊
로직 자체 변경은 크게 없어서 바로 어프루브 할게요

2023-08-02 12:51 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
> +    public List<GoalRoom> findGoalRoomsWithPendingMembersPageByCond(final Roadmap roadmap,
메서드 네이밍이 `ByCond`라서 조건에 따라 선별하는 줄 알았는데 보니까 순서를 정렬하는 역할이네요. `OrderBy`나 `SortBy`같은 건 어떨까요?

2023-08-02 18:25 UTC, merged