[feat/CK-22,76] 사용자가 참가한 골룸 목록 조회와 단일 조회(인증 피드 조회)를 구현한다
woowacourse-teams/2023-co-kirikiri pull request #48
Opened 2023-07-30 21:22 UTC by Ohjintaek

## 📌 작업 이슈 번호
[CK-76](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-76) 

## ✨ 작업 내용
- 인증 피드 조회 기능을 구현했습니다. 따로 요청이 오는 것이 아니라 사용자 골룸 단일 조회 페이지에서 현재 진행 중인 노드 동안 등록된 인증 피드만 볼 수 있어서 `사용자 골룸 단일/목록 조회` 다시 만들면서 같이 해주었습니다.
- 사용자가 참여한 골룸의 단일 조회 기능을 구현했습니다. 페이지가 제한되어서 골룸 노드 2개, 투두 3개, 인증 피드 4개까지만 제한해서 보냅니다.
- 사용자가 참여한 골룸의 목록 조회 기능을 구현했습니다. 쿼리파라미터를 통해 조회하고 싶은 골룸의 상태를 보낼 수 있고 명시하지 않으면 전체 골룸 목록을 보냅니다.

## 💬 리뷰어에게 남길 멘트
- feature/CK-75 브랜치에서 분기해서 작업했습니다. 앞의 commit들은 겹치기 때문에 뒷 부분만 리뷰해주시면 돼요. [이 부분입니다]()
- querydsl에서 여러 테이블들을 join할 때 최적화 측면에선 아직 잘 몰라서 `이러면 되겠다`라는 식으로 작성한 상태입니다. 혹시 좀 더 나은 방법이 있으면 추천해주시면 감사하겠습니다.
- GoalRoomMapper의 `convertToGoalRoomRoadmapNodesResponse` 메서드에 Mapper치고는 로직이 좀 들어간 편입니다. 사용자 골룸 단일 조회에서 골룸 노드를 보여줄 때 현재 진행 중인 노드를 기준으로 2개를 보여주고, 표시된 2개의 앞 뒤에 노드가 존재하는지 여부를 반환하는데 도메인 로직은 아니라고 생각해서 따로 GoalRoom에 메서드를 만들지 않았습니다. 괜찮은지 코멘트 해주시면 감사하겠습니다.

## 🚀 요구사항 분석

## 인증 피드 조회 기능

- [x] 골룸의 인증 피드 조회 기능 구현
    - [x] 골룸 내의 현재 진행 중인 노드에서 등록된 피드만 전달한다

## 사용자가 참가한 골룸을 조회한다

- [x] 사용자 골룸 단일 정보를 조회한다
- [x] 사용자 골룸 목록을 조회한다
    - [x] 골룸의 상태에 따라 나눠서 조회할 수 있다(모집 중, 진행 중, 완료 등)

2023-07-31 06:44 UTC, Cl8D requested changes
고생하셨어요 썬샷~!! ☀️☀️
중복되는 메서드를 분리하는 방향으로 가면 테스트도 조금 더 가벼워질 것 같아요 ㅎㅎ
간단하게 제 의견을 담아보았는데 확인하시구 반영 부탁드립니다!!

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +        goalRoomCreateService.startGoalRooms();
이부분도 메서드를 따로 추출해주면 한글로 메서드명이 씌워질 테니 이해하기 쉬울 것 같아요!

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +        goalRoomCreateService.startGoalRooms();
사실 테스트를 보면서 조금 고민이 드는 부분이 있네요...!
아무래도 E2E 테스트다 보니까 골룸이 시작되기 위해서는 해당 메서드를 호출해서 골룸을 시작시켜줘야 하지만, 시작하는 메서드의 로직을 살펴보면 해당 메서드가 호출된 날짜에 해당하는 골룸들을 전부 시작하고 있더라구요.
그래서 아마 썬샷도 오늘에 해당하는 골룸을 만들고 해당 메서드를 호출하신 것 같아요.
하지만 만약 테스트가 실행되는 시점이 23:59 -> 24:00이라면 테스트가 실패할 가능성도 있을 것 같아요. (하루로 인해서 수가 틀릴 수도 있으니까요...!) 
이건 어떻게 해결하기보다는 그렇게 테스트가 실패할 수 있는 지점이 있을 수 있다는 거여서... 어렵네요 ㅠ

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +        assertThat(memberGoalRooms).hasSize(4);
이 테스트는 특정 사용자의 골룸을 조회하는 것이니까 다른 member를 생성해서 작성하는 게 좀 더 정확한 테스트가 될 것 같아요!
또한 결과에 대해서 사이즈만 검증하는 것이 아닌 내부 내용까지 함께 검증할 수 있는 포인트인 것 같아요.

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +                .get();
여기서도 개인적으로 골룸 여러 개를 저장한 다음에 특정 골룸에 대해서만 잘 조회되는지 판단하면 더 좋을 것 같아요!

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +        );
여기도 사이즈 말구 내용까지 검증하면 좋을 것 같습니다! 😮

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
`findMemberGoalRooms()`와 `findMemberGoalRoomsByStatusType()`의 테스트 메서드가 빠진 것 같아요! 추가 부탁드립니다 🙇‍♀️

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
> +    void 사용자_단일_골룸을_조회한다() {
`findMemberGoalRoom()` 메서드에서 발생할 수 있는 분기가 여러 개인데 테스트 케이스가 조금 부족한 것 같아요! 테스트 커버리지에 걸릴 수 있는 부분들이라서 언급드립니다! ㅠㅠ

1. `findMemberGoalRoomById()` : 골룸이 존재하지 않을 때 
2. `findMemberByIdentifier()`로 인해서 회원이 존재하지 않을 때
3. `validateMemberInGoalRoom()`: 골룸에 참여하지 않은 사용자일 때

번거로우실 수 있겠지만 서비스 테스트에서는 분기점에 대해서 모두 테스트를 하는 게 좋기 때문에 좀만 더 힘내주세요!! 💪💪💪

2023-07-31 06:44 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +                .orElseThrow();
?! 예외 메시지가 빠져있어요!

2023-08-03 06:59 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/GoalRoomStatusTypeRequest.java
> +        this.description = description;
그랬었는데 지금은 없애도 되네요...?

2023-08-03 07:20 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomRoadmapNodeResponse.java
> +        Integer checkCount
GoalRoomRoadmapNode의 id도 넘겨주도록 바꾸었습니다!!

2023-08-03 07:40 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +        assertThat(memberGoalRooms).hasSize(4);
골룸을 생성할 때 들어간 creator의 골룸목록도 호출해서 제대로 가져오는지 수정했습니다!! 두 멤버가 참여한 골룸을 다르게 했고 내부 내용도 usingRecursiveComparison()을 사용했어요

2023-08-03 07:50 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +                .get();
서로 다른 사용자가 골룸을 만들게 해서 저장한 뒤 두 골룸 다 조회해보았습니다

2023-08-03 07:54 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
> +        );
역시 usingRecursive()를 사용해주었습니다!!!

2023-08-03 08:38 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
테스트 작성할 때 정신이 많이 빠져있었네요... 테스트 코드 작성이 안 된 부분이 이렇게 많았다니😲
죄송합니다

2023-08-03 09:05 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
> +    void 사용자_단일_골룸을_조회한다() {
화이팅 화이팅 감사합니다 져니

2023-08-03 09:05 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +                .orElseThrow();
유효하지 않은 골룸이 들어왔을 때 예외 메시지를 반환해주었습니다!!!

2023-08-03 09:08 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
> +                .limit(3)
너무 좋습니다!! 나중에 충분히 바뀔 수도 있는 숫자고 알아보기도 쉬워졌어요😊

2023-08-03 09:10 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +        final List<CheckFeed> checkFeeds = checkFeedRepository.findByGoalRoomRoadmapNode(goalRoomRoadmapNode);
좋습니다 바꿔줬어요~

2023-08-03 10:35 UTC, Cl8D approved these changes
고생하셨어요 썬샷~!
다음에 리팩터링용 브랜치 파서 남은 리뷰들 반영해 주세요! 💪

2023-08-03 12:16 UTC, merged