[feat/CK-118] 골룸의 노드 리스트 정보를 조회하는 기능을 추가한다
woowacourse-teams/2023-co-kirikiri pull request #72
Opened 2023-08-06 17:37 UTC by Cl8D

## 📌 작업 이슈 번호
[CK-118](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-118)

## ✨ 작업 내용
- 골룸의 노드 리스트에 대해 조회하는 기능을 추가하였습니다.
- 기존의 골룸 정보 조회 시 노드의 아이디값을 내려주지 않는 클래스가 있길래 해당 클래스를 제거하였습니다.

## 💬 리뷰어에게 남길 멘트
- 엄청 간단한 작업이라 리뷰할만한 것도 없을 것 같네요...!
- 다만 노드 조회 시에 추가적으로 더 필요한 정보가 없나 고민이 듭니다...! 제목, 날짜, 횟수 정도만 반환하고 있는데 혹시 더 필요한 정보는 없을지 확인 부탁드려요! (피그마에 딱히 나온 게 없어서 우선 기존의 클래스를 재활용하였습니다.)
- 아, 추가적으로 저번에 작업한 투두리스트 관련해서 리뷰를 못 받고 merge가 되었어서...! 간단하게 리뷰 주시면 해당 내용 이번에 반영하도록 하겠습니다. [PR 링크](https://github.com/woowacourse-teams/2023-co-kirikiri/pull/63)

## 🚀 요구사항 분석
- 골룸의 노드 정보를 반환한다.

2023-08-07 11:57 UTC, miseongk requested changes
져니 고생하셨어요~!
특별한 리뷰는 없어서 바로 approve 하려고 했는데
투두리스트 조회 부분도 리뷰하고 하는 게 좋을 것 같네용 🙃

투두리스트 조회 기능도 빨리 리뷰 남길게요!

2023-08-07 11:57 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +        final List<GoalRoomRoadmapNodeResponse> goalRoomTodoResponses = List.of(
변수명이 '골룸투두' 네요!😉

2023-08-07 11:57 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
> +                                        fieldWithPath("[0].id").description("로드맵 노드 아이디"),
'골룸 로드맵 노드 아이디'라고 해야 헷갈리지 않을 것 같아요!

2023-08-07 11:57 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +        validateGoalRoomMember(goalRoomId, identifier);
위에 져니가 작성해주시지 않은 메서드 중에 `validateMemberInGoalRoom` 이라는 메서드는 member를 인자로 넣고 참여하지 않은 멤버일 시 `BadRequestException`을 던지네요. 
골룸에 참여하지 않은 멤버가 어떤 행위를 할 경우 BadRequest vs Forbidden 으로 할 지 저희끼리 통일해야 할 것 같네요!

저는 지금 생각해보면 Forbidden이 더 적절할 것 같아요!

2023-08-07 11:57 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
> +
골룸 노드 조회 시 발생하는 예외 상황에 대해서도 테스트 하면 좋을 것 같아요!

2023-08-07 14:21 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
> +    public ResponseEntity<List<GoalRoomRoadmapNodeResponse>> getAllNodes(
아고... 자꾸 실수하네요 🥲 수정하겠습니다!

2023-08-07 14:25 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
> +        validateGoalRoomMember(goalRoomId, identifier);
앗 사실 이 부분은 썬샷이 작업해주신 부분이라 제가 건들기가 애매하네요...
한 번 여쭤봐야겠어요! 좋은 의견 감사합니다!

2023-08-08 01:13 UTC, miseongk approved these changes
어프르부할게요~!

2023-08-08 01:14 UTC, merged