[feat/CK-16] 로드맵 생성 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #8
Opened 2023-07-15 10:53 UTC by miseongk

## 📌 작업 이슈 번호
[CK-16](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-16)

## ✨ 작업 내용
- 로드맵 생성 API를 구현했습니다.
- 카테고리, 제목, 소개글, 본문, 난이도, 전체 추천 소요 기간, 각 로드맵 단계 별 제목, 각 로드맵 단계 별 설명을 입력받아 로드맵을 생성합니다.

## 💬 리뷰어에게 남길 멘트
- `List<RoamapContents>`, `List<RoadmapNode>`를 모두 일급컬렉션으로 묶어서 관리했습니다.
- 기존에 같이 구현했던 `RoadmapContent`의 필드인 `List<RoadmapNode>`도 cascade `CascadeType.PERSIST, CascadeType.MERGE` 를 추가해서, `RoamapContent`가 저장될때 같이 저장되도록 수정했습니다.
- ⭐️ 원래 로드맵 생성 시 각 노드에 대한 사진을 노드 별로 2개 이하로 받기로 되어있는데, 그렇다면 아래의 명세처럼 roadmapNodes 배열에서 **각각의 요소에 대한 이미지를 여러개 받아야 되는 상황**인데 이미지는 multipart/form-data로 전달해야해서 2 depth를 들어가서 각 요소에 대한 이미지를 받아오는 것이 구현이 안되는 것 같습니다..! (제가 몰라서 그럴수도 있어요..)
그래서 일단은 로드맵 생성이 더 우선이기 때문에 이미지를 받아오는 부분을 모두 제외하고 구현했습니다. 🥹
로드맵 생성 api 호출 시 함께 모든 이미지를 받아오는 방법을 조금 더 알아보고, 불가능하다면 다른 방법을 찾아봐야 할 것 같습니다!!
```json 
[
    {
        "categoryId": 4,
        "title": "필라테스 마스터 로드맵",
        // 생략..
        "roadmapNodes": [
		        {
				"title": "필라테스 1주차",
				"content": "필라테스 1주차에는 준비 운동을 배울거에요.",
				"images" : [{}, {}] // <----
		        },
		        {
				"title": "필라테스 2주차",
				"content": "필라테스 2주차에는 기구 사용법을 배울거에요.",
				"images" : [{}, {}] // <----
		        }
           ]	
    }
]
```
- 제가 JPA를 아직 잘 다루지 못해서 완벽하지 않을 수 있습니다 😭 JPA 로직 부분이 제대로 됐는지 확인해주시면 감사하겠습니다!!

## 🚀 요구사항 분석
- [x]  로드맵을 생성한다.
    - [x]  **카테고리**를 설정한다.
        - [x]  카테고리는 무조건 1개를 선택해야한다.
    - [x]  **제목**을 입력한다.
        - [x]  제목은 필수로 입력해야한다.
        - [x]  제목의 길이는 최소 1글자, 최대 40글자이다.
    - [x]  **소개글**을 입력한다.
        - [x]  소개글은 필수로 입력해야한다.
        - [x]  소개글의 길이는 최소 1글자, 최대 150글자이다.
    - [x]  **본문**을 입력한다.
        - [x]  본문은 선택사항이다.
        - [x]  본문의 길이는 최대 150글자이다.
    - [x]  **난이도**를 설정한다.
        - [x]  난이도는 필수로 설정해야한다.
        - [x]  난이도의 종류는 `VERY_EASY,EASY,NORMAL,DIFFICULT,VERY_DIFFICULT` 가 있다.
    - [x]  **전체 추천 소요 기간**을 설정한다.
        - [x]  전체 추천 소요 기간은 필수로 설정해야한다.
        - [x]  ‘기한 없음’을 설정할 수 있다. (이때는 0으로 입력한다.)
        - [x]  기간은 일 단위로 설정한다.
        - [x]  기간은 최소 1일에서 최대 1000일이다.
    - [x]  **각 로드맵 단계에 대한 제목**을 입력한다.
        - [x]  각 로드맵 단계의 제목은 필수로 입력한다.
        - [x]  제목은 최소 1글자, 최대 40글자이다.
    - [x]  **각 로드맵 단계에 대한 설명**을 입력한다.
        - [x]  각 로드맵 단계에 대한 설명(텍스트)은 필수로 입력한다.
            - [x]  설명은 최소 1글자, 최대 200글자이다.
        - [ ]  각 로드맵 단계에 대한 이미지는 선택사항이다.
            - [ ]  이미지를 첨부한다면 최대 2장으로 제한한다.
            - [ ]  이미지의 용량은 최대 10mb이다.

2023-07-15 17:09 UTC, Cl8D requested changes
고생하셨어요 밀리!! 👍
특히 테스트 케이스가 엄청 많아서 놀랐습니다... ;ㅅ;
새벽에 리뷰한 거라 몇 가지 빠뜨린 부분이 있을 수도 있어서, 또 리뷰 요청 주시면 다시 한 번 살펴볼게요 ㅎㅎ!!

그리고 이미지 받아오는 부분은 저도 한 번 고민해볼게요.
아마 `@ModelAttribute`나 `@RequestPart` 쓰면 될 것 같은데 우선 이미지 쪽은 다음 스프린트 때 진행해도 되니까 넘어갑시다! ㅋㅋㅋ (나중에 s3 받고 한 번에 하는 게 더 좋을 것 같네요)

이번 주 좀만 더 파이팅! 💪

2023-07-15 17:09 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +            final long 카테고리_id = 2L;
이렇게 명시적으로 아이디를 지정해주려면 컨텍스트를 초기화해줘야 할 것 같아요~
현재는 `@BeforeEach`로 인해서 테스트마다 계속 save를 저장하고 있기 때문에 id=2인 카테고리는 항상 존재하지 않을까요?!

2023-07-15 17:09 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/RoadmapRepositoryTest.java
> +                () -> assertThat(roadmapNodeRepository.findAll()).hasSize(2)
사이즈 검증 대신에 savedRoadmap을 통해 객체를 반환받고, 해당 객체값을 검증하는 테스트를 하는 게 좋을 것 같아요 😶
테스트 하실 때 쿼리 한 번 보시면 LAZY 전략으로 인해서 객체 접근 시 쿼리가 엄청 날아갈 텐데요!
최적화 과정은 `@BatchSize`나 fetch join 등을 활용할 수 있는데, 우선 이건 천천히 고민해봅시다 ㅎㅎ
물론 미리 적용해주시면 최고구요 👍

2023-07-15 17:09 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
> +        assertThat(roadmapService.create(request, creator)).isEqualTo(1L);
요기도 이왕이면 `usingRecursiveComparison()`을 활용해주세요! ㅋㅋㅋ

2023-07-16 08:43 UTC, younghoondoodoom approved these changes
고생 하셨습니다 밀리~! 역시 잘 짜시네요! 특히 인수테스트를 깔끔하게 잘 짜시네요👍
제 생각 코멘트 남겼으니까 참고 부탁드립니다!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
> +    }
이 부분은 애매하긴한데 1개 이상 존재해야한다는 제약 조건을 빼는건 어떨까요?? 이미 `RoadMap`에서 빈 생성자를 사용해서 완전히 이 객체가 이 제약 조건을 지킨다고 보기 어려운 것 같아요. 그리고 이 제약 조건으로 인해 희생하는 부분이 많은 것 같습니다ㅠㅠ

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +    }
`Roadmap`에서 addXXX를 사용했으니까 통일하는건 어떨까요?? 저는 수정이 아니라 추가라는 의미에서 add가 나은것 같습니다!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +    }
그리고 위에서 `nodes.getRoadmapNodes()`를 사용하는 것보다 `RoadmapNodes`에 위임할 수 있을 것 같습니다!
```java
private void updateRoadmapNodes(final RoadmapNodes nodes) {
        this.nodes.addAll(nodes);
        nodes.updateAllRoadmapContent(this);
    }
```

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
> +    }
메소드 분리를 해보시는건 어떨까요?? 저는 validateXXX로 해서 무엇을 검증하는지 분리 해놓는게 가독성이 더 좋더라고요!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
> +    }
양방향 연관관계 때문에 setter가 꼭 필요하겠네요! 하지만 다른데에서 이 메소드가 악용될 수 있을 것 같아요. 각 `RoadMapNode`는 하나의 content만 가져야하고 이는 변동이 없어야하는데, 수정될 여지가 있네요ㅠㅠ 
`RoadMapNode`의 `RoadmapContent`가 null일때만 수정할 수 있게 할 수 있을 것 같아요!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
> +@Getter
다른 엔티티에서도 언급하긴 했는데 모든 클래스에서 Getter는 필요할 때만 여는건 어떨가요..??

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
> +            throw new BadRequestException("로드맵의 노드는 최소" + ROADMAP_NODES_NIN_SIZE + "1개 이상 존재해야 합니다.");
이 부분도 아까 `RoadmapContents`와 비슷한 의견입니다!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/RoadmapContentRepository.java
> +}
이 인터페이스는 테스트에서만 사용이 되는거 같아요!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/persistence/RoadmapNodeRepository.java
> +}
이 인터페이스도 테스트에서만 사용이 되네요!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +    public ResponseEntity<Void> create(@AuthPrincipal final Member member,
controller에서 직접 `Member`를 사용하고 있네요! 저는 연관관계를 끊으려고 사용자 아이디를 문자열로 반환하고 있어요! 그거를 통해 `Member`는 service에서 찾는게 좀 더 나을 것 같아요!

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +        // TODO: member 관련 부분 제거
todo 감사합니다👍

2023-07-16 08:43 UTC, younghoondoodoom commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +            응답_상태_코드_검증(로드맵_생성_응답, HttpStatus.BAD_REQUEST);
에러 메세지도 검증할 수 있으면 하는게 좋을 거 같아요! 
```java
protected <T> T jsonToClass(final String responseBody, final TypeReference<T> typeReference) throws JsonProcessingException, UnsupportedEncodingException {
        return objectMapper.readValue(responseBody, typeReference);
    }
```
저는 위에 코드 이용해서 클래스로 변환한 다음 검증을 많이 하는데 리펙토링 해봐도 좋을 것 같네요! 
다른 부분도 마찬가지입니다!

2023-07-16 08:45 UTC, younghoondoodoom requested changes
모르고 Approve 해서 바꾸겠습니다😅

2023-07-16 13:35 UTC, Ohjintaek requested changes
테스트 코드가 자세했던 점이 인상적이었어요ㅎㅎ 제약조건들이 많아서 할 일이 많았겠다 싶네요...
엔티티 리스트들을 일급 컬렉션으로 묶어서 관리한 것도 좀 더 보기 편해서 좋았던 거 같아요. 저도 제 코드 리팩토링 할 때 바꿔봐야겠네요

2023-07-16 13:35 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +            응답_상태_코드_검증(로드맵_생성_응답, HttpStatus.CREATED);
CREATED 상태 코드를 반환할 때 location 헤더에도 값을 담아줬던 거로 기억하는데 같이 검증하면 좋을 거 같아요!!

2023-07-16 13:35 UTC, Ohjintaek commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +            final ErrorResponse 에러_메세지 = 로드맵_생성_응답.as(ErrorResponse.class);
이건 되는데 다른 테스트에 에러 메시지를 검증을 추가했더니 안 된다는 소리였군요 밀리...

차이점을 보니 `MethodArgumentNotValidException`을 호출하면 List<ErrorResponse>를 ResponseEntity에 담아서 반환한다는 것이었습니다. 다음처럼 하니까 되긴 하는데 좋은 방식인지는 잘 모르겠네요. 져니도 두둠도 다 다른 방식이라 아무거나 선택하셔도 될 거 같아요.
```java
//then
final List<ErrorResponse> 에러_메세지 = 로드맵_생성_응답.as(new TypeRef<>() {});
assertThat(에러_메세지.get(0).message()).isEqualTo("카테고리를 입력해주세요.");
```

2023-07-16 16:00 UTC, Cl8D commented
안녕하세요, 밀리! 추가적으로 리뷰 드리고 싶어서 댓글 남겨요.
두둠한테도 남겼던 리뷰여서 공통적으로 드립니다!

POST 요청에 대한 Rest-Docs에 대해서도 response-fields.snippet 적용한 것처럼 request-fields.snippet을 활용하는 게 좋을 것 같아요.
어떤 제약조건이 있는지 문서에 담겨있어야 하는데, 현재는 http request / response만 나오다 보니까 프론트분들이 별도의 문서를 또 확인하면서 작업해야 될 것 같다는 생각이 들어서요!
저는 이전에 이런 식으로 진행했었습니다!
```java
.andDo(
                documentationResultHandler.document(
                    requestFields(
                        fieldWithPath("id").description("사용자 아이디").ignored(),
                        fieldWithPath("role").description("사용자 권한(USER, ADMIN)"),
                        fieldWithPath("email").description("사용자 이메일")
                            .attributes(new Attributes.Attribute(RANGE, "5-50")),
                        fieldWithPath("password").description("사용자 비밀번호")
                            .attributes(new Attributes.Attribute(RANGE, "8-50")),
                        fieldWithPath("nickname").description("사용자 닉네임")
                            .attributes(new Attributes.Attribute(RANGE, "1-30")),
                        fieldWithPath("telephone").description("사용자 전화번호 (010-xxxx-xxxx)")
                            .attributes(new Attributes.Attribute(RANGE, "13"))
                    ),
                    responseHeaders(
                        headerWithName("Location").description("사용자 세부 정보 URI")
                    )
                )
            );
```
필드 이름과 필드에 대한 설명, 필드의 제약 조건을 함께 넣었었어요! (optional한 정보라면 .optional()을 이용하구요)
response-fields에 대해서 커스텀 하는 방식이랑 거의 동일합니다!

2023-07-17 06:09 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +    public ResponseEntity<Void> create(@AuthPrincipal final Member member,
이 부분은 로그인 API 머지되면 추후에 수정할게요!

2023-07-17 06:15 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
> +        return ResponseEntity.created(URI.create("/roadmaps/" + id)).build();
노션에 작성된 API 명세서 말씀이시죠?? 감사합니다 업데이트 했습니다~

2023-07-17 06:28 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +    public Roadmap(final String title, final String introduction, final int requiredPeriod,
status와 contents의 디폴트 값을 설정해주는쪽으로 수정해서 체이닝을 사용하지 않도록 했어요!

2023-07-17 06:46 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +    }
그렇군요! 감사합니다 ㅎㅎ

2023-07-17 11:23 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +    }
저도 set은 별로인 것 같아요!
setXXX -> updateXXX로 변경하고, updateXXX -> addXXX로 변경했습니다!

2023-07-17 12:31 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +    }
좋아요 일단 다들 사용하셨으니 수정하겠습니다!

2023-07-17 12:42 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapSaveDto.java
> +        RoadmapDifficulty difficulty,
RoadmapDifficultyType을 만들어놓고 안썼네요..! 
그런데 RoadmapSaveDto는 컨트롤러에서 사용하지 않고, service 패키지 하위에 있는데도 RoadmapDifficultyType을 써야할까요??

2023-07-17 15:22 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapContentTest.java
> +@SuppressWarnings("NonAsciiCharacters")
SuppressWarnings는 상속이 안되는 것 같아서 DisplayNameGeneration만 있는 클래스를 상속하기에는 굳이인가.. 싶어서 그냥 일단 제거했습니다🥲

2023-07-17 15:57 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +            final long 카테고리_id = 2L;
헉 그렇네요..!
일단은 @sql 로 데이터 지워주는 작업했습니다~ 추후에 썬샷이 작성해주신 DatabaseCleaner를 사용하게 된다면 변경하겠습니다!

2023-07-17 17:26 UTC, miseongk commented
안녕하세요 리뷰가 많아서 반영하는데도 하루가 걸리네요😭
아직 resolve 되지않은 코멘트를 봐주시면 감사하겠습니다!

그리고 두둠이 남겨주신 코멘트 https://github.com/woowacourse-teams/2023-co-kirikiri/pull/8#discussion_r1264634858 를 반영해서 `RoadmapContents`와 `RoadmapNodes`에 있던 '1개 이상 존재해야한다는 제약 조건'을 모두 제거했습니다!
다시 한 번 확인 부탁드려요🙇‍♀️

2023-07-18 03:22 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapSaveDto.java
> +        RoadmapDifficulty difficulty,
아 제가 잘못 알았네요!! 서비스에서만 사용하는 객체니까 변하지 않아도 될 것 같아요! ㅎㅎㅎ

2023-07-18 03:25 UTC, Cl8D commented
고생하셨어요 밀리~!!
approve 할게요! develop으로만 merge 하실 때 신경써 주세요!! 💪

2023-07-18 04:22 UTC, Cl8D approved these changes

2023-07-18 04:23 UTC, Ohjintaek approved these changes
리뷰 적용하느라 수고하셨어요 밀리

2023-07-18 04:25 UTC, miseongk commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
> +    private final List<RoadmapContent> contents = new ArrayList<>();
일단은 굳이 Set을 써야할 이유도 없는것 같아서 List로 놔두겠습니다!
데이터베이스에서 받아올때 정렬해서 받아오면 되긴 하지만, RoadmapContent 보여줄 때 가장 최신의 데이터를 찾아내야 하는 경우도 있을 것 같아서요!

2023-07-18 05:12 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
> +    private final List<RoadmapContent> contents = new ArrayList<>();
그렇군요! 정렬할 필요가 있다면 List가 나을 것 같습니다👍

2023-07-18 05:20 UTC, younghoondoodoom approved these changes
고생하셨습니다 밀리~🙇‍♂️

2023-07-18 08:47 UTC, merged