[feat/CK-17] 로드맵 단일 조회 기능을 구현한다
woowacourse-teams/2023-co-kirikiri pull request #9
Opened 2023-07-15 11:56 UTC by Ohjintaek

## 📌 작업 이슈 번호
[CK-17](https://co-kirikiri.atlassian.net/jira/software/projects/CK/boards/1?selectedIssue=CK-17)

## ✨ 작업 내용
- 로드맵 단일 조회 API 기능을 추가하였습니다.
- 하나의 로드맵에 대한 정보를 요청받았을 때 현재 로드맵이 가지는 가장 최신의 컨텐츠에 대한 정보에 대해서만 반환합니다. (수정되기 이전의 정보들은 반환하지 않습니다)
- @DirtestContext를 사용하지 않기 위해 `DatabaseCleaner`라는 객체를 만들어 `IntegrationTest` 내부에 주입되도록 했습니다. @Sql과 비교해서 장점은 테이블 간 상속 관계를 신경쓰지 않고 테이블을 지울 수 있도록 `"SET REFERENTIAL_INTEGRITY FALSE"`를 실행한다는 점입니다.

## 💬 리뷰어에게 남길 멘트
- 현재 요청에 대한 응답을 SingleRoadmapResponse<RoadmapDetailResponse>로 전달하고 있는데 각 Dto의 네이밍에 대해 코멘트해주시면 감사하겠습니다. 또한 굳이 RoadmapDetailResponse라는 Dto를 만든 이유는 추후에 단일 로드맵을 조회하는 페이지에서 로드맵과 관련없는 정보(ex. 관련있는 로드맵 추천)들이 포함될 여지가 있다고 `우디`와 토의할 때 판단했기 때문입니다. 이 부분에 대해서도 생각을 들려주셨으면 좋겟습니다.
- 추가한 `DatabaseCleaner`에 대해 간단히 설명드리자면 현재 데이터베이스 내에 존재하는 모든 테이블의 이름을 Connection의 메타데이터에서 읽어와서 저장한 뒤 각 테스트 메서드가 끝날 때마다 연관관계 상관없이 지운 뒤 다시 생성하는 방식입니다. 다만 테스트에서 사용하는 h2 database의 특성인지 저희가 생성하지 않은 테이블들의 이름이 metadata를 조회할 때 같이 저장됩니다. 다만 실제로는 그런 디폴트 테이블명으로는 테이블을 생성하지 않아 존재하지 않는 테이블을 지우려고 하니 SQL Exception이 발생하는 문제가 있었습니다. 그래서 저희가 생성하는 테이블들의 이름을 따로 위에 저장해두는 식으로 구현했습니다. 단순히 하나의 제안으로 추가한 부분이니 나중에 같이 얘기나눴으면 좋을 거 같습니다.
- JPA나 RestDocs을 처음 써 보는 거라 잘못된 부분이 많을 수 있습니다. 잘 부탁드려요!!!

## 🚀 요구사항 분석
- [x] 단일 로드맵 정보를 조회할 수 있다.
    - [x] 로드맵의 id에 해당하는 카테고리, 제목, 소개글, 난이도, 추천 기간을 가져온다. (RoadmapRepository)
    - [x] 로드맵의 id에 해당하는 가장 최신의 로드맵 내용을 가져온다.
    - [x] 로드맵의 최신 내용의 id에 해당하는 노드 리스트들을 가져온다.
    - [x] 로드맵을 만든 유저의 id와 닉네임을 가져온다.
- [ ] 해당 로드맵으로 진행 중인 모든 골룸의 수를 가져온다. (추후 구현 필요)
- [ ] 해당 로드맵을 완료한 유저의 수를 가져온다. (추후 구현 필요)

2023-07-16 04:33 UTC, Cl8D requested changes
고생하셨어요 썬샷~!
로드맵 리스트 조회랑 비슷한 내용이 많아서 빠르게 리뷰가 가능했어요 ㅎㅎ
리뷰 보시구 수정할 부분 한 번씩 체크 부탁드려요 🙇‍♀️

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +
생성자 체이닝 👍
저는 개인적으로 체이닝 시 모든 인자가 있는 생성자를 기준으로 거는 편인데, 썬샷은 어떻게 생각하시나요?
ex) `this(null, null, nodes)`
중간 생성자를 사용하게 되면 한 번 더 생성자의 값을 봐야 해서 조금 불편할 수 있을 것 같아요!

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +        }
두둠한테 받았던 피드백인데, 썬샷도 적용해보시면 좋을 것 같아요~
[리뷰 내용](https://github.com/woowacourse-teams/2023-co-kirikiri/pull/3#discussion_r1262120656)
develop-backend 브랜치에 해당 내용이 적용되어 있어서 패스하셔도 괜찮습니다! (merge 시에 참고해 주셔도 돼요 ㅎㅎ)

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +        return RoadmapMapper.convertSingleRoadmapResponse(roadmap);
단일 조회라는 명칭에 대해서 `Single`이라는 prefix를 사용하셨네요!
저는 개인적으로 단일 조회는 단수형, 복수 조회는 복수형으로 사용하는 편이어서 prefix를 꼭 붙여야 할까? 라는 생각이 들어요!

또한,`roadmapRepository.findById()`을 반환하는 로직을 1차적으로 메서드로 분리한 다음에 (findById()) mapper를 통해서 response를 반환하는 것이니까 `findRoadmapResponseById()`와 같이 진행해줘도 될 것 같아요 ㅎㅎ

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/SingleRoadmapResponse.java
> +) {
> 굳이 RoadmapDetailResponse라는 Dto를 만든 이유는 추후에 단일 로드맵을 조회하는 페이지에서 로드맵과 관련없는 정보(ex. 관련있는 로드맵 추천)들이 포함될 여지가 있다고 우디와 토의할 때 판단했기 때문입니다. 이 부분에 대해서도 생각을 들려주셨으면 좋겟습니다.

저는 API 스펙에 따라서 달라질 것 같아요!
관련있는 로드맵 추천의 경우 로드맵 단일 조회 시 한 번에 내려가는 값이라기보다는, 클라이언트가 한 번 더 API 요청을 통해서 받아가야 하는 값이라는 생각이 들어서 별도의 객체로 생성되지 않을까? 라는 생각이 드네요 ㅎㅎ
(조회의 경우 정말 빈번하게 일어나는 작업일 텐데 한 번에 너무 많은 데이터를 내려주려고 하면 오히려 부하가 생길 수 있는 포인트이고, 단일 조회부터 발생시킨 다음에 추천 로드맵 정보까지 사용자 스크롤이 닿았을 때 api 호출을 LAZY하게 호출할 수도 있는 것이니까...) 이 부분은 다른 분들의 의견도 궁금하네요!

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
> +                roadmap.getRecentContent().getContent(),
연관있는 변수끼리는 한 번씩 추출해주면 더 가독성이 좋아질 것 같아요! (디미터의 법칙)
ex) `roadmap.getCategory()`, `roadmap.getCreator()`...

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/DatabaseCleaner.java
> +    @PersistenceContext
> @DirtestContext를 사용하지 않기 위해 DatabaseCleaner라는 객체를 만들어 IntegrationTest 내부에 주입되도록 했습니다. https://github.com/Sql과 비교해서 장점은 테이블 간 상속 관계를 신경쓰지 않고 테이블을 지울 수 있도록 "SET REFERENTIAL_INTEGRITY FALSE"를 실행한다는 점입니다.

👍
저는 너무 좋은 방법인 것 같아요! 
테이블 이름을 저렇게 정적으로 지정할 수도 있지만, `dataSource`를 활용하면 동적으로도 주입받을 수 있답니다 🚀

```java
    @Autowired
    private DataSource dataSource;

    private static final List<String> SYSTEM_TABLE_NAMES = List.of(
        "CONSTANTS", "ENUM_VALUES", "INDEXES", "INDEX_COLUMNS", "INFORMATION_SCHEMA_CATALOG_NAME", "IN_DOUBT", "LOCKS",
        "QUERY_STATISTICS", "RIGHTS", "ROLES", "SESSIONS", "SESSION_STATE", "SETTINGS", "SYNONYMS", "USERS"
    );

    @Test
    public void test() {
        List<String> tableNames = new ArrayList<>();
        try {
            DatabaseMetaData metaData = dataSource.getConnection().getMetaData();
            ResultSet tables = metaData.getTables(null, null, null, new String[]{"TABLE"});
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (!SYSTEM_TABLE_NAMES.contains(tableName)) {
                    tableNames.add(tableName);
                }
            }
            System.out.println("tableNames = " + tableNames);
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }
```

시스템 관련 테이블들을 상수로 정의하고, 저희가 생성한 테이블들만 받아오는 코드입니다 ㅎ_ㅎ

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +    }
ㅋㅋㅋㅋㅋ 썬샷의 취향이 담긴 로드맵 👍

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
> +@ActiveProfiles("test")
`RoadmapServiceTest`의 경우 mocking된 데이터를 받아오기 때문에 profile 정보를 지정해줄 필요는 없을 것 같아요 😊

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
> +    }
단일 로드맵 조회 시 반환되는 정보가 워낙 많고, LAZY 전략으로 걸려 있는 필드들로 인해 아마 쿼리가 우수수 나갈 거예요!
(현재는 save와 findById가 같은 트랜잭션 내에 묶여서 아마 확인이 안 될 테지만요!)
n+1 문제 같은 쿼리 최적화는 함께 고민해봐요 🚀 (`@BatchSize`, fetch join, 혹은 일반 join + dto 활용 등)

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
> +        return new Member(1L, "아이디", "패스워드", memberProfile);
나중에 develop-backend로 merge 하실 때 member 생성 시 id, password 모두에 제약 조건이 있어서 아마 테스트 통과가 안 되실 거예요! merge 후 꼭 테스트 돌려서 확인해주세요!!

2023-07-16 04:33 UTC, Cl8D commented on backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
> +                .andExpect(jsonPath("$.message").value("존재하지 않는 로드맵입니다. roadmapId = 2"));
저도 뭔가 빼먹었던 것 같은데, 예외 발생 시에도 `documentationResultHandler.document`을 활용해서 `responseFields`를 지정해주면 좋을 것 같아요! (문서에 Http Response까지만 나와있어서 ㅎㅎㅎ) 저두 다음 스프린트 때 수정해야겠네요...

2023-07-16 16:38 UTC, miseongk approved these changes
썬샷 고생하셨습니다~~👍
깔끔하게 잘 구현하신것 같아요!
저는 큰 수정 사항을 남기지 않아서 approve 하겠습니다~

2023-07-16 16:38 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/DatabaseCleaner.java
> +    @PersistenceContext
오 아주 멋진 방법 같아요👍👍👍

2023-07-16 16:38 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/DatabaseCleaner.java
> +@Transactional
혹시 Transactional 어노테이션을 붙인 이유가 있을까요??

2023-07-16 16:38 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +        final Roadmap 로드맵 = 로드맵을_생성한다(사용자, 카테고리);
`로드맵`이라는 변수는 사용되지 않는 변수네요! 제거해도 좋을 것 같아요!

2023-07-16 16:38 UTC, miseongk commented on backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
> +                .get("/roadmaps/{roadmapId}", 요청하는_로드맵_아이디)
`요청하는 로드맵 아이디`보다 `존재하지 않는 로드맵 아이디`가 좀 더 이해하기 쉬울 것 같네요 ㅎㅎ

2023-07-17 08:58 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +        }
Optional<RoadmapContent>를 반환하는 형태로 수정해주었는데 외부에서 get()을 통해 꺼내려고 할 때 null일 때 예외 처리에 대해 고민이 됩니다. `NosuchElementException`이 발생하면 따로 예외처리하지 않고 그대로 500 http status를 반환하도록 할지, 따로 예외처리를 해 줄지 조언을 주시면 감사하겠습니다

2023-07-17 15:35 UTC, younghoondoodoom requested changes
역시 깔끔하게 잘 짜시네요! 여러부분에서 썬샷이 많이 고민하신 흔적이 보이네요👍
너무 늦게 리뷰 해드리는것 같아서 죄송하네요.. 그래서 최대한 프로덕션 코드 위주로만 가볍게 코멘트 남겨봤습니다! 고생 하셨습니다💪

2023-07-17 15:35 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +@Getter
다른 엔티티도 비슷한 생각입니다!

2023-07-17 15:35 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/SingleRoadmapResponse.java
> +) {
저도 그런 경우 API가 분리되는게 나을 것 같다는 생각이 드네요! API도 최대한 단일 책임 원칙이 적용되는게 좋은 것 같습니다. 물론 그게 안되는 경우에는 어쩔 수 없지만요!

2023-07-17 15:35 UTC, younghoondoodoom commented on backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
> +                roadmap.getRecentContent().getContent(),
mapper라서 디미터 법칙의 예외가 있겠지만 최대한 지키는게 좋을 것 같긴 합니다..!
`ex) roadmap.getCreator().getMemberProfile().getNickname()) -> roadmap.getCreator().getNickName()`

2023-07-17 15:41 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
> +
평소에 하나씩 내려가면서 보느라 불편한 걸 몰랐는데 그럴 수 있겠군요...
수정해주었습니다!!

2023-07-17 15:42 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
> +        return contents.get(contents.size() - 1);
Comparator를 사용해서 RoadmapContents 내부에서 정렬하는 방법을 사용했는데 테스트를 작성하기가 곤란한 부분이 있네요. 일단 DB에 저장되어야 createdAt 값이 생성이 되어서 repository에서 테스트 하는 것으로 만들었어요

2023-07-17 15:44 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
> +        return RoadmapMapper.convertSingleRoadmapResponse(roadmap);
여기서 Single이라는 prefix를 떼 버린다면 우디와 상의해서 API를 조금 수정하는 게 낫겠네요. 저도 그냥 RoadmapResponse로 반환하는 것이 나을 거 같아 내일 상의 후 바로 수정하겠습니다!!

2023-07-17 16:47 UTC, Ohjintaek commented on backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
> +    }
감사합니다!!
양방향 연관관계 신경쓰기 어렵네요😅

2023-07-18 05:27 UTC, Ohjintaek commented
리뷰해 주신 내용 적용했습니다!!!
특별히 말씀드리고 싶은 내용은 로드맵에 대한 컨텐츠를 도메인 내부에서 createdAt순으로 정렬해주기 위해 BaseEntity에 getCreatedAt를 추가했는데 마음에 안 드시는 분 계실 수 있을 거 같아서 의견을 물어보고 싶습니다. 그냥 쿼리로 해결해보는 게 나을까요?

2023-07-18 05:56 UTC, Cl8D commented
> 리뷰해 주신 내용 적용했습니다!!! 특별히 말씀드리고 싶은 내용은 로드맵에 대한 컨텐츠를 도메인 내부에서 createdAt순으로 정렬해주기 위해 BaseEntity에 getCreatedAt를 추가했는데 마음에 안 드시는 분 계실 수 있을 거 같아서 의견을 물어보고 싶습니다. 그냥 쿼리로 해결해보는 게 나을까요?

쿼리를 사용하게 되면 아마 서브 쿼리로 해결해야 할 것 같은데, 생각해보니 하나의 로드맵에 존재하는 컨텐츠가 엄청 많을 것 같지는 않아서 (골룸이 생성된 경우에만 새롭게 추가될 테니까, 수정이 연속적으로 발생하는 게 아니라면 수정 - 골룸 생성 - 수정 - 골룸 생성... 과 같은 로직들이 크게 일어날 것 같지는 않아서요!), 테이블 내에서 정렬하는 것보다는 도메인 로직으로 가져오는 게 좋을 것 같아요. 썬샷의 구현 방식 저는 좋습니다 😊
 
> 추가적으로 빈값이 아니어야 하는 로드맵의 컨텐츠가 빈값일 경우 현재 NosuchElementException이 발생하고 ExceptionHandler가 검출해서 NOT FOUND(404)를 반환하는데 적절한지도 생각을 말씀해주시면 감사하겠습니다
저는 개인적으로 처음부터 NotFoundException을 터트리는 게 더 좋을 것 같아요! 근데 Optional로 반환값을 받으면 `NosuchElementException`이 안 터지지 않나요?!

2023-07-18 07:07 UTC, younghoondoodoom approved these changes
> 특별히 말씀드리고 싶은 내용은 로드맵에 대한 컨텐츠를 도메인 내부에서 createdAt순으로 정렬해주기 위해 BaseEntity에 getCreatedAt를 추가했는데 마음에 안 드시는 분 계실 수 있을 거 같아서 의견을 물어보고 싶습니다. 그냥 쿼리로 해결해보는 게 나을까요?

음.. 고민되는데요 개인적으로는 createdAt 같은 경우에는 쿼리를 활용하는게 더 좋다고 생각합니다. 저는 단 하나만 가져오는 쿼리로 바꾸던가 (sub query select 이용) 따로 쿼리를 보내는게 좋을 것 같습니다. 개인적으로는 전자를 선호합니다!

> 추가적으로 빈값이 아니어야 하는 로드맵의 컨텐츠가 빈값일 경우 현재 NosuchElementException이 발생하고 ExceptionHandler가 검출해서 NOT FOUND(404)를 반환하는데 적절한지도 생각을 말씀해주시면 감사하겠습니다

만약 `NoSuchElementException`이 난다면 `RoadmapContents`에서 `contents.get(0)`을 호출할 때 날 것 같습니다. 그 부분에서부터 Optional로 반환하는 건 어떤가요? 로드맵에서는 그걸 그대로 전달만 하면 될 것 같아요! 
```java
 public Optional<RoadmapContent> getRecentContent() {
        if (contents.isEmpty()) {
            return Optional.empty();
        }
        contents.sort(Comparator.comparing(RoadmapContent::getCreatedAt).reversed());
        return Optional.of(contents.get(0));
    }
```
이렇게 되면 `NosuchElementException`이 발생할 여지는 없앨 수 있고, `ExceptionHandler`에서 잡을 필요가 없다고 생각합니다! 
만약 모든 `NosuchElementException`을 받게되면 예상치 못하는 예외까지 모두 받게 되는 위험이 있을 것 같습니다!

2023-07-18 10:40 UTC, merged