Feature/ck 136
woowacourse-teams/2023-co-kirikiri pull request #97
Opened 2023-08-07 06:38 UTC by NaveOWO

## 📌 작업 이슈 번호

## ✨ 작업 내용

## 💬 리뷰어에게 남길 멘트

## 🚀 요구사항 분석

2023-08-07 07:04 UTC, sh981013s approved these changes
월요일부터 달리시는군요! 덕분에 자극을 받네요! 👍

너무 고생하셨고 코멘트 확인 부탁드려요!

2023-08-07 07:04 UTC, sh981013s commented on client/src/hooks/_common/useIdentifyUser.ts
> +};
너무너무 좋아요! 다만 걸리는 부분들만 사알짝 짚어볼게요!

useEffect 내에서 비동기 작업을 수행할 때는 작업이 완료되기 전에 컴포넌트가 언마운트될 수 있음을 주의해야 할 것 같아요! 컴포넌트가 언마운트되고 상태를 설정하려고 시도하면 메모리 누수를 일으킬 수 있으니까요. useEffect의 clean-up 함수에서 비동기 작업을 취소하거나, 상태 업데이트를 시도하기 전에 컴포넌트가 마운트 상태인지 확인해야 하는 건 어떨까요??

2023-08-07 07:04 UTC, sh981013s commented on client/src/hooks/user/useValidationCheck.ts
>  };
아예 구현부와 사용처를 없애도 좋을 것 같군요..!

2023-08-07 07:04 UTC, sh981013s commented on client/src/App.tsx
> +        <ToastProvider>
🙃🙃🙃🙃🙃

2023-08-07 07:05 UTC, sh981013s requested changes
위에서 어푸르부를 눌렀어서.. 😅 코멘트 확인 부탁드려요!

2023-08-07 07:52 UTC, evencoding approved these changes
네이브 주말에 버그 고치느라 너무 고생하셨어요😭

너무 좋습니다!
바로 approve 할게요🤩

2023-08-09 05:01 UTC, NaveOWO commented on client/src/hooks/_common/useIdentifyUser.ts
> +};
완전 하나 배워가요... 수정사항 확인해주세요!

2023-08-09 05:01 UTC, NaveOWO commented on client/src/hooks/user/useValidationCheck.ts
>  };
굿굿 지우겠습니다

2023-08-09 05:07 UTC, sh981013s approved these changes
vㅔ리베리 굳입니다!!!! 고생하셨어요~

2023-08-09 05:07 UTC, sh981013s commented on client/src/hooks/_common/useIdentifyUser.ts
> +    return () => fetchController.abort();
호오우 `AbortController` 를 사용하셨군요..! 너무 좋습니다! 👍👍👍

2023-08-09 05:08 UTC, sh981013s commented on client/src/hooks/_common/useIdentifyUser.ts
> +};
확인했어요!! 너무너무 좋습니다!!

2023-08-09 06:36 UTC, merged